### ISSUE TITLE
Define requirements

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#1]
**1. main Landing page** 
"COVID-19 Barometer" (NL)
"baromètre COVID-19" (FR)
"COVID-19 Barometer" (ENG)

**2. (sub-)project landing pages**
2.1.1 "COVID-19 Barometer: huisartsen" (NL)
2.1.2 "baromètre COVID-19: médecins généralistes" (FR)
2.2.1 "COVID-19 Barometer: Coördinerend en raadgevend artsen " (NL)
2.2.2"baromètre COVID-19: Médecin coordinateur et conseiller" (FR)
2.3.1 "COVID-19 Barometer: triage posten" (NL)
2.3.2 "baromètre COVID-19: postes de triage" (FR)
2.4.1 "COVID-19 Barometer: apothekers" (NL)
2.4.2 "baromètre COVID-19: pharmaciens" (FR)

**3. Forms to be created (seperate cards will be made)**
FIRST WAVE: GO LIVE MONDAY 23.03.2020
3.1 "Formulieren voor huisartsen":
3.1.1. Registratie formulier
3.1.2. Dagelijkse status formulier 
3.2. "Formulieren voor Coördinerend en raadgevend artsen":
3.2.1 Registratie formulier
3.2.2 Dagelijkse status formulier 
3.3. "Formulieren voor triage posten"
3.3.1 Registratie formulier
3.3.2 Dagelijkse status formulier 
3.4. "Formulieren voor apothekers"
3.4.1 Registratie formulier
3.4.2 Dagelijkse status formulier 

SECOND WAVE: GO LIVE UNKNOWN
3.5. "forms for **Midwives**"
3.6. "forms for **?**"

**Destinaton of the forms:**
- all forms will be transferred to SFTP server of healthdata.be

**Format of the registered data:**
- For each "daily status form" all registered data should be consolidated in a CSV file.

**Frequency of registration:**
- Registratie formulier huisartsen => 1 time (first time)
- Dagelijkse status formulier huisartsen => daily 
- Registratie formulier Coördinerend en raadgevend artsen => 1 time (first time)
- Dagelijkse status formulier Coördinerend en raadgevend artsen => daily 
- Registratie formulier triage posten => 1 time (first time)
- Dagelijkse status formulier triage posten => daily 
- Registratie formulier apothekers => 1 time (first time)
- Dagelijkse status formulier apothekers => 2 times each week

**Comment by VrankenKris** [comment]
Because this is an ever chaning issue, and is followed by Evelyne now, this ticket can be closed
