### ISSUE TITLE
Create "Daily status form for Pharmacists"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#10]

**Comment by JohanvanBussel** [comment]
Form that will be completed on daily basis
no user acces needed

Dutch and french have own version of form:
- "Status formulier voor apothekers " (NL)
- "Formulaire de statut pour les pharmaciens" (FR)

Doc:
- NL: https://docs.google.com/forms/d/1QnldrIW--nyx9vRvegDXTajx9oZjZU-sNbVdiLc9SZc/viewform?ts=5e74d4ce&edit_requested=true
- FR: ?

**Comment by neuronick** [comment]
- The Google form is made multistep, but the second step contains only one questions and comments field. Should we replicate this or would one page be sufficient?
<br>
- Are there any preferences / requirements regarding field names?
  Current field (technical) names for this form:
  - tx_email
  - tx_pharmacy_name
  - tx_apb_number
  - tx_postal_code
  - cd_function
  - nr_num_employees_current
  - nr_num_patients_standard
  - nr_num_partients_yesterday
  - nr_num_partients_phone_standard
  - nr_num_partients_phone_yesterday
  - nr_num_employees_covid19_pos
  - nr_num_employees_quar
  - nr_num_employees_covid19_contact
  - fl_pharmacy_covid19_closed
  - cd_pharmacy_measures
  - cd_pharmacy_patient_warranty
  - fl_critical_tasks_completed
  - tx_comments
<br>
- Are there any preferences / requirements regarding code values for checkboxes / radios? Currently  numbers starting from 1 are used.

**Comment by JohanvanBussel** [comment]
OK for one page 
OK for suggested field (technical) names
OK for code values numbers starting from 1 are used

**Comment by neuronick** [comment]
Draft version of the form: 
https://hd4patient-acc.healthdata.be/nl/covid19/pharmacists/status

**Comment by JohanvanBussel** [comment]
The Dutch and the French introduction are both in the French version of the form.

![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/23bcfbb8-c8d4-4355-be89-4d9d3b829d61)

**Comment by neuronick** [comment]
Introductory text in French is fixed now.

**Comment by JohanvanBussel** [comment]
text field "Daily status form for Pharmacists"
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/2943a094-dc6b-4887-858f-625d9974a408)

text field "other forms"
![helptext_in_textfield.jpg](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/968234e3-6293-4e39-9569-b6ad84e7dd2c)

We need a standard approach for all forms ... Suggestion: do both! so
- helptext below the question
- helptext in the textfield

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/030b5169-fcd4-41f2-be59-81efadda54d2)

Dutch progress line is shown in french version of form. Needs to be the French progress line

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/4c7c0ca7-13f5-450d-a1c3-2a7b2477a8e4)

Dutch section name in french version of form. Should be set on french section name

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/a1364ac0-cb0b-4087-9866-7465d9d52518)

The current introsection should be removed and replaced by a shorter intro, similar like :

![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/4108f205-5b30-474f-b9dd-268b73a2fbf9)

New text (NL) :  Dit formulier bevat een aantal vragen die uw situatie als apotheker in kaart moet brengen. Met deze vragen hebben we als doel uw situatie en die van anderen in kaart te brengen en zo nodig met de feedback jullie hulp te kunnen aanbieden. De bedoeling is om deze vragen eerlijk in te vullen zodat de realiteit voldoende gereflecteerd wordt!
Gelieve feedback te geven wanneer je hulp nodig bent of 'Niet akkoord' aanduidt.

New text (FR) :  Ce formulaire contient quelques questions visant à mettre en lumière la situation à laquelle vous faites face en tant que pharmacien. Avec ces questions, nous visons à identifier vos besoins et ceux de vos confrères. Votre feedback nous aidera à vous fournir une assistance ciblée. Votre feedback honnête est necessaire pour que la réalité soit suffisamment reflétée!
Si vous avez besoin d'aide ou si votre réponse à une question est "pas d'accord" merci d'en expliquer la raison.

**Comment by maerckaert** [comment]
I've translated based on "triage center status form" but some translation are missing.

'#title': 'Welke van onderstaand materiaal ontbreekt in de apotheek waar u titularis van bent zodat u zelf minder veilig kan werken?'
  '#options':
    1: 'Niets ontbreekt MOMENTEEL'
    2: 'Ontsmettingsalcohol (voor eigen gebruik)'
    3: 'Alcogel (voor eigen gebruik)'
    4: 'Mondmaskers (voor eigen gebruik)'
    5: 'Handschoenen (voor eigen gebruik)'

'#placeholder': 'Gelieve te verduidelijken waarom u hulp nodig heeft.'

'#title': '<h2>Capaciteit voor de volgende openingsdag</h2>'
fl_capacity_next_day:
  '#title': 'Ik denk dat we voldoende capaciteit hebben (mensen & materiaal) om alle taken van onze eerstvolgende openingsdag uit te voeren.'

'#title': '<h2>Capaciteit komende week</h2>'
fl_capacity_next_week:
  '#title': 'Ik denk dat we voldoende capaciteit hebben (mensen & materiaal) om alle taken van de komende week uit te voeren.'

**Comment by JohanvanBussel** [comment]
Ok i’ll look into that

----------------------------------------------------------------------------------------------------
Johan van Bussel
Head of service
Healthdata.be
M + 32 485 85 16 97
Skype johan.vanbussel@sciensano.be
[cid:image001.jpg@01D54DCF.B4D16B10]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

**Comment by maerckaert** [comment]
Done!

**Comment by neuronick** [comment]
The header text has also been changed. as well as the placeholders for comments.
