### ISSUE TITLE
Pharmacists NL + FR: landingpage: ADD salutation (Beste Apotheker / Cher pharmacien, chère pharmacienne)

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#100]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/d0bbd3eb-8192-423b-a9dc-71e716eb863c)

ADD salutation top positon of text
=================================
NL:
Beste Apotheker,
=================================
FR:
Cher pharmacien, chère pharmacienne

**Comment by neuronick** [comment]
Changes added to ACC / PROD
