### ISSUE TITLE
GP FR (ONLY): status form : order of choices "Tabliers adaptés aux infections": BE CAREFULL !!!

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#105]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/4a248c28-e507-4c7e-9e47-c65f45acb503)

GP status form => section "Disponibilité du matériel médical" => "Tabliers adaptés aux infections" => CORRECT order of choices: SHOULD BE => 
- Grande pénurie
- Petite pénurie
- Petit surplus
- Grand surplus

NL = Correct 

**VERY IMPORTANT: to verify with Kris impact of this change on submissions already received !!! Does the value also have to be changed for french version PLEASE BE CAREFULL !!!**

**Comment by maerckaert** [comment]
The  changes in prod has been made at : 26/03/2020 at 12:54
The field name: "cd_infection_aprons"

**Comment by VrankenKris** [comment]
@JohanvanBussel decision needed : what ot do with data already sent to doclr

**Comment by JohanvanBussel** [comment]
Decision : sent update to doclr. Describe clearly the impact.
