### ISSUE TITLE
Provide and style tagcloud for COVID-related datasets

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#112]
Modules to consider (taking into account future migration of FAIR to D8):
- https://www.drupal.org/project/tagclouds (**looks like best choice**)
OR
- https://www.drupal.org/project/tagadelic + https://www.drupal.org/project/tagadelic_views

**Comment by JohanvanBussel** [comment]
I prefer https://www.drupal.org/project/tagclouds  with "Module Settings: Display Type ="Count" which is shown as "TagName(N)" where N is the number of times that term is used. (Image 3)

**Comment by neuronick** [comment]
@maerckaert 
Review of the current state of the implementation:

### Visualisation
- Visualisation is currently not working for me. Only the one term with the lowest tid is displayed.
- Tags in the tag cloud need to be clickable and should have the following URL pattern:
/search/field_tags/[term-name]-[tid]
(where _[term-name]_ is a lowercased version of the term name with '-' instead of spaces, if any).
- Tag size should set automatically and should be based on a tag weight (number of occurrences).
- Tag color can be assigned randomly (ideally from a list of predefined values, which, for example, could be provided as a comma-separated list of color values per block in a text-field or something).
- There are a lot of debugging-related console.log still present in the javascript. These should be cleaned up.
- Size of the tag-cloud / elements should not be hardcoded but instead be based / relative to the size of the parent container.

### Business Logic
- There should be a possibility to create more then one tag-cloud block. The number of available blocks should be changeable via variables / configuration. Each of the block should have its own configuration. See this for an example: https://stackoverflow.com/questions/12585912/how-to-allow-multiple-blocks-in-a-module-of-drupal
- No new vocabulary should be created. There is already a vocabulary called **Tags**. It should be used for the tag cloud.<br>
There is a table called **taxonomy_index**, which can be used for finding / filtering / counting the right terms. Once you have the **tids** with the count, you can then query the term names for display. 
  - For COVID-19 tags, only tags appearing in datasets with the **data source**: 'COVID-19' should be used. 
  - For AP-18 tags, only tags appearing in datasets with the **data source**: 'Metadata (AP18)' should be used.<br>

- Ideally the vocabulary should not be hardcoded at all but instead a **view** (selectable per : block) should be used, which will provide the list of terms and their 'weight' (number of occurrences). This way tag cloud can be used for anything accessible by the view (terms, nodes etc.)
The view result can the be used programatically like this:
```
$view = views_get_view('tag_cloud');
$view->set_items_per_page($number_of_tags_to_show);
$view->execute();
$tags = $view->result;
```
You can then process **$tags** array to get the list of tags needed for your javascript visualisation.

If you need an example of such view (with terms / weight, filtered by a specific data source) -> I can provide you with an example.

**Comment by evelynedewitte** [comment]
@JohanvanBussel 

Zie https://fair.healthdata.be/ waar de tag clouds werden toegevoegd.
