### ISSUE TITLE
Create, style, add new COVID19 header to FAIR frontpage

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#114]
The header should come under the menu (in place of the old FAIR header). The old FAIR header follows.

Styling can differ a bit, but here is the mockup from Johan:
![image](https://user-images.githubusercontent.com/838476/77787441-d7073800-705f-11ea-9f70-f69a2b9e58e6.png)

**Comment by evelynedewitte** [comment]
@neuronick @maerckaert 

As just discussed with Johan:

- Put a bar for COVID19 above the one for AP18
- Within that bar, put a search box for the COVID19 datasets + a link to the list of all COVID19 datasets
- Add "source" as a facet on the left

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/f82789e7-3511-4944-9362-fb98db6ab2e8)

Is this useful? 

![covid19.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/82e22fa6-62ff-48d9-8700-863c9a1632b0)

**Comment by JohanvanBussel** [comment]
![covid19.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/82e22fa6-62ff-48d9-8700-863c9a1632b0)

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/bee071fd-8b6d-490e-a430-19c0e5b9cec5)

1. Leave some white space between searchbox and "or browse the list of COIVD-19 Open data sets"
2. Put "or browse the list of COIVD-19 Open data sets" in bold
3. add link "https://fair-acc.healthdata.be/sources/covid19" on COVID19 graphic and title "COVID19 open data"

**Comment by JohanvanBussel** [comment]
CORRECT SPELLING: 
- COIVD = COVID
- SO: "or browse the list of COIVD-19 Open data sets" INTO "or browse the list of COVID-19 Open data sets"

**Comment by neuronick** [comment]
@JohanvanBussel the typo is fixed. Margin is updated. Link is added.

**Comment by neuronick** [comment]
'Alfa' version of the header is pushed to ACC / PROD.
