### ISSUE TITLE
Populate FAIR AP18 datasets with relevant tags

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#115]
- [x] Create a special technical page to facilitate tags "collection"
- [x] Create and populate the spreadsheet with the following columns: dataset UUID, '|' separated list of tags (based on existing facet values here: https://fair.healthdata.be/sources/metadata_projects)
- [x] Import and data from the excel spreadsheet above / populate tag field of relevant datasets with the provided tags.

**Comment by neuronick** [comment]
The special hidden page for tag "collection" can be found here:
https://fair.healthdata.be/sources/metadata_projects/tech

**Comment by evelynedewitte** [comment]
[https://app.zenhub.com/files/248791371/e12a2fb3-c6ef-4a9b-a88c-6caf6cb024d3/download](https://app.zenhub.com/files/248791371/e12a2fb3-c6ef-4a9b-a88c-6caf6cb024d3/download)

**Comment by evelynedewitte** [comment]
Nikita, attached the file with the tags per dataset
