### ISSUE TITLE
Update topbar to include 'About Sciensano' link

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#119]
![image.png](https://images.zenhubusercontent.com/5bfe64d282265008a04d697d/bce1c0d4-2797-447f-afa4-1e2d35d81fd0)

**Comment by maerckaert** [comment]
@neuronick It cannot be done as we expected.
Another solution has to be found.
The estimation points as to be changed.

**Comment by maerckaert** [comment]
@neuronick pushed on branch-114

**Comment by neuronick** [comment]
Deployed tot ACC / PROD.
