### ISSUE TITLE
Create COVID-19 Open Data catalog page

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#120]
- [x] Create a view for searching COVID-19 related datasets
- [x] Create / add facets
- [x] Create a panel page for the catalog page
- [x] Add link to the source on https://fair-acc.healthdata.be/sources

**Comment by neuronick** [comment]
Here is the first version:
https://fair-acc.healthdata.be/sources/covid19

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/5cfaff55-b919-495f-a6a5-0dba9d70448d)

CORRECT breadcrumbs : "Healthdata.be Metrics" => "COVID-19"

**Comment by neuronick** [comment]
Updated
