### ISSUE TITLE
Create COVID-19-related datasets / populate metadata fields

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#121]
Metadata needs to be foreseen for the following COVID19 datasets:

- [x] Pre-create COVID-related datasets. Pre-assign group / source.
- [x] Populate metadata / add necessary changes to GP Dataset: https://fair.healthdata.be/dataset/21d2b862-105c-44d5-b4a1-cf04efe2f071
- [x] Populate metadata / add necessary changes to CRA Dataset: https://fair.healthdata.be/dataset/a1679922-bc79-4d8c-b9ec-600c6fe3d42f
- [x] Populate metadata / add necessary changes to Pharmacists Dataset: https://fair.healthdata.be/dataset/ca720802-caa8-4dd0-a9a4-2202b783d866
- [x] Populate metadata / add necessary changes to Triage Posts Dataset: https://fair.healthdata.be/dataset/022c05d8-c232-4d66-a884-cf14c1996e80
- [x] Populate metadata / add necessary changes to Midwives Dataset: https://fair.healthdata.be/dataset/17651fcd-ab19-40ab-8bc9-0f00ce89ed61

**Comment by JohanvanBussel** [comment]
url of "Populate metadata / add necessary changes to Midwives Dataset" is the same as the one of GP ...
I did the rest already.

**Comment by neuronick** [comment]
@JohanvanBussel I have update the midwives url. sorry for that.

Could you also fill-in the description(s) with some text to provide some background / context for the dataset(s) in question?

**Comment by JohanvanBussel** [comment]
DONE !

**Comment by neuronick** [comment]
@JohanvanBussel:
For the facet publishers to be visible (https://fair-acc.healthdata.be/sources/covid19) we need to create / assign publishers to COVID related dataset.

Do we know / want to add the publishers for COVID to the FAIR platform? If yes, then
could you provide the titles / descriptions of the publishers and which datasets are they the publishers of?

Thanks!

**Comment by JohanvanBussel** [comment]
I propose to do this in second stage ... No blocking issue

**Comment by JohanvanBussel** [comment]
excel with tags for projects within COVID19 open data catalogue:
- https://www.dropbox.com/s/tljp4ujnt80qmtt/covid19_fair.tags.xlsx?dl=0

**Comment by neuronick** [comment]
I think there is nothing left to be done here. For Publisher ideally we will need to create a new issue anyway.

Moving to Done. Re-open if needed.

**Comment by JohanvanBussel** [comment]
Hello Nikita, yesterday, i tried to create a new dataset in prod version of fair : “Sciensano Epistat Covid”. I linked it with source COVID19, but cannot find it back again in the list of data sets …

----------------------------------------------------------------------------------------------------
Johan van Bussel
Head of service
Healthdata.be
M + 32 485 85 16 97
Skype johan.vanbussel@sciensano.be
[cid:image001.jpg@01D54DCF.B4D16B10]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

**Comment by neuronick** [comment]
It is visible now. I have created a ticket for myself to setup cron / search index update to run every hour.

**Comment by evelynedewitte** [comment]
@JohanvanBussel 

Is it OK for you that we close this ticket?

**Comment by JohanvanBussel** [comment]
OK for closing this ticket
