### ISSUE TITLE
Get / review all necessary COVID-19 related CSVs for FAIR

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#122]
- [x] Kris generates and provides files
- [x] Evelyne coordinates the effort
- [x] Nikita checks and upload the resources to the FAIR portal

**Comment by neuronick** [comment]
The open data files are not yet provided for: 
- hd_covid_pharmacist_status
- hd_covid_midwives_status

The rest looks good and is added.

**Comment by VrankenKris** [comment]
You are absolutely right. I wanted to wait until the new data arrived this morning… And then I forgot…

I will do it now.

Kris


Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

**Comment by neuronick** [comment]
@VrankenKris 
I have encountered some problems with these files (mostly non UTF-8 encoding):

- hd_covid_midwives_tx_measures_support.csv
- hd_covid_pharmacist_cd_pharmacy_measures.csv
- hd_covid_pharmacist_cd_scale_feel_supported_assoc.csv

I have converted them lockally, but because I don't have writing rights for the Dropbox folder, could you convert and reupload them there as well?

The rest fo the files is ok.

**Comment by JohanvanBussel** [comment]
csv file names : "hd_covid_" => should be "**covid19_**"
reason: this is not HD data ...

**Comment by VrankenKris** [comment]
@JohanvanBussel @neuronick @evelynedewitte @maerckaert  I will change and re run the program. I will also have a look at the UTF-8 encoding. You do not have to write files back to DropBox. DropBox is only a way to get files from SAS to FAIR, not a storage place. The storage is done in SAS...

**Comment by VrankenKris** [comment]
@neuronick can you check with this file: covid_midwives_tx_measures_support.csv
This should be in UTF-8

**Comment by VrankenKris** [comment]
confirmation received that all files are ok

**Comment by evelynedewitte** [comment]
@VrankenKris 

Voor GP mist er 1 bestand: covid19_gp_cd_num_respiratory_consultations.csv
