### ISSUE TITLE
Import / add COVID-19 related resources to the relevant datasets

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#123]
- [x] import CSV resource for: hd_covid_cra_status
- [x] import CSV resource for: hd_covid_gp_status
- [x] import CSV resource for: hd_covid_triage_status
- [x] import CSV resource for: hd_covid_pharmacist_status
- [x] import CSV resource for: hd_covid_midwives_status

**Comment by neuronick** [comment]
No Open data yet for:
- hd_covid_pharmacist_status
- hd_covid_midwives_status

The rest is added.

**Comment by neuronick** [comment]
Added: 
- hd_covid_pharmacist_status
- hd_covid_midwives_status

+ populated FAIR Datastores

**Comment by neuronick** [comment]
To review, go here: https://fair.healthdata.be/sources/covid19

Take a look inside datasets, make sure you can see / download resources.

**Comment by neuronick** [comment]
I assigned @JohanvanBussel  to this issue as well, as maybe he will want to change titles / add descriptions for the COVID-related resources in question.

**Comment by JohanvanBussel** [comment]
- In the **descriptions field of the resource**, the "**survey question**" related to that specific resource clould be entered... If that could be automated ... 
=> So resource = covid_gp_cd_alc_hand_disinfectant.csv => description : "**Beschikbaarheid medisch materiaal: Alcoholische handontsmetting**"

**Comment by evelynedewitte** [comment]
@VrankenKris @JohanvanBussel 

For midwives / pharmacists we changed 2 questions where numbers were asked for "yesterday" to the same information but for "today". For this, we put the "old" questions on hidden in the form and created 2 new questions. 

So on the FAIR site, today we still have the CSV files mentioned below. As both groups fill in the forms on Monday and Wednesday, I presume that on Thursday these files will disappear and be replaced by the ones for "today". Is that correct? So I know what to check on Thursday.

covid19_midwives_nr_num_clients_standard_yesterday.csv
covid19_midwives_nr_num_clients_phone_yesterday.csv

covid19_pharmacist_nr_num_partients_phone_yesterday.csv
covid19_pharmacist_nr_num_partients_yesterday.csv

**Comment by evelynedewitte** [comment]
@neuronick 

See the comment of Johan --> I am not seeing the description field per resource? Can we have a look at this tomorrow?

**Comment by JohanvanBussel** [comment]
De “yesterday” files currently on FAIR should stay on FAIR, but are not updated anymore. The “today” files will be added to the appropriate FAIR data set.

**Comment by VrankenKris** [comment]
Every day the files contain ALL data.
So, no appending needs to be done…

Kris

Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

**Comment by neuronick** [comment]
All COVID19 Barometer open data resources now have a relevant description / data dictionary
