### ISSUE TITLE
Create / add schema's per COVID19 resource type

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#124]
https://frictionlessdata.io/specs/table-schema/

**Comment by evelynedewitte** [comment]
@VrankenKris 
Deze wil ik graag oppakken, maar ik heb wat meer uitleg nodig over het waarom zodat ik goed begrijp wat de gewenste uitkomst is.

**Comment by neuronick** [comment]
@evelynedewitte I think I can help here :)

**Comment by neuronick** [comment]
This can be considered done, as we now have a data dictionary per resource in a table form.
