### ISSUE TITLE
Make sure all COVID-related resources are available via Datastore API

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#126]

**Comment by neuronick** [comment]
To validate:
- Select a number of COVID-19 related resources from different datasets
For each resource:
- Go to Data API tab
- Click on example Query to the the end-point producing response in JSON format.

![image](https://user-images.githubusercontent.com/838476/77861295-4faef580-7214-11ea-81c8-722c3cdc4bd2.png)

**Comment by evelynedewitte** [comment]
@neuronick 

This didn't seem to do anything. To check together.

**Comment by evelynedewitte** [comment]
Nothing to click...

![2020-04-09.png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/a4d021fc-6e6f-4b78-9926-ec283dbbc6cf)

**Comment by neuronick** [comment]
@evelynedewitte I had to temporarily remove this functionality as there is a bug in sorting mechanism on preview page.
Once we have updated to the latest DKAN version we should be able to use it again. I have added the ticket about update and dependency to this ticket.

**Comment by evelynedewitte** [comment]
@neuronick Ok, clear, thanks for the update.

**Comment by neuronick** [comment]
I have added automatic datastore reimport routine (as the datastore needs be dropped / reimported after each time opendata is reloaded).

Should be OK after the next open data load (after Tuesday 16.06)
