### ISSUE TITLE
Create "landing page for coördinerend en raadgevend arts"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#13]
Dutch title: "COVID-19 Barometer: coördinerend en raadgevend arts"
text: "Tijdens deze COVID-19 pandemie wenst het Academisch Centrum voor Huisartsgeneeskunde (ACHG) het netwerk van coördinerend en raadgevend artsen te ondersteunen die dagelijks in de klinische realiteit staan. Met een formulier wordt hun situatie en die van anderen in kaart gebracht en kan zo nodig met de feedback hulp aangeboden worden. 

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het informatieveiligheidscomité (referentie: IVC/KSZG/20/xxx).

- Start met de 
- Start met de 

French title: "Baromètre COVID-19: Médecin coordinateur et conseiller"
text: "to do"

**Comment by neuronick** [comment]
changes implemented

**Comment by JohanvanBussel** [comment]
Changes: sorry not my fault:
...............................
"Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerend en raadgevend artsen, triageposten en apothekers) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden. De monitoring bij de coördinerend en raadgevend artsen gebeurt elke dag, ongeveer om 18u00. 

Voor de coördinerend en raadgevend artsen werd deze barometer opgemaakt door het Academisch Centrum voor Huisartsgeneeskunde (Prof. Jan De Lepeleir) van de KULeuven. 
Deze barometer wordt gesteund door de volgende organisaties: ****, **** en ****.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, de COVID19 Risk Management Groep, en de Nationale Crisiscel.
Op basis van de gegevens die u registreert, ontvangt u gepersonaliseerde feedback verzorgd door Doclr.

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Uw e-mailadres wordt enkel gebruikt om de samenvatting van de resultaten naar u op te sturen en om de follow-up monitoring aan te kondigen. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig, kan steeds kan onderbroken worden, en alle gegevens zullen anoniem verwerkt worden.

Voor inhoudelijke vragen bij deze gegevensverzameling: emailadres
Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

Start met de barometer registratie.
..............................

franse versie volgt

**Comment by neuronick** [comment]
text updated
