### ISSUE TITLE
Test PROD data flow for Home nurses (independent) + Home nurses (employee)

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#130]
The form to test on PROD:
https://covid19.healthdata.be/nl/hn_emp/status
https://covid19.healthdata.be/fr/hn_emp/status (most of the translations are not provided yet)
https://covid19.healthdata.be/nl/hn_ind/status
https://covid19.healthdata.be/fr/hn_ind/status (most of the translations are not provided yet)

End-points configured on PROD:
http://10.72.128.65:9090/generic/hd_covid_hn_emp_status
http://10.72.128.65:9090/generic/hd_covid_hn_ind_status

**Comment by neuronick** [comment]
form deployed to PROD

**Comment by VrankenKris** [comment]
Tested 2 records in production, works fine (flagged the records so they are not downloaded this evening)
