### ISSUE TITLE
Update COVID_fields document for home nurses forms

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#131]
- [x] Add information on **hd_covid_hn_emp_status**: field names, labels, options, options translations
- [x] Add information on **hd_covid_hn_ind_status**: field names, labels, options, options translations

https://www.dropbox.com/scl/fi/1htdxm64uv963t82eajjs/COVID19_fields.xlsx

**Comment by neuronick** [comment]
Current information about the aforementioned forms is added to the document:
https://www.dropbox.com/scl/fi/1htdxm64uv963t82eajjs/COVID19_fields.xlsx

**Comment by evelynedewitte** [comment]
Attention!

@VrankenKris 

30/03: request from Tim to add 1 question to the form --> update the corresponding metadata!

**Comment by evelynedewitte** [comment]
@VrankenKris 
COVID19_fields were updated:

added for both nurses employed + nurses independent:
fl_capacity_next_days
tx_capacity_next_days_comments
