### ISSUE TITLE
FORMS: Verduidelijking tekorten/overschotten

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#134]
Vanuit de taskforce COVID19 Shortages (Kabinet De Backer) wordt gevraagd naar een begeleidende “RUWE indicatie” van de beschikbaarheid van middelen.

Verduidelijking: wat betekenen de termen "groot tekort", "klein tekort", "klein overschot", "groot overschot" voor de middelen "maskers", "schorten", "brillen", "gel" en "handschoenen zodat elke eerstelijnsmedewerker dit consistent kan invullen.

**Comment by JohanvanBussel** [comment]
Hallo Evelyn, verwacht wordt dat de overheden de Barometer deze week gaan promoten om de beschikbaarheid van materialen te meten. Daarvoor is de (ruwe) kwantificatie van de huidige kwalitatieve indicatie belangrijk. wat zijn de nodige nog te zetten stappen hierin? Johan

**Comment by evelynedewitte** [comment]
Dag Johan,
We zijn dit nu aan het implementeren. We beginnen met de home nurses, gezien we deze nu toch op ACC aan het zetten zijn en gaan zo verder met het updaten van alle formulieren die deze vraag bevat.

Zie issue 150 --> daar staat heel concreet wat voor wie moet gebeuren.

Dit issue was opdat ik ervoor zou zorgen dat er verduidelijking kwam met Bert Vaes. Dit issue ga ik dus afsluiten.
