### ISSUE TITLE
MIDWIFES FR: status form: create FR version

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#135]
Eline Tommelein provided us with the French text: landing page + questionnaire. 
The corresponding form for the FR Midwives has to be set up to be operational on 29/03.

**Comment by evelynedewitte** [comment]
https://docs.google.com/forms/d/13Cr_ABkaxlIxO-MDx9M0cEIop5wvPnLt4CjhDUF5nig/edit?ts=5e7cae10  

"pour les commentaires" --> check with Eline

**Comment by maerckaert** [comment]
@evelynedewitte 
This part is not translated:
"We stapten in een breder monitoringsproject waarin ook andere zorgverleners in de eerste lijn zijn opgenomen. Hieronder worden de 5 specifieke vragen weergegeven waarop men screent. "

**Comment by maerckaert** [comment]
@evelynedewitte 
Also this one: "Capaciteit voor de volgende openingsdag"

**Comment by maerckaert** [comment]
@evelynedewitte 
This one is only translate by: "Remarques"
"Indien u nog andere zaken wil opgenomen zien in deze vragenlijst, kan u dat hieronder weergeven. U kan ook andere suggesties of booschappen achterlaten. Wij zullen deze mee verwerken in de analyse. Wij danken u hartelijk voor uw medewerking, en steken alle collega''s een hart onder de riem!"

Is it correct?

**Comment by evelynedewitte** [comment]
@maerckaert @neuronick 

I have taken your remarks / questions and sent them to Eline for feedback. Keep you posted.

**Comment by evelynedewitte** [comment]
@maerckaert 

Response from Eline:

Onderstaande werd niet vertaald naar het Frans:
"We stapten in een breder monitoringsproject waarin ook andere zorgverleners in de eerste lijn zijn opgenomen. Hieronder worden de 5 specifieke vragen weergegeven waarop men screent. " 

Nous faisons partie d'un projet de surveillance plus large qui inclut également d'autres prestataires de soins dans les soins primaires. Vous trouverez ci-dessous les 5 questions spécifiques sur lesquelles les personnes sont projetées.


Onderstaande is enkel vertaald als "remarques":

"Indien u nog andere zaken wil opgenomen zien in deze vragenlijst, kan u dat hieronder weergeven. U kan ook andere suggesties of booschappen achterlaten. Wij zullen deze mee verwerken in de analyse. Wij danken u hartelijk voor uw medewerking, en steken alle collega''s een hart onder de riem!" 

Si vous souhaitez voir d'autres sujets inclus dans ce questionnaire, vous pouvez les indiquer ci-dessous. Vous pouvez également laisser d'autres suggestions ou messages. Nous les inclurons dans l'analyse. Nous vous remercions beaucoup pour votre coopération. Bon courage!

**Comment by evelynedewitte** [comment]
Validated on ACC: all is fine. There is one "legend" missing for the first scale 0-10 but we did not receive this ourselves. I will ask Eline.

@maerckaert

**Comment by evelynedewitte** [comment]
Closed --> merged with issue #138
