### ISSUE TITLE
Nurses Barometer: add metadata fields to COVID19_fields_xlsx

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#136]
2 new target groups: nurses (independent + employed)

For both, forms are created so that the data collection can be started. The corresponding metadata needs to be added to the file COVID19_fields_xlsx

**Comment by VrankenKris** [comment]
This is #133

**Comment by evelynedewitte** [comment]
COVID19_fields were updated for home nurses and are now complete, included French translations.
