### ISSUE TITLE
Nurses Barometer: specify data access rights

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#137]
Need to precise who can see the Nurses data + on what level of detail.

Add to: COVID19_barometer_UA.xlsx

Add to: COVID19_data_access_follow_up.xlxs

**Comment by evelynedewitte** [comment]
@VrankenKris 
As agreed with Kris: barometer fields not OK yet --> Kris + Evelyne will make a proposal for Johan on Monday morning 20/03

**Comment by JohanvanBussel** [comment]
•	Secretariaat NPTV: info@nptv.be
•	Uschi De Coster Uschi.De.Coster@vlaanderen.wgk.be

**Comment by VrankenKris** [comment]
This is done
