### ISSUE TITLE
MIDWIVES NL/FR: status form update (tekort/overschot)

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#138]
-  replace the question about lacking means with the samen questionnaire you ask GP practices (groot tekort, overschot…)

**Comment by evelynedewitte** [comment]
Mail from Eline Tommelein:

Dear Jonathan,
 
I added you to the google forms with the questionnaire for midwives in French.
 
I noticed a small mistake in the Dutch questionnaire though.
I asked to replace the question about lacking means with the samen questionnaire you ask GP practices (groot tekort, overschot…). This didn’t happen! Can you please change that for tomorrow evening?
 
As well in the French questionnaire this has to be added. These forms should already exist as they are available for the GP practices, so please copy and paste them from that questionnaire.
 
When you are ready, send me the links and I will validate!
 
Eline

**Comment by neuronick** [comment]
Changes deployed to ACC.

**Comment by evelynedewitte** [comment]
The request of Eline was to **replace** the question with the way it was done for GPs.

Instead, this has been added. Can you please remove the original question in both NL & FR forms please:

![2020-03-29 (1).png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/1ff0ad97-7a85-4e3f-b899-5c690e1c1636)

![2020-03-29 (2).png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/35813caf-b572-424e-b502-c64541f4ee92)

@maerckaert @neuronick

**Comment by evelynedewitte** [comment]
@maerckaert Can you always put the links to the forms in the comments? Otherwise I have to search for the right links and I'm loosing time :).

Thx.

**Comment by maerckaert** [comment]
Yes sure.
https://covid19-acc.healthdata.be/fr/sages-femmes/status
https://covid19-acc.healthdata.be/nl/vroedvrouwen/status

**Comment by evelynedewitte** [comment]
For the Dutch version the word "vroedkundige" needs to be replaced by "vroedvrouw" as apparently also the men are "vroedvrouwen" ;-)

@maerckaert

**Comment by evelynedewitte** [comment]
Update:

- Tested by me and validated
- Sent to Eline Tommelein for UAT
