### ISSUE TITLE
Update MIDWIVES UA and fields metadata

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#139]
The metadata (fields, User Access ) have to be loaded into the DB2 tables that are used to steer the SAS programs that read, load and export the data.

CHANGE requested by Eline Tommelein:
replace the question about lacking means with the samen questionnaire you ask GP practices (groot tekort, overschot…)

The metadata fields (fields, UA) need to be updated to reflect these changes.

**Comment by VrankenKris** [comment]
This will be tested the first time I execute the load to other organisations...
