### ISSUE TITLE
FAIR DATASET TEMPLATE: POSITION "Data and Resources" AFTER "Description","Dataset Information"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#140]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/e030cb41-380b-475b-bf42-465e18db4f73)

POSITION "Data and Resources" AFTER "Dataset Information", so order is:
1. "Description"
2. "Dataset Information"
3. "Data and Resources"
4. "Tags"

**Comment by evelynedewitte** [comment]
Reviewed and approved
