### ISSUE TITLE
MIDWIVES NL/FR: update 2 questions on status form

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#142]
Eline Tommelein decided to replace 2 questions about "yesterday" to "today"

Form NL now:
Hoeveel cliënten begeleidde u of de praktijk gisteren (enkel face-to-face)?
Hoeveel cliënten informeerde u of de praktijk gisteren telefonisch?

Form NL to be:
Hoeveel cliënten begeleidde u of de praktijk vandaag (enkel face-to-face)?
Hoeveel cliënten informeerde u of de praktijk vandaag telefonisch?

Form FR now:
Combien de clients vous ont guidé ou ont pratiqué hier (uniquement en face à face)
Combien de clients vous ou la pratique avez-vous informés hier par téléphone?

Form FR to be:
Combien de clients avez-vous pris en charge aujourd'hui (uniquement en face à face)?
Combien de clients avez-vous informés par téléphone aujourd'hui?

**Comment by maerckaert** [comment]
@evelynedewitte Are you sure about the French translation? For me, they are non sense.

**Comment by evelynedewitte** [comment]
@maerckaert 

You are right. I have updated them. Is this ok?

**Comment by maerckaert** [comment]
This one should be changed also:
Combien de clients vous ont guidé ou ont pratiqué hier (uniquement en face à face)
to
Combien de clients vous ou la pratique avez-vous informés hier (uniquement en face à face)

**Comment by evelynedewitte** [comment]
@maerckaert 

I imagine I changed the phrase while you were commenting. It is OK now, no?

**Comment by maerckaert** [comment]
Yes perfect!

**Comment by maerckaert** [comment]
Links
FR: https://covid19-acc.healthdata.be/fr/sages-femmes
NL: https://covid19-acc.healthdata.be/nl/vroedvrouwen

**Comment by evelynedewitte** [comment]
@neuronick 

In the FR version, these 2 questions have not been translated!

Please put the French translations on ACC & on PRD

**Comment by neuronick** [comment]
It's on ACC and PROD now

**Comment by evelynedewitte** [comment]
@neuronick 

On PROD it is correct, but not on ACC. Please review ACC.

**Comment by evelynedewitte** [comment]
On ACC & PROD it is now again both in Dutch... for the FR version

**Comment by neuronick** [comment]
Jonathan fixed it. Deployed to ACC / PROD

**Comment by evelynedewitte** [comment]
Validated
