### ISSUE TITLE
PHARMACISTS NL/FR: update 2 questions on status form

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#143]
bbbbbb

**Comment by evelynedewitte** [comment]
Eline Tommelein decided to replace 2 questions about "yesterday" to "today"

Form NL now:
Hoeveel patiënten werden gisteren in de apotheek bediend?
Hoeveel patiënten informeerde de apotheek op gisteren via de telefoon? (schatting)

Form NL to be:
Hoeveel patiënten werden vandaag in de apotheek bediend?
Hoeveel patiënten informeerde de apotheek op vandaag via de telefoon? (schatting)

Form FR now:
Combien de patients ont été aidé en pharmacie hier?
Combien de patients la pharmacie a-t-elle informés par téléphone hier? (estimation)

Form FR to be:
Combien de patients ont été aidé en pharmacie aujourd'hui?
Combien de patients la pharmacie a-t-elle informés par téléphone aujourd'hui? (estimation)

**Comment by maerckaert** [comment]
Links
FR: https://covid19-acc.healthdata.be/fr/pharmacists
NL: https://covid19-acc.healthdata.be/nl/pharmacists

**Comment by evelynedewitte** [comment]
@VrankenKris 
Metadata has been updated in COVID19_fields:

added fields:
nr_num_patients_today
nr_num_patients_phone_today

**Comment by evelynedewitte** [comment]
@neuronick

In the FR version, these 2 questions have not been translated!

Please put the French translations on ACC & on PRD

**Comment by evelynedewitte** [comment]
Done & closed
