### ISSUE TITLE
MIDWIVES NL/FR: change requested to 2 questions: update COVID19_fields

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#144]
More specifically, this concerns the COVID19_fields:

nr_num_clients_standard_yesterday --> nr_num_clients_standard_today
nr_num_clients_phone_yesterday --> nr_num_clients_phone_today

**Comment by evelynedewitte** [comment]
Question NL now:
Hoeveel cliënten begeleidde u of de praktijk gisteren (enkel face-to-face)?
Hoeveel cliënten informeerde u of de praktijk gisteren telefonisch?

Question NL to be:
Hoeveel cliënten begeleidde u of de praktijk vandaag (enkel face-to-face)?
Hoeveel cliënten informeerde u of de praktijk vandaag telefonisch?

Question FR now:
Combien de clients vous ont guidé ou ont pratiqué hier (uniquement en face à face)
Combien de clients vous ou la pratique avez-vous informés hier par téléphone?

Question FR to be:
Combien de clients vous ont guidé ou ont pratiqué aujourd'hui (uniquement en face à face)
Combien de clients vous ou la pratique avez-vous informés aujourd'hui par téléphone?

**Comment by VrankenKris** [comment]
This will become new fields I hope…


Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

**Comment by evelynedewitte** [comment]
Evelyne op te nemen met Jonathan:

- Namen van de **nieuwe** velden doorgeven aan Kris
- Checken dat het wel degelijk nieuwe velden zijn en niet de oude die hernoemd zijn
