### ISSUE TITLE
Home nurses NL + FR: update form: add question on capacity

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#146]
Tim Weltens requests the addition of the following question:

Form NL:
Heb je nog capaciteit (mensen en middelen) om de komende dagen bijkomende patiënten te verzorgen?

Form FR:
Avez-vous toujours la capacité (personnes et ressources) de prendre en charge des patients supplémentaires dans les prochains jours?

**Comment by maerckaert** [comment]
Where to place this question?
What's the possible answers? (ja / neen or ja /neen / andere)
Do we have to add another field for remarks in case of answer no ? (like in the other forms)

**Comment by evelynedewitte** [comment]
@maerckaert Let us look at this tomorrow together. I would suggest to keep this in line with the other questionnaires where the capacity question was asked.

**Comment by evelynedewitte** [comment]
@maerckaert 

As discussed: add the question on capacity for nurses_employed +  nurses_independent for NL/FR

**Comment by neuronick** [comment]
Added to ACC:
https://covid19-acc.healthdata.be/fr/hn_ind/status
https://covid19-acc.healthdata.be/fr/hn_emp/status

**Comment by evelynedewitte** [comment]
Done - closed because we have issue #66 for the survey as a whole
