### ISSUE TITLE
Enable prefilling of fields in status forms based on COOKIES

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#147]
Both client and data providers asked for a means to reduce data entry, especially for "stable information" like email, postcode, ... etc. It was suggested to use cookies. therefore, an excel was made to indicate which fields could be prefilled.
- https://www.dropbox.com/scl/fi/875vipx4gksfmplwrbizo/COVID19_fields_cookies.xlsx?dl=0&rlkey=y0i2qx6ic58pjdnuizaoh3xzf

It is suggested to ask validation by client of these prefills.

If cookies are used to prefill fields, the disclaimer about cookies should be adapted to that end. Do not hesitate to contact Roel Heijlen, our DPO, for this.

**Comment by neuronick** [comment]
It is important to consider a number of issues:

- If a respondent uses multiple devices to fill-in the forms (e.g. laptop and smartphone), then the cookies saved on one device will not be available on another, resulting, for example, in pre-fill being available on a laptop but not on smartphone etc. This could create confusion.

- If the form is filled-in by multiple people using the same computer this could also create confusion as a prefill could be correct for one person but incorrect for another (e.g. email-adres) ...

- Another question concerns erroneous input saved into a cookie (example: respondent makes a mistake in practice name). How are we going to approach this? Do we update cookies on each submit?

**Comment by JohanvanBussel** [comment]
1. If a respondent uses multiple devices to fill-in the forms => **Not a problem. Is a matter of communication.**
2. If the form is filled-in by multiple people using the same computer => **Not a problem. Is a matter of communication. + will not happen often: most forms are completed by 1 person for an organisation.**
3. erroneous input saved into a cookie, Do we update cookies on each submit? : **What are the consequenses of updating the cookies on each submit?**

**Comment by evelynedewitte** [comment]
Remark: Roel betrekken ivm disclaimers (zie mail van Johan) @evelynedewitte

**Comment by evelynedewitte** [comment]
Tested on ACC for GP, CRA en Triage.

This disclaimer is shown regarding the cookies:

- ![2020-04-10.png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/4d37e0d8-6789-437c-89f9-7546b8695f6c)
