### ISSUE TITLE
Home Nurses: update COVID19_Barometer_data_access_20200326.xlsx

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#148]
De resultaten van de enquête voor de sector thuisverpleging zullen verdeeld worden door het secretariaat van het NPTV (Nederlandstalig Platform Thuisverpleging).

**Comment by evelynedewitte** [comment]
Provide Johan with the e-mailadres of the NPTV

**Comment by evelynedewitte** [comment]
@JohanvanBussel @VrankenKris 

De CSV bestanden voor home nurses op de SFTP site mogen toegankelijk zijn voor:

- Secretariaat NPTV: info@nptv.be
- Uschi De Coster <Uschi.De.Coster@vlaanderen.wgk.be>

**Comment by VrankenKris** [comment]
This is done
