### ISSUE TITLE
Create "Landing page for pharmacists"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#15]
Dutch title: "COVID-19 Barometer: apothekers"
text: "Tijdens deze COVID-19 pandemie wenst de faculteit Geneeskunde en Farmacie van de Vrije Universiteit Brussel het netwerk van apothekers te ondersteunen die dagelijks in de klinische realiteit staan. Met een formulier wordt hun situatie en die van anderen in kaart gebracht en kan zo nodig met de feedback hulp aangeboden worden. 

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het informatieveiligheidscomité (referentie: IVC/KSZG/20/xxx).

- Start met de 
- Start met de 

French title: "Baromètre COVID-19: pharmaciens"
text: "to do"

**Comment by neuronick** [comment]
changes implemented

**Comment by JohanvanBussel** [comment]
New version (sorry, but not my fault !!!)
................................
"Tijdens deze COVID-19 pandemie werd een landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coordinerend en raadgevend artsen, triageposten en apothekers) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden. De monitoring van het apothekerskorps gebeurt twee maal per week, op woensdag en zaterdagavond. Enkel de titularis van elke apotheek dient dit formulier in te vullen. 

Voor de apothekers werd deze barometer opgemaakt door de Dienst toegepaste farmacologie & farmacotherapie, farmaceutische zorg (Prof. Eline Tommelein) van de Vrije Universiteit Brussel. 
Deze barometer wordt gesteund door de volgende organisaties: ****, **** en ****.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Groep, en Nationale Crisiscel.
Op basis van de gegevens die u registreert, ontvangt u gepersonaliseerde feedback verzorgd door Doclr.
Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Uw e-mailadres wordt enkel gebruikt om de samenvatting van de resultaten naar u op te sturen en om de follow-up monitoring aan te kondigen. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig, kan steeds kan onderbroken worden, en alle gegevens zullen anoniem verwerkt worden.

Voor inhoudelijke vragen bij deze gegevensverzameling: emailadres
Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

Start met de barometer registratie.
..............................

franse versie volgt

**Comment by neuronick** [comment]
text updated
