### ISSUE TITLE
Change request: update option labels for cd_surgical_masks, cd_infection_masks, cd_infection_aprons

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#150]
Request to change the option labels for the fields:

**cd_surgical_masks** 

1: Groot tekort|Grande pénurie (max 2 maskers / masques)
2: Klein tekort|Petite pénurie (3 - 7 maskers / masques)
3: Klein overschot|Petit surplus (8 - 14 maskers / masques)
 4: Groot overshot|Grand surplus (> 14 maskers / masques)

**cd_infection_masks**

1: Groot tekort|Grande pénurie (max 2 maskers / masques)
2: Klein tekort|Petite pénurie (3 - 7 maskers / masques)
3: Klein overschot|Petit surplus (8 - 14 maskers / masques)
 4: Groot overshot|Grand surplus (> 14 maskers / masques)

**cd_infection_aprons**

1: Groot tekort|Grande pénurie (max 2 schorten / tabliers)
2: Klein tekort|Petite pénurie (3 - 7 schorten / tabliers)
3: Klein overschot|Petit surplus (8 - 14 schorten / tabliers)
 4: Groot overshot|Grand surplus (> 14 schorten / tabliers)

And this for all forms where these labels appear (all except for pharmacies):

- [x] GP
- [x] CRA
- [x] TRIAGE
- [x] MIDWIVES
- [x] HOME NURSES EMP
- [x] HOME NURSES IND

I have already updated the file covid19_fields on Dropbox for this.

**Comment by JohanvanBussel** [comment]
Moet daar niet steeds “per arts”, “per vroedvrouw”, per “thuisverpleegkundige”, … bij staan?

**Comment by neuronick** [comment]
per ... added to (NL / FR):
- [x] GP
- [ ] CRA
- [ ] TRIAGE
- [x] MIDWIVES
- [x] HOME NURSES EMP
- [x] HOME NURSES IND

**Comment by neuronick** [comment]
The changes are available on ACC
