### ISSUE TITLE
Create COVID-specific frontpage search block

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#154]
Create custom block for the search (like the one for the existing frontpage header), make sure it uses correct search settings / index

**Comment by neuronick** [comment]
@maerckaert 
Block is created, basic styling is provided.
Currently deployed on ACC only.
Should be added to the new frontpage Covid19 header via Panels

**Comment by JohanvanBussel** [comment]
Not visible in my ACC-screen ...

![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/141efccd-7a1f-4656-a6b1-8e9e50f95bdd)

**Comment by neuronick** [comment]
@JohanvanBussel 
Jonathan is working on the header. He still need to add the block, once the COVID header is added.
