### ISSUE TITLE
Pharmacists: correct frequency of registration on landing page NL + FR

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#156]

**Comment by evelynedewitte** [comment]
FR:

as-is:
Le suivi par le corps des pharmacies se fait deux fois par semaine, **le mercredi et le samedi soir**.

to-be:
Le suivi par le corps des pharmacies se fait deux fois par semaine, **le lundi et le mercredi soir**.

**Comment by evelynedewitte** [comment]
NL:

as-is:
De monitoring van het apothekerskorps gebeurt twee maal per week, op **woensdag en zaterdagavond**.

to-be:
De monitoring van het apothekerskorps gebeurt twee maal per week, op **maandag- en woensdagavond, tussen 15u en 22u**.

**Comment by neuronick** [comment]
Update on ACC / PROD
