### ISSUE TITLE
Midwives: correct frequency of registration on landing page NL + FR

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#157]

**Comment by evelynedewitte** [comment]
NL:

as-is:
De monitoring van het apothekerskorps gebeurt twee maal per week, op woensdag en zaterdagavond.

to-be:
De monitoring van het apothekerskorps gebeurt twee maal per week, op maandag- en woensdagavond.

**Comment by evelynedewitte** [comment]
FR:

as-is:
Le corps des sages-femmes est surveillé deux fois par semaine, le mercredi et le samedi soir

to-be:

Le corps des sages-femmes est surveillé deux fois par semaine, le lundi et le mercredi soir.

**Comment by neuronick** [comment]
Updated on ACC / PROD
