### ISSUE TITLE
Create "COVID-19 Barometer Data Dictionary"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#16]
Excell available on dropbox: https://www.dropbox.com/scl/fi/nbxwebdreuhtj838e0ns5/COVID19_Barometer_dd_01.xlsx?dl=0&rlkey=ydggu51jwcpwaiwuaij3xbfb2

**Comment by neuronick** [comment]
@JohanvanBussel : as the structure of the forms changes (registration forms integrated into daily status forms), I do not think the above file is up to date.

On Kris request I have created a separate file with technical field_names, labels (NL / FR) and options (values + labels) here:
https://www.dropbox.com/scl/fi/1htdxm64uv963t82eajjs/COVID19_fields.xlsx

**Comment by neuronick** [comment]
Is this sufficient information from our part?

**Comment by VrankenKris** [comment]
This is done and used on a daily basis
