### ISSUE TITLE
Create landing page "Eerste lijn zorgverleners: algemeen" / "Prestataires de soins de première ligne: général"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#162]
Er moet nog een formulier  komen voor de zorgverstrekkers 1ste lijn die niet tot de beroepsgroepen horen die al een formulier hebben. reden= dat barometer als the one and only wordt beschouwd voor de 1ste lijn. Punt is dat met de formulieren die we nu hebben wel een groot deel coveren, maar niet alle actoren. Als die dan op de barometer komen, dan kan dat voor frustratie zorgen.

**Comment by evelynedewitte** [comment]
@JohanvanBussel Welke tekst plaatsen we op de landingspagina voor de "algemene" doelgroep? Hieronder al even een voorzet gebaseerd op de thuisverpleegkundigen.

**Landing page NL**

Beste zorgverlener,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (o.a. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen, thuisverpleegkundigen en gezinszorg) van nabij te volgen en zo knelpunten in de eerste lijn vroeger te detecteren en sneller gericht oplossingen te kunnen aanbieden.

Deze monitoring werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134). Concreet worden de gegevens gebruikt ter ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en de Nationale Crisiscel in de sturing van het beleid.

Voor de "eerste lijn zorgverleners: algemeen" werd deze barometer opgemaakt door XXX. De monitoring kan dagelijks gebeuren tussen 15u en 22u.         **--> willen we hier geen frequentie voorstellen?**

Pas op: per dienst hoeft er slechts één vragenlijst ingevuld te worden. **--> behouden?**

Uw e-mailadres wordt gebruikt om de follow-up monitoring aan te kondigen. Alle gegevens zullen in verder wetenschappelijk onderzoek anoniem verwerkt worden. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst, die geheel vrijwillig is en op elk moment kan worden onderbroken.

Voor inhoudelijke vragen bij deze gegevensverzameling: XXX

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

Alvast hartelijk bedankt voor uw medewerking.

**Comment by evelynedewitte** [comment]
@JohanvanBussel 
Welke tekst plaatsen we op de landingspagina voor de "algemene" doelgroep? Hieronder al even een voorzet gebaseerd op de thuisverpleegkundigen.

**Landing page FR**

Cher fournisseurs de soins,

Durant de cette pandémie de COVID-19, le projet national de surveillance" Baromètre COVID-19" a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et consultatifs, les postes de triage, les pharmaciens, les sages-femmes, et les infirmières à domicile) et, si nécessaire, apporter une aide via feed-back.

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).

Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’.

Votre adresse e-mail ne sera utilisée que pour annoncer le suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire et peut être interrompu à tout moment. Vos données sont actuellement utilisées pour guider la politique et toutes les données seront traitées de manière anonyme dans les recherches scientifiques futures.

Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be

Merci pour votre coopération.

**Comment by JohanvanBussel** [comment]
Tekst is voor mij OK.
Wel moet VIVEL toegevoegd worden als zijnde bereikbaar voor inhoudelijke vragen. Anders komen die bij ons terecht. Misschien is het goed om de woorden “inhoudelijk” en “technisch” in vet én onderlijnd te zetten.

**Comment by evelynedewitte** [comment]
**Landing page NL**

Beste zorgverlener,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (o.a. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen, thuisverpleegkundigen en gezinszorg) van nabij te volgen en zo knelpunten in de eerste lijn vroeger te detecteren en sneller gericht oplossingen te kunnen aanbieden.

Deze monitoring werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134). Concreet worden de gegevens gebruikt ter ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en de Nationale Crisiscel in de sturing van het beleid.

Voor de "eerste lijn zorgverleners: algemeen" werd deze barometer opgemaakt in samenwerking met Vivel.

Pas op: per dienst hoeft er slechts één vragenlijst ingevuld te worden.

Uw e-mailadres wordt gebruikt om de follow-up monitoring aan te kondigen. Alle gegevens zullen in verder wetenschappelijk onderzoek anoniem verwerkt worden. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst, die geheel vrijwillig is en op elk moment kan worden onderbroken.

Voor inhoudelijke vragen bij deze gegevensverzameling: XXX

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

Alvast hartelijk bedankt voor uw medewerking.

**Comment by evelynedewitte** [comment]
Cher fournisseur de soins,

Durant de cette pandémie de COVID-19, le projet national de surveillance" Baromètre COVID-19" a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et consultatifs, les postes de triage, les pharmaciens, les sages-femmes, et les infirmières à domicile) et, si nécessaire, apporter une aide via feed-back.

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).
Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’.

Votre adresse e-mail ne sera utilisée que pour annoncer le suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire et peut être interrompu à tout moment. Vos données sont actuellement utilisées pour guider la politique et toutes les données seront traitées de manière anonyme dans les recherches scientifiques futures.

Remarque: une seule inscription doit être effectuée par service ou cabinet.

Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be

Merci bien pour votre coopération.
