### ISSUE TITLE
create form NL + FR: "Eerste lijn zorgverleners: algemeen" / "Prestataires de soins de première ligne: général"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#163]
Inhoud = die van GP, zonder de vragen van Vioras, dus iets als:

- Type zorgactor (dropdown lijst die ik ga opvragen)
- tx_gp_name      Naam van de praktijk
- tx_email             E-mailadres
- tx_gp_postal_code         Postcode van de gemeente waarin de praktijk zich bevindt
- nr_num_??_providers   Aantal zorgverstrekkers werkzaam in de praktijk
- nr_num_??_providers_absent   Aantal zorgverstrekkers die ziek zijn en niet kunnen werken
- nr_num_consultations_phone   Hoeveel telefonische consultaties hebt u vandaag gedaan?
- nr_num_consultations_phys      Hoeveel fysieke consultaties hebt u vandaag gedaan?
- nr_num_patients_triage             Hoeveel patiënten hebt u vandaag doorverwezen naar de covid19 triage post?
- nr_num_patients_emergency    Hoeveel potentiële covid19 patiënten hebt u vandaag doorverwezen naar spoed?
- cd_num_respiratory_consultations         Hoeveel % van uw consultaties hebben betrekking op luchtweg klachten?
- cd_extra_load   "Hoe groot is de extra belasting voor u als zorgverstrekker op dit moment?     "
- cd_alc_hand_disinfectant           Alcoholische handontsmetting
- + number units needed
- cd_surgical_masks         Gewone chirurgische maskers
- + number units needed
- cd_infection_masks       Maskers geschikt te gebruiken bij infecties (FFP2 en co)
- + number units needed
- cd_infection_gloves       Handschoenen geschikt te gebruiken bij infecties
- + number units needed
- cd_infection_aprons      Schorten geschikt te gebruiken bij infecties
- + number units needed
- cd_infection_screen       Bril/scherm geschikt te gebruiken bij infecties
- + number units needed

**Comment by evelynedewitte** [comment]
Type zorgactor: drop-down list with the following fields:

Tandarts / Dentiste
Orthodontist / Orthodontiste
Parodontoloog / Parontologue
Kinesist / Kinésithérapeute
Diëtist / Diététicien
Ergotherapeut / Ergothérapeute
Logopedist / Logopède
Audiologen en audiciens / Audiologue et Audicien
Arts-specialist / Médecins spécialistes
Andre /Autre

**Comment by evelynedewitte** [comment]
Start: 

Dit formulier bevat vragen die uw situatie als eerste lijn zorgverlener in kaart moet brengen. Met deze vragen hebben we als doel uw situatie en die van anderen in kaart te brengen en zo nodig met de feedback jullie hulp te kunnen aanbieden. De bedoeling is om deze vragen eerlijk in te vullen zodat de realiteit voldoende gereflecteerd wordt!
Gelieve feedback te geven wanneer je hulp nodig hebt of 'Niet akkoord' aanduidt.


Ce formulaire contient des questions pour cartographier votre situation en tant que prestataire de soin de première ligne. Notre objectif est de cartographier votre situation et celle des autres et, si nécessaire, de vous offrir de l'aide via le feed-back. L'intention est de répondre honnêtement à ces questions afin que la réalité soit suffisamment reflétée!
Veuillez fournir des commentaires lorsque vous avez besoin d'aide ou indiquer «Pas d'accord».
