### ISSUE TITLE
COVID-19 CSV files: bug in daily updating of the files

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#165]
It seems the Open Data is not refreshed on a daily basis.

As this is currently a manual load, it is prone to errors or forgetfullness. Can we check whether the files have been refreshed yesterday evening?

For instance: this dataset does not contain data later than 29/03 (checked just now):

covid19_triage_cd_infection_gloves.csv

**Comment by evelynedewitte** [comment]
The names of the files on Dropbox were recently changed:

From hd_covid_xxx to covid19_xxx

Maybe it was not updated on your end?

**Comment by neuronick** [comment]
All the resource have been updated on PROD. I will sync this with ACC tonight.

**Comment by evelynedewitte** [comment]
@neuronick 

I downloaded at random CSV files and noticed that the files for the new questions are empty, which is logical. Please remove these from all pages until we have data for them.

nr_num_surgical_masks
nr_num_alc_hand_disinfectant
nr_num_infection_masks
nr_num_infection_gloves
nr_num_infection_aprons
nr_num_infection_screen

**Comment by neuronick** [comment]
Instead of deleting these resources are temporarily unpublished (so they are visible for administrator but not for the site visitors).
