### ISSUE TITLE
Family care services FR: create survey

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#166]
@neuronick 

Nikita, @JohanvanBussel  is taking care of the French translations for the Family Care survey.

Until we receive those. You cannot do anything of course, but I want to make sure it is not forgotten.

**Comment by neuronick** [comment]
Draft version is here:
https://covid19-acc.healthdata.be/fr/fcs/status

**Comment by evelynedewitte** [comment]
Added the FR translations

**Comment by neuronick** [comment]
Updated FR translation

**Comment by evelynedewitte** [comment]
Feedback after the first validation:

**Start page**

- [ ] Below "province", update the Dutch phrase with: "les principaux services doivent répondre au sondage par province"
- [ ] Nombre de collaborateurs d'Aide familiale activement au travail dans le service au moment de l'enquête?? --> one ? seems enough :-)

All the rest = fine!

**Comment by neuronick** [comment]
done
