### ISSUE TITLE
Family Care services FR: create landing page

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#167]

**Comment by evelynedewitte** [comment]
Chère infirmière, cher infirmier,

Durant de cette pandémie de COVID-19, le projet national de surveillance" Baromètre COVID-19" a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et consultatifs, les postes de triage, les pharmaciens, les sages-femmes, et les infirmières à domicile) et, si nécessaire, apporter une aide via feed-back. Le suivi du corps des infirmières à domicile a lieu deux fois par semaine, le lundi et le mercredi, entre 15h et 22h.

Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’.

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).

Votre adresse e-mail ne sera utilisée que pour annoncer le suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire et peut être interrompu à tout moment. Vos données sont actuellement utilisées pour guider la politique et toutes les données seront traitées de manière anonyme dans les recherches scientifiques futures.

Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be

**Comment by neuronick** [comment]
Landing page created on ACC:
https://covid19-acc.healthdata.be/fr/fcs

**Comment by evelynedewitte** [comment]
Update the beginning with:
- Chère aide-soignante, cher aide-soignant

**Comment by evelynedewitte** [comment]
@neuronick 

Update the title to:  Baromètre COVID-19: soins familiaux.

**Comment by evelynedewitte** [comment]
Some small errors in the text, you can just copy-paste this one:

Chère aide-soignante, cher aide-soignant,

Durant de cette pandémie de COVID-19, le projet national de surveillance" Baromètre COVID-19" a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et consultatifs, les postes de triage, les pharmaciens, les sages-femmes, et les infirmières à domicile) et, si nécessaire, apporter une aide via feed-back.

Le suivi du corps des aide-soignants à domicile a lieu deux fois par semaine, le lundi et le mercredi, entre 15h et 22h.

Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’.

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).

Votre adresse e-mail ne sera utilisée que pour annoncer le suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire et peut être interrompu à tout moment. Vos données sont actuellement utilisées pour guider la politique et toutes les données seront traitées de manière anonyme dans les recherches scientifiques futures.

Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be

**Comment by neuronick** [comment]
Updated.

**Comment by evelynedewitte** [comment]
I made a small error in the phrase:
Le suivi du corps des aide-soignants **à domicile** a lieu deux fois par semaine, le lundi et le mercredi, entre 15h et 22h.

We have to remove the "à dimicile".

**Comment by neuronick** [comment]
Fixed in ACC / PROD

**Comment by evelynedewitte** [comment]
Verified.
