### ISSUE TITLE
Implement COOKIE POLICY on website covid19.healthdata.be

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#17]
cfr regulations and advise of DPO sciensano.

**Comment by maerckaert** [comment]
I need text for the cookies consent.
Do we have a cookie policy page?
![Cookies](https://user-images.githubusercontent.com/59559118/77229503-b128f180-6b8e-11ea-93b0-592faddb44ac.JPG)

**Comment by JohanvanBussel** [comment]
Text as used by sciensano ?:
NL: https://www.sciensano.be/nl/aansprakelijkheid-en-vertrouwelijkheid
FR: https://www.sciensano.be/en/responsibility-and-privacy
ENG: https://www.sciensano.be/fr/responsabilite-et-vie-privee

**Comment by neuronick** [comment]
- As discussed with Roel, we need to put the cookie consent banner at the top.

- Also the banner does not neet to be displayed for these roles (as these users are internal or create by us explicitly):
  - Data entry
  - Content manager
  - Head of service

- These options should ideally also be checked on:
  - Exclude admin pages
  - Don't show the banner for UID 1
  - Let screen readers see the banner before other links on the page.

**Comment by maerckaert** [comment]
I've just modified.
