### ISSUE TITLE
Link resources with open datasets a) Self-employed home nurse and b) Home nursing services

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#172]
The open data based on the data submitted on 06.04.2020 for the barometers "Self-employed home nurse" and " Home nursing services" should be linked to the following datasets:

COVID-19 Barometer: Self-employed home nurse => https://fair.healthdata.be/dataset/316ccf57-9575-4b05-8116-c77b839a50c1

COVID-19 Barometer: Home nursing services => https://fair.healthdata.be/dataset/8e4f9f20-2726-4659-988e-83000b8072cb

**Comment by evelynedewitte** [comment]
@neuronick @maerckaert 
OK to assign this one to @maerckaert ?
