### ISSUE TITLE
Barometer GP: toevoegen Huisartsenkring - NL

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#179]
Huisartsenkring per gemeente (2019) toevoegen aan NL formulier voor GP.

- [x] Add covid19_field in Excel file

- [x] Add question: "**Lid van huisartsenkring**" to form below "**Postcode** van de gemeente waarin de praktijk zich bevindt"

- [x] Add drop-down list to form based on the Excel file on Dropbox. The column to use is "Naam":
https://www.dropbox.com/s/wnd53ifqaljlyct/Huisartsenrking%20per%20gemeente%20%282019%29.xlsx?dl=0. Filter the values on **postcode**.

- [x] Add "Andere"/"Autre" to the drop-down list + the possibility to fill in the name in a text field when chosen "Andere"/"Autre" (= a code field + a text field)

**Comment by evelynedewitte** [comment]
@VrankenKris 

As discussed during on of our calls with Nikita & Jonathan, you wanted to have a look first at the Excel files because of the doubles.

See comment with the link or Dropbox folder HD_9999_COVID19/List_of_values_COVID19_Barometer

**Comment by VrankenKris** [comment]
@evelynedewitte I think I sent the document

**Comment by evelynedewitte** [comment]
@maerckaert 

Kris created the codes for the NL and FR circles for GP:

https://www.dropbox.com/s/xl7qoemk7hyh9bg/GP_NL_FR_circles.xlsx?dl=0

**Comment by evelynedewitte** [comment]
@maerckaert 
In the NL version for GP, the code C999 appears twice in the list ("C999 - Andere" en "C999 - Autre").

**Comment by evelynedewitte** [comment]
@maerckaert ![2020-04-13.png]

(https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/3d0ece43-ce27-4560-a1e4-594b025d0a70)![2020-04-13.png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/52f0c230-ac40-4176-b7f1-4a366ed5a374)

Bug detected: even if I pick a Circle for Huisartsenkring (not equal to "Andere/Autre"), the text field for "Andere/Autre" appears and I am obligated to fill in something.

**Comment by neuronick** [comment]
There were changes for this:
- Field tx_prof_circle is removed.
- Field cd_prof_circle now also contains option 'Andere / Autre', which will allow to enter free text. The value will be either code or free text. (discussed this with Kris - ok for him).
- Hereby the bug mentioned above is resolved.

**Comment by VrankenKris** [comment]
@neuronick You did this also in production, I think
