### ISSUE TITLE
Barometer GP: add the circle of GP - FR

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#180]
Huisartsenkring toevoegen aan FR formulier voor GP.

 - [x] Add covid19_field in Excel file

 - [x] Add question: "Membre du Cercle de Médecins Généralistes" to form below "Code Postal du cabinet"

 - [x] Add drop-down list to form based on the Excel file on Dropbox: https://www.dropbox.com/s/hdiwbcwv3vwrar9/2019-31-12%20Cercles%20MG%20Communes.xlsx?dl=0

       Use Excel-variabele “Cercle”

- [ ] Add "Andere"/"Autre" to the drop-down list + the possibility to fill in the name in a text field when chosen "Andere"/"Autre" (= a code field + a text field)

**Comment by evelynedewitte** [comment]
@maerckaert 

Kris created the codes for the NL and FR circles for GP:

https://www.dropbox.com/s/xl7qoemk7hyh9bg/GP_NL_FR_circles.xlsx?dl=0

**Comment by evelynedewitte** [comment]
@maerckaert 
In both the NL and FR version for GP, the code C999 appears twice in the list ("C999 - Andere" en "C999 - Autre"). We can make it just one code ("C999 - Andere/Autre).

**Comment by evelynedewitte** [comment]
Bug detected!

@maerckaert 

![2020-04-13.png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/dcddbaeb-d170-4c06-a1e7-52eb10f283de)

The text field that should only be shown when "Andere"/"Autre" is chosen for Circle, is always a required field even when one picks a specific Circle.

**Comment by neuronick** [comment]
see #179
