### ISSUE TITLE
NL + FR: Add text around capacity to each landing page

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#184]
Text (see comments below) to add to:

- [x] GP
- [x] CRA
- [x] Triage
- [x] Pharmacies
- [x] Midwives
- [x] Home Nurses
- [x] Family Care
- [x] Algemeen

**Comment by evelynedewitte** [comment]
**To add as a new paragraph after this phrase:**
“Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Groep, en Nationale Crisiscel.”

**Text NL:**

“Er werd afgesproken op interfederaal niveau dat de COVID19 barometer eerste lijn, het kanaal is via dewelke de eerstelijnsactoren hun noden moeten doorgeven. Daartoe worden vanaf  6 april de materiaalitems gekwantificeerd bevraagd in deze barometer.
Op die manier worden de noden voor de eerste lijn kwantitatief in kaart gebracht en doorgegeven naar de verschillende bevoegde instanties.
 
Wij willen er evenwel op wijzen dat het doorgeven van de noden aan beschermend materiaal, geenszins inhoudt dat de overheid voor leveringen zal instaan. Voor de overheid is dit het medium om vinger aan de pols te houden van de noden op het terrein, zodat zij de industrie correct kan informeren en zo nodig kan aanzetten tot verhoogde productie of invoer naar België.”

**Comment by maerckaert** [comment]
Added in acc and prod.

**Comment by evelynedewitte** [comment]
Validated in PROD for NL version. Waiting for the FR translation.

**Comment by evelynedewitte** [comment]
**Text FR:**

“Il a été convenu au niveau interfédéral que le baromètre COVID19 de première ligne soit le canal via lequel les acteurs de première ligne doivent transmettre leurs besoins. A cet effet, ce baromètre interroge, à dater du 6 avril, au sujet des points concernant le matériel en termes de quantification. Cela permet de répertorier d’une manière quantitative les besoins de la première ligne et de les transmettre aux différentes instances compétentes.

Nous voudrions toutefois faire remarquer que la communication des besoins en matériel de protection n’implique en aucun cas que le gouvernement se chargera des livraisons. Pour le gouvernement, c’est le moyen d’être informé des besoins sur le terrain, afin de pouvoir informer correctement l’industrie et si nécessaire, de pouvoir inciter à augmenter la production ou l’importation vers la Belgique. ”

**Comment by evelynedewitte** [comment]
@maerckaert 

Feedback on production:

- [ ] For midwives, the NL text has been copied 2 times. Please remove 1 copy.

The rest is fine!
