### ISSUE TITLE
Cohortzorg: add explication on "start" page of relevant barometer

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#185]
Text (see comments below) to add to:

- [x] Home Nurses (emp + ind)
- [x] Family Care

**Comment by evelynedewitte** [comment]
Add explanation below on the page where we ask questions concerning "cohortzorg" / "soins cohorte".
(Eerste pagina – Start)

NL
Cohortzorg houdt in dat een vaste equipe verzorgenden en een vaste equipe verpleegkundigen exclusief instaan voor de zorg en ondersteuning bij personen die besmet zijn met COVID-19 of door de (huis)arts als potentieel besmet beschouwd worden. Andere verzorgenden/verpleegkundigen die géén deel uitmaken van de equipes voor (mogelijke) COVID-19 cliënten nemen de zorg op voor cliënten die niet besmet zijn.

FR
Les soins de cohorte signifient qu'une équipe permanente de professionnels et une équipe permanente d'infirmières sont exclusivement responsables des soins et du soutien des personnes infectées par COVID-19 ou considérées comme potentiellement infectées (par le médecin généraliste). D'autres professionnels / infirmières qui ne font pas partie des équipes pour les patients (possibles) de COVID-19 s'occupent des patients qui ne sont pas infectés.

**Comment by maerckaert** [comment]
@evelynedewitte I'm not sure where i've to put this paragraph. I don't see "soins cohorte" on every form. Could you provide me more info?

**Comment by evelynedewitte** [comment]
After the word "cohortzorg" in the 2 questions: put an (*).

Repeat (*) with the footnote.
