### ISSUE TITLE
URGENCY / protection of data on barometer drupal

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#188]
Could you please offload all data from the barometer drupal ?
People with a lot of time are checking whether they can access the data !!!
The limesurvey data of the resarchers are hacked , so I want to prevent this happening to our projects !!!

**Comment by neuronick** [comment]
All successfully sent submissions have been purged from covid19.healthdata.be

**Comment by JohanvanBussel** [comment]
On a daily basis ?
