### ISSUE TITLE
Activation / DeActivation of barometer forms (temporary until eID / ItsMe)

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#189]
Forms to DEACTIVATE on Friday 10/04 ASAP and to ACTIVE again on Monday 13/04 at 15h:
- [x]    Midwives
- [x]    Pharmacies
- [x]    Home Nurses EMP
- [x]    Home Nurses IND
- [x]    Family Care
- [x]    Other

When one clicks on "start the registration“, the following message is shown: "U heeft geen toegang tot dit formulier” / "Vous n'avez pas accès au formulaire"
 
Forms to DEACTIVATE on Friday 10/04 at 22h and to ACTIVE again on Monday 13/04 at 15h:
- [x]    GP
- [x]    CRA
- [x]    Triage
 
Form to ACTIVATE on Saturday 11/04 + Sunday 12/04 between 15h and 22h:
- [ ]    Triage

See also Outlook reminders on all days this Easter weekend

**Comment by maerckaert** [comment]
Barometer for Triage is activated.

**Comment by maerckaert** [comment]
Barometer for Triage is deactivated.

**Comment by evelynedewitte** [comment]
Thanks @maerckaert

**Comment by evelynedewitte** [comment]
@neuronick @maerckaert 

Who of you can perform this change asap:

Replace « U heeft geen toegang tot dit formulier” for ALL BAROMETERS by:
 
NL: “Om veiligheidsredenen is het formulier enkel toegankelijk tijdens de registratieperiode van elke beroepsgroep. Dit registratievenster staat beschreven op de informatiepagina van uw COVID-19 Barometer. Dank voor uw begrip.”.
 
FR: «Pour des raisons de sécurité, le formulaire n'est accessible que pendant la période d'enregistrement de chaque profession. Cette fenêtre d'enregistrement est décrite sur la page d'informations de votre baromètre COVID-19.  Merci pour votre compréhension.».

**Comment by neuronick** [comment]
@evelynedewitte The text for all forms is changed + FR translation added.

**Comment by evelynedewitte** [comment]
@neuronick Text validated on production for as well NL as FR

**Comment by neuronick** [comment]
Triage is deactivated

**Comment by maerckaert** [comment]
All forms are activated.

**Comment by maerckaert** [comment]
All forms are deactivated.

**Comment by JohanvanBussel** [comment]
AS OF 14.04.2020, from 15h00 on, ALL FORMS should be available , via eID/ITSME ,  **24/7**.
