### ISSUE TITLE
Cookie policy page for Covid-19 barometer page http://covid19.healthdata.be/

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#192]
Roel, DPO of Sciensano, delivered a draft text to use for the cookie policy page of the covid-19 barometer page.

The text is found on Dropbox: https://www.dropbox.com/s/erfr7yr70edaoar/Cookie%20Policy%20COVID19%20Barometer.docx?dl=0

**Comment by evelynedewitte** [comment]
@JohanvanBussel 

Roel delivered a draft text to use for the cookie policy page of the covid-19 barometer page. We only have the text in Dutch. Can I ask our translation service to translate to French?

**Comment by JohanvanBussel** [comment]
@evelynedewitte OK for translation by Sciensano translation service.

**Comment by evelynedewitte** [comment]
@neuronick 
I unassigned you and assigned it to me as I'm going to provide you with the translation to French.

**Comment by evelynedewitte** [comment]
Translation request sent on 16/04.

**Comment by evelynedewitte** [comment]
@neuronick 
While waiting for the FR translations, we can already prepare the Dutch version on ACC.

**Comment by evelynedewitte** [comment]
FR translation received:

https://www.dropbox.com/s/hl9zxdxo1st08io/Cookie%20Policy%20COVID19%20Barometer%20%281%29%20FR.docx?dl=0

**Comment by evelynedewitte** [comment]
To do:

- Look at the drupal modules for cookies (Nikita already started investigating them)
- Decide on the approach to take

**Comment by evelynedewitte** [comment]
Tasks:

- Create the cookie policy page with the text from Roel
- Show what kind of cookies we use currently
- People should be able to manage the cookies they accept (opt-in, opt-out)

**Comment by neuronick** [comment]
Here are some potentials candidates if EU Cookies Consent isn't working properly for our needs:
- https://www.drupal.org/project/gdpr_compliance
- https://www.drupal.org/project/gdpr
- https://www.drupal.org/project/cookieconsent
- https://www.drupal.org/project/cookie_content_blocker
- https://www.drupal.org/project/tacjs

**Comment by evelynedewitte** [comment]
@roelheijlen 
Roel, can you provide us the final texts to appear on these pages?

**Comment by roelheijlen** [comment]
@evelynedewitte 
New text available on Dropbox (Dutch & French): https://www.dropbox.com/scl/fi/pzcgvtg48obgshq29exml/20200430-Cookie-Policy-COVID19-Barometer.docx?cloud_editor=word&dl=0&rlkey=wnqyv5vlxhcr3x9oidaybb35j 

TO DO's for @maerckaert 

- [ ] check if all cookies used are mentioned 

- [ ] complete or correct the duration if each cookie

- [ ] check if the info on type of cookies (e.g. https, pixel, ...) is correct

**Comment by maerckaert** [comment]
https://www.dropbox.com/scl/fi/pzcgvtg48obgshq29exml/20200430-Cookie-Policy-COVID19-Barometer.docx?cloud_editor=word&dl=0

**Comment by helene-ameels** [comment]
@maerckaert @neuronick - French cookies tested in Internet Exporere - email sent on 05/05/2020

**Comment by evelynedewitte** [comment]
Feedback:

- [ ] Rephrase "Door op de link “OK, ik ga akkoord” te klikken, geeft u ons toestemming om cookies in te stellen" as follows: 
NL: "Gelieve hieronder de cookies die u aanvaardt, te selecteren en op "accepteer cookies" te klikken."
FR: (Hélène)

- [ ] Only retain 1 button "Accepteer cookies (NL)". Remove "Accept all cookies" (FR + NL)

- [ ] Replace "Nee, geef me meer info" by "Meer informatie" (in FR it is OK)

**Comment by helene-ameels** [comment]
@evelynedewitte - tested for FR and NL and everyhting asked implemented - Next steps?
- [ ] confirmed by Roel?
- [ ] UAT by client?

**Comment by roelheijlen** [comment]
@maerckaert - Please correct the three typo's in the Dutch version of the cookie policy? See track changes: https://www.dropbox.com/scl/fi/n9u075i9pfcxhgt96fzxh/Typos-cookie-policy_NL.docx?cloud_editor=word&dl=0&rlkey=2xxgsj2ood1oy3jvxf82x96i5

No other comments

@evelynedewitte -  In contract to the ACC website the cookie banner on https://covid19.healthdata.be/ has not implement your feedback from 05.05.2020. As the content of this banner is not correct, suggestion to change it soon.

**Comment by maerckaert** [comment]
@helene-ameels : the corrections has been implemented. Ready to go in prod.

**Comment by evelynedewitte** [comment]
@maerckaert @helene-ameels 

Small error in the Dutch text:

"Op basis van analytische cookies kunnen wij anonieme statistieke**n** (...)""

Roel should do the UAT --> if he validates the pages/texts, then we go to PROD

**Comment by roelheijlen** [comment]
@maerckaert : Validation ok, ready for production

**Comment by helene-ameels** [comment]
@maerckaert 
French version: OK
Ndls version: not yet OK
- in the 'bandeau' - typo is still present: "Op basis van analytische cookies kunnen wij anonieme statistieke**n** (...)""
- when we click on more info, a new window appear with the word document text BUT the 'bandeau' is still hiding the text  - see prtin screen attached
![Capture](https://user-images.githubusercontent.com/43435785/81261953-43049500-903d-11ea-819d-47e5b28039b8.PNG)

**Comment by maerckaert** [comment]
@helene-ameels It was only a cache problem. Now it appears correctly.

**Comment by helene-ameels** [comment]
@maerckaert : it is indeed ok

**Comment by helene-ameels** [comment]
@neuronick - ready to deploy in PROD

**Comment by helene-ameels** [comment]
ok in prod

**Comment by neuronick** [comment]
- [ ] Update the texts (NL / FR)  with the changes agreed with Roel
- [ ] Provide cookie policy link in the header or footer.

**Comment by neuronick** [comment]
Texts changed / link added to the header (NL / FR)

**Comment by helene-ameels** [comment]
Modification implemented correctly
@Roel to check the whole policy

**Comment by roelheijlen** [comment]
Checked. Ticket can be closed.
