### ISSUE TITLE
Adjust note on privacy on landing pages:

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#193]
Adjust the information concerning "anononieme verwerking" on the landing pages.
 
- [x] **For GP, CRA, Triage and midwives:**
as-is:
Deze vragenlijst is volledig vrijwillig, kan steeds kan onderbroken worden, en alle gegevens zullen anoniem verwerkt worden.
 
to-be:
Alle gegevens zullen in verder wetenschappelijk onderzoek anoniem verwerkt worden. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst, die geheel vrijwillig is en op elk moment kan worden onderbroken.
 
- [x] **Also adjust the following phrases for Home Nurses and ALGEMEEN:**

AS IS
Concreet worden de gegevens gebruikt ter ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en de Nationale Crisiscel in de sturing van het beleid.

TO BE
Concreet worden de gegevens gebruikt ter ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, Nationale Crisiscel en regionale gezondheidsagentschappen in de sturing van het beleid.

- [x] **Also adjust the following phrases for GP, CRA, Triage, Pharmacies, Midwives and Family Care:**

AS IS
Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Groep, en Nationale Crisiscel.

TO BE
Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Groep, Nationale Crisiscel en regionale gezondheidsagentschappen.

**Comment by maerckaert** [comment]
Modified in acc and prod.

**Comment by evelynedewitte** [comment]
Verified & validated in PROD
