### ISSUE TITLE
All COVID-19 Barometers: add FAQ section about eID and Itsme

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#194]
Reuse the FAQ of HD4Patient for each COVID-19 Barometer:
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/e1bdcc3a-d534-4bd4-a15b-54875e079e01)

- [x] COVID-19 Barometer: General Practitioners
- [x] COVID-19 Barometer: Midwives
- [x] COVID-19 Barometer: Pharmacists
- [x] COVID-19 Barometer: Triage Posts
- [x] COVID-19 Barometer: Coordinating and Advising Physicians
- [x] COVID-19 Barometer: Self-employed home nurse
- [x] COVID-19 Barometer: Home nursing services
- [x] COVID-19 Barometer: Family care services
- [x] COVID-19 Barometer: 1st line healthcare providers: general

**Comment by maerckaert** [comment]
Done in English I put in Dutch and French now.

**Comment by JohanvanBussel** [comment]
OK, but also **remove "Other" section from FAQ**, so only keep sections "eID" and "Itsme" !!!

**Comment by maerckaert** [comment]
All should be correct in both languages in PROD.

**Comment by maerckaert** [comment]
In Acc also now.
