### ISSUE TITLE
Create main landing page "COVID-19 barometer"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#2]

**Comment by JohanvanBussel** [comment]
1st Review of Dutch landing page: see screenshot [https://app.zenhub.com/files/248791371/901436d5-39b8-4186-a86b-7fa43c61687e/download](https://app.zenhub.com/files/248791371/901436d5-39b8-4186-a86b-7fa43c61687e/download)

**Comment by JohanvanBussel** [comment]
![Covid19_main_page.jpg](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/a08d0c2a-3ddf-471b-8913-105986d8c37f)

**Comment by neuronick** [comment]
changes implemented

**Comment by neuronick** [comment]
Here is the alternative frontpage.
https://covid19.healthdata.be/front2
