### ISSUE TITLE
Implement results publishing to SFTP

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#20]
This contains the complete flow from the key-values tables loaded by entering data in drupal until the placement of the files on the SFTP folders of the different organisations that have the right to use (part of) the data.
It includes also the creation of a set of tables to manage this access per field...

**Comment by VrankenKris** [comment]
Pogram has been created and tested. Is ok for manual execution. Not yet automated and data is not yet written to DB2 (only to permanent SAS tables and CSVs). Export to SFTP has to be added.

Things to do
- creation of DB2 STG tables
- change the program so these tables are used
- write to SFTP
- pharmacists --> specificity: multichoice

Changed milestone to Wednesday (pharmacists)

**Comment by VrankenKris** [comment]
Program has been created and tested. Is ok for manual execution. Not yet automated and data is not yet written to DB2 (only to permanent SAS tables and CSVs).

Things to do
- creation of DB2 STG tables
- change the program so these tables are used
- User access has almost been added

**Comment by evelynedewitte** [comment]
@VrankenKris 

It is not clear what I need to do here?

**Comment by VrankenKris** [comment]
@evelynedewitte This was just to inform you

**Comment by VrankenKris** [comment]
Part of it is put in 'industrialisation' of the flow
