### ISSUE TITLE
INFORM SOB-team about use of eID/Itsme for access to all COVID19 forms

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#200]

**Comment by hamzasciensano** [comment]
SOB Collaborators has been informed about:

1. eID and itsme will be active from today on, on the web page covid19.healthdata.be
2. That an FAQ about eID and itsme has been made available at the landing page of covid19 Barometer forms.
3. eID and it'sme related questions/issues will be supported by Healthdata.be Service Desk.
4. For complicated web related issues to inform Nikita's Team.

@lufillet 
Could you please update our Covid-19 Knowledge Base as well?

Many thanks
Hamza

**Comment by lufillet** [comment]
KB has been updated
