### ISSUE TITLE
Add Brussels Professional Circles (GP)

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#201]

**Comment by VrankenKris** [comment]
[https://app.zenhub.com/files/248791371/7678c105-a469-4310-9da3-303fb37585d6/download](https://app.zenhub.com/files/248791371/7678c105-a469-4310-9da3-303fb37585d6/download)

**Comment by evelynedewitte** [comment]
Tested & validated on ACC.

**Comment by evelynedewitte** [comment]
@maerckaert 
I already validated on ACC so we can move to PROD. Unless you want me to check something?
