### ISSUE TITLE
Geconnecteerd als iemand anders

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#202]
![image.png](https://images.zenhubusercontent.com/5bfe323082265008a04d6831/581bdb74-76ea-474f-b344-8524d6796dfb)
After logging into production using eID my name does NOT appear but always the same name. Althoug in 'my profile' it is clearly me and my data will be sent.
In acceptance this does not happen

**Comment by neuronick** [comment]
@VrankenKris Seems that that variable was too aggressively cached. I have changed implementation. Can you confirm it works ok?

**Comment by VrankenKris** [comment]
[cid:image003.jpg@01D612A0.C6F8F4C0]

It is ok now

Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail
