### ISSUE TITLE
All covid-19 barometers: update FAQ on intro page

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#208]
Add the following questions & answers to the FAQs.

**Comment by evelynedewitte** [comment]
- [ ] Mag ik de registraties van vorige dagen ook ineens mee ingeven?
o   Neen, enkel van de dag zelf.          

- [ ] Ik ben begonnen registraties in te geven, kan ik deze opslaan en nadien verder gaan?
o   Neen, moeten ineens afgewerkt worden.

- [ ] Werkt itsme ook op de website?
o   Ja

- [ ]  Ik kan niet inloggen als dokter, mag ik als burger de gegevens ingeven?
o   Ja

- [ ] EID en Itsme werkt niet, hoe kan ik de Covid-19 barometer invullen?
o   EID en Itsme kan soms problemen geven wanneer u de Covid-19 barometer via een Artsen software opent. We raden u rechtstreeks het URL https://covid19.healthdata.be/ te gebruiken in uw internet browser.

- [ ] Waarom zie ik een andere naam bij het aanmelden met de EID?
o   Uw internet browser toont de certificaten van de gebruikers die eerder EID gebruikt hebben. Als u beneden scrolt, gaat u uw naam ook zien.

**Comment by neuronick** [comment]
@evelynedewitte 

Example here:
https://covid19-acc.healthdata.be/nl/gp

There is no FR translation though. 

Let me know if this is ok, so I can duplicate it on other forms / PROD.

**Comment by evelynedewitte** [comment]
22/04: Lode Journée helpt ons dit wat beter uit te schrijven.

**Comment by evelynedewitte** [comment]
[https://app.zenhub.com/files/248791371/07f83225-2e2c-451b-bb4b-0cdc608a5c4e/download](https://app.zenhub.com/files/248791371/07f83225-2e2c-451b-bb4b-0cdc608a5c4e/download)

**Comment by evelynedewitte** [comment]
@maerckaert Tu peux vérifier le français en-dessous?

Q: Puis-je saisir immédiatement les inscriptions des jours précédents?
R: Non, ce n'est pas possible. Vous ne pouvez saisir que l'enregistrement de la journée en cours.

Q: J'ai commencé à saisir des données dans le baromètre Covid-19. Est-il possible de sauvegarder une partie de mes inscriptions entre-temps et d'arrêter l'inscription pour la reprendre plus tard?
R: Non, ce n'est pas possible. Une fois que vous avez commencé une inscription, vous devez la compléter.

Q: Puis-je me connecter au site Web via itsme?
R: Il est en effet possible de se connecter au site via itsme.

Q: Je ne peux pas me connecter en tant que médecin. Puis-je me connecter avec mon compte personnel pour commencer à m'inscrire dans le baromètre Covid-19?
R: Oui, c'est possible.

Q: Je ne parviens pas à me connecter via eID ou via itsme. Que dois-je faire pour commencer mon inscription dans le baromètre Covid-19?
R: eID et itsme peuvent parfois causer des problèmes lorsque vous souhaitez vous enregistrer via un logiciel spécifique (médecin). Nous vous recommandons d'ouvrir l'URL https://covid19.healthdata.be/ directement dans votre navigateur.

**Comment by maerckaert** [comment]
@evelynedewitte for me it's ok. I don't see any error in French.

**Comment by neuronick** [comment]
@evelynedewitte I have update faq, but there is a problem. We have a limit of 128 characters for the question and some questions in NL / FR are longer than that and are trimmed.
There are 3 possible solutions:
- Make questions shorter
- Create short version of the question (something like Title) and use both Q: / A: inside the answer
- Don't use accordion and just show all questions / answers as one big text block.

Please let me know which one and provide the additional info (incase of option 1 or 2).
