### ISSUE TITLE
Adapt eHealth message during login by ItsMe/eID

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#209]
![Screenshot 2020-04-20 13.12.06.png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/9e1cf460-2d50-4cb0-9061-b58525792971)

During login a screen is shown that needs to be updated:

as-is
Aanmelden voor Wetenschappelijk Instituut Volksgezondheid - Healthdata for Patient

to-be
SCIENSANO - HD-APPS

**Comment by VrankenKris** [comment]
Mail sent to eHealth (Wolf)
