### ISSUE TITLE
Request: New FOOTER for covid19.healthdata.be

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#21]
CURRENT FOOTER
![Main_COVIDA9_footer_review1.JPG](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/865b8b72-ba3b-4ccd-940b-f7c3f4c72e01)

Proposal NEW FOOTER
![Main_COVIDA9_footer_review2.JPG](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/5534fdda-f6b1-49cd-a386-dfc1ea3cdc7a)

**Comment by maerckaert** [comment]
The ehealth logo is not visible on the footer. its color needs to be clearer.
The logo between INAMI and AFMPS is missing.
See screenshot.
![footer](https://user-images.githubusercontent.com/59559118/77252645-6faf4980-6c55-11ea-8176-cb47e57ca952.JPG)

**Comment by neuronick** [comment]
I have made ehealth logo lighter and added the missing logo (FOD VG)

and the footer is deployed.
