### ISSUE TITLE
Transform jsons into CSVs

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#221]
Transform the json of the form specification into a filespecification for the CSV
Transform the json example records into csv example records

**Comment by evelynedewitte** [comment]
@LanderBroothaers 

**COVID19_lab_20200422.json** zou omgevormd moeten worden tot een ‘relationeel’ model en dan in csv’s moetne komen.

Zie de JSON file via e-mail.

**Comment by LanderBroothaers** [comment]
@evelynedewitte, Kris heeft deze taak overgenomen.

**Comment by evelynedewitte** [comment]
@VrankenKris Wat is de status hiervan?
