### ISSUE TITLE
Pharmacies: add a lot of questions to form

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#227]
**21 new questions (fields)**

(already requested: the following 5 fields):
cd_scale_patients_corona
cd_scale_patients_nonessential
cd_scale_patients_aggression
nr_num_hd_before
nr_num_hd_week

(additional request):
cd_questions_day
cd_questions_drugs
fl_drugs_without
cd_prod_to_cp
**cd_cp_contacted** --> obsolete and replaced
**cd_cp_contacted_buy** --> obsolete and replaced
cd_prod_to_patients
nr_num_patients_oxy
nr_num_patients_oxy_no
nr_num_patients_pp
nr_num_patients_pp_no
tx_drugs_oos
fl_covid19_distri
nr_num_compensation
nr_num_quest_mask19
cd_quest_schema

**Comment by evelynedewitte** [comment]
@maerckaert ON HOLD - waiting for a sign from business

**Comment by maerckaert** [comment]
@evelynedewitte 
The document covid19_fields is not updated.
Could you update the document with the field_name?

**Comment by maerckaert** [comment]
I did a first version with those fields name:
cd_scale_patient
cd_scale_essential
cd_scale_agression
nr_num_home_shipping_avg
nr_num_home_shipping

**Comment by evelynedewitte** [comment]
@maerckaert 
I just specified the field names, see in the description of this ticket!

**Comment by maerckaert** [comment]
@evelynedewitte for the two last one I think it should start with "nr_mun" because it's numeric fields.
cd_scale_hd_before => nr_mun_hd_before
cd_scale_hd_today => nr_num_hd_today 
Could you confirm if I'm right?

**Comment by evelynedewitte** [comment]
@maerckaert 

We received "some" extra questions... instead of 5, we now have 21.

Questions are formulated in the enclosed Word document containing the 21 questions in NL & FR:

[https://app.zenhub.com/files/248791371/7b926a8c-8b74-4919-8cbd-f8b50f8c0fa1/download](https://app.zenhub.com/files/248791371/7b926a8c-8b74-4919-8cbd-f8b50f8c0fa1/download)

**Comment by maerckaert** [comment]
@evelynedewitte  The translation of this field is not correct.
nl: Hoeveel ‘Masker 19’ vragen verkreeg u de afgelopen week in de apotheek?
fr: Combien de sollicitations avez-vous reçues dans le cadre de services d’aide aux victimes de violence domestiques/conjugales (“Masque 19”?)

**Comment by maerckaert** [comment]
@evelynedewitte Hoeveel thuisleveringen voerde u gemiddeld uit per dag in de afgelopen week? (antwoord: getal)
(FR: - Combien de livraisons à domicile avez-vous fait aujourd'hui?)

**Comment by evelynedewitte** [comment]
@maerckaert 
Tested on ACC and only 1 remark: the following phrase should be placed as indicated in the Word document:
 
Welke onderstaande producten kan u afleveren aan ambulante patiënten (kan u bestellen of heeft u op voorraad, of dat u dit werkelijk doet – staat hier los van)? 
-	ontsmettingsalcohol (voor oppervlaktes)
-	alcogel (voor handen)
-	handschoenen
-	chirurgische mondmaskers 
-	FFP2 maskers
-	Klassieke thermometer
-	Voorhoofdthermometer
-	Beschermende schorten
(FR : Quels produits ci-dessous pouvez-vous livrer aux patients ambulatoires (pouvez-vous commander ou les avoir en stock ?)
- alcool à friction (pour les surfaces)
- alcogel (pour les mains)
- des gants
- masques chirurgicaux
- Masques FFP2
- Thermomètre classique
- Thermomètre frontal
- Tabliers de protection)

**Comment by evelynedewitte** [comment]
@neuronick @maerckaert 
Please promoto to PROD before 15h today.
