### ISSUE TITLE
Load the data in DB2

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#228]
Dominique Van Beckhoven will put hte data of admissions, discharges and the clean data on a directory on the SFTP server. DWH has to put this data in DB2 tables.
Data needed to send the data back to the data providers are
- RIZIV number of physician
- KBO number (?) of the hospital

**Comment by KurtVanbrabant** [comment]
Data loaded.

STG.T_COVID19_RETURN_ADMIS_0420
STG.T_COVID19_RETURN_DISCH_0420
STG.T_COVID19_RETURN_ANAL_0421

**Comment by VrankenKris** [comment]
I have renamed the tables to STG.T_COVID19_RET_ADM_20200420, STG.T_COVID19_RET_DIS_20200420 and STG.T_COVID19_RET_ANL_20200420
