### ISSUE TITLE
Create a sub site for Covid19-acc.healthdata.be

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#23]
A subsite has to be created on the hd4patien-acc.healthdata.be server, sciensano has to create the record covid19-acc.healthdata.be to point to the IP dress of this server.
This is not as urgent as the production site, but it has to be done  as soon as possible.

**Comment by neuronick** [comment]
The subsite is created and ready. The only thing missing is the DNS record for **covid19-acc.healthdata.be** which should point to: **94.143.190.181** (Arxus internal: 10.72.129.34 – SCN-A-HD4PAT01)

**Comment by neuronick** [comment]
OK. Just test. DNS is working. Site is available.

If there is something needs to be done in order make Tom's REST endpoint operational on ACC (firewall changes / connection with DWH) it can proceed.

Then we can test ACC data transfer.

**Comment by tommichiels** [comment]
@VrankenKris  @neuronick   Are the tables created in DWH?

**Comment by VrankenKris** [comment]
Yes but check with Juan
Juan, are the tables for COVID19 in acceptance created? I thought I saw a mail sying so

Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

**Comment by VrankenKris** [comment]
Yes.

Juan Quesada
DWH Team Lead
Healthdata.be
M + 32 475 52 03 45
Skype: juan_wiv
[cid:image002.jpg@01D592ED.3BF69D60]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

From: Kris Vranken <Kris.Vranken@sciensano.be>
Sent: Wednesday, 25 March 2020 10:12
To: Sciensano-Healthdata/HD-Corona <reply@reply.github.com>; Sciensano-Healthdata/HD-Corona <HD-Corona@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Juan Quesada <Juan.Quesada@sciensano.be>
Subject: RE: [Sciensano-Healthdata/HD-Corona] Create a sub site for Covid19-acc.healthdata.be (#23)

Yes but check with Juan
Juan, are the tables for COVID19 in acceptance created? I thought I saw a mail sying so

Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

**Comment by tommichiels** [comment]
@VrankenKris @QuesadaJuan @neuronick   When the firewall is opened this should be working.
