### ISSUE TITLE
ALL barometers: give detailed information about the tickets related to the barometer

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#230]
Provide the Excel with information on created tickets related to the covid-19 barometer.

**Comment by hamzasciensano** [comment]
[Covid_questions.xlsx](https://github.com/Sciensano-Healthdata/HD-Corona/files/4514529/Covid_questions.xlsx)

Hi Evelyne,

Hereby I am attaching the list of created tickets at Support related to Covid-19 Barometer.

If you need extra information, please don't hesitate

Regards
Hamza

**Comment by hamzasciensano** [comment]
Hi Johan

The list with all incidents opened at Support is continuously updated with each single ticket that we receive, day and evening until 22 o clock.

You will always see the last tickets whenever you open it.

https://www.dropbox.com/s/sp58be7nnr63yyq/Covid_Incidents_and_Questions.xlsx?dl=0

Could you please confirm whether this is sufficient? Please let me know if you need extra columns in the list.

Many thanks in advance

Hamza

**Comment by evelynedewitte** [comment]
@hamzasciensano Checked with Johan & OK!
