### ISSUE TITLE
All barometers: monitor log-in attempts

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#234]
Wij zouden toch in staat moeten zijn om traject te volgen:
1.       Ip adres komt op barometer (login)pagina (= healthdata)
2.       IP adres wordt naar ehealth gestuurd (kunnen wij niet meer meten)
3.       IP adres komt of formulier …

**Comment by evelynedewitte** [comment]
Step 1: detail possible approaches & see who we need to involve to pick the best approach

**Comment by neuronick** [comment]
For the moment I see two possible approaches:

### Approach 1: Google Analytics
**Summary:**
As we already have Google Analytics integration setup, we can reuse it to track this  information. Some research is needed to make a link between anonymous / authenticated users as IP address is not reliable identifier for this purpose. Specific reports need to be setup as well.

**Pro's:**
- We already have the basic integration in place and use it for general web-analytics.
- Should be faster and will take less effort.
- No (or less) custom code will need to be maintained long-term.
- We can reuse built-in Google Analytics reporting and these reports can easily be automated / shared with other stakeholders from within the Google Analytics itself.

**Con's:**
- This will probably require additional discussion / authorization regarding privacy / GDPR
- Metrics are sent to the third-party (but it is already the case for the basic web stats).

### Approach 2: Custom tracking / logging / reporting
**Summary:**
Custom solution can be programmed to provide this functionality based on temporary session storage / cookies (we have part of this already in place for autofill). This approach will require more effort and will probably take more time, as not only tracking and logging will be needed but also custom reporting functionality as well. 

**Pro's:**
- Solution tailored exactly for our needs
- Probably less 'invasive' privacy-wise
- Metrics are kept on-premise.

**Con's:**
- Will take more time / effort
- The code will need to be maintained long-term

**Comment by evelynedewitte** [comment]
Feedback from @VrankenKris and @tommichiels : 

**Chosen solution: via the use of cookies** 

- Tom Michiels: De cookies die gebruikt worden om sessies te maken op Drupal kunnen gelogd worden in een access.log file. In een acces.log staat dan ook de url waarnaar er gesurft wordt.  Bij succes authenticatie komt er nog eens een extra header bij denk ik met RRN van de gebruiker in. met al deze info moet je gemakkelijk report kunnen maken.
Cookies kunnen ook permanenter gemaakt worden dan enkel de websessie en dan kan je zelfs over dagen heen zien wat het gedrag is gekoppeld aan een welbepaalde bowser Als de gebruiker dan met zijn eis 2 browser gebruikt dan kan de link weer gemaakt worden via rrn.
Ik denk dus dat de combinatie cookie http call recording in een acces.log file voldoende data geeft om de vragen rond gebruik op te lossen.


- Kris: Ik wil data in DB2,  ik wil rapporten in DWH.
Ik wil dat die data doorstromen naar het DWH zodat we in de toekomst die data ook met andere data entry systemen die geen eID gebruiken kunnen vergelijken (LimeSurvey, EMD ingave, etc) en niet binnen 1 applicatie blijven met ons rapport.

**Comment by neuronick** [comment]
Deployed to ACC.

The stats are accessible in **/home/sciensano/covid19_stats** folder. 
The file should be copied (not moved) to SFTP.

schema: https://github.com/Sciensano-Healthdata/hd-hd4patient/blob/master/web/modules/custom/hd_stats/docs/hd_stats.schema.json

csv dialect: https://github.com/Sciensano-Healthdata/hd-hd4patient/blob/master/web/modules/custom/hd_stats/docs/hd_stats.dialect.json

**Comment by VrankenKris** [comment]
@neuronick can you copy the stats to the SFTP folder? So a SAS program can be written to read them?

**Comment by neuronick** [comment]
@VrankenKris Of course. What is the path (of the SFTP folder)?

**Comment by VrankenKris** [comment]
@neuronick Is this still needed?

**Comment by evelynedewitte** [comment]
@VrankenKris 
This is done. Issue closed.
