### ISSUE TITLE
Split COVID19 Barometer into a separate codebase

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#237]
Split COVID19 Barometer into a separate codebase, remove unneeded modules / custom code, clean up leftovers of hd4patient.

**Comment by VrankenKris** [comment]
@neuronick Is this done? Needed?

**Comment by VrankenKris** [comment]
@neuronick This should not be an Epic, just an issue

**Comment by evelynedewitte** [comment]
The split already happened. 
Can be closed.
