### ISSUE TITLE
Adjust access rights to data for: PHARMACIES

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#250]
Pharmacies:
- 21 new questions
- access rights for these 21 questions were updated in the Covid19-barometer data access file.

**Comment by evelynedewitte** [comment]
@VrankenKris 
After discussion with Nikita & Jonathan, I had to adapt the fields.

This is what changed: 

1. Instead of **cd_cp_contacted** we now have:
nr_num_cp_contacted_gp
nr_num_cp_contacted_hn
nr_num_cp_contacted_mw
nr_num_cp_contacted_tri
nr_num_cp_contacted_wz
nr_num_cp_contacted_den
tx_cp_contacted_oth

2. Instead of **cd_cp_contacted_buy** we now have:
nr_num_cp_buy_gp
nr_num_cp_buy_hn
nr_num_cp_buy_mw
nr_num_cp_buy_tri
nr_num_cp_buy_wz
nr_num_cp_buy_den
tx_cp_buy_oth

**Comment by VrankenKris** [comment]
@evelynedewitte This is still in the pipeline new issues and you have worked on it. What is the status?

**Comment by VrankenKris** [comment]
@JohanvanBussel I have to add 47 !!! fields
