### ISSUE TITLE
Install Drupal

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#255]

**Comment by neuronick** [comment]
@VrankenKris I have some question regarding this, to understand how we should better setup this and make it more future-proof.

- Is there a document on Dropbox or somewhere describing what we are trying to achieve? I would like to know some background to better understand the big picture.

- Are there any specific requirements which are absolutely a must? (for example: only PostgreSQL and no MariaDB or MySQL)?

- What functionality should the new site(s) have? The same as Barometer? Something extra?

- Do we foresee any custom integrations? (except for the eID authentication and what we already have in Barometer)?

- When you talked about multiple sites, are they going to have identical functionality / look and just different URL / forms / users? Or will they differ more substantially? And roughly how many of these are we going to have?

- What about the look? The same as Barometer or different? Will the site(s) be used on mobile platforms as well?

- Who will be the PM for this (to not bother you or Johan unnecessarily)? I assume Evelyne?

**Comment by VrankenKris** [comment]
- Not yet, I am working on it today and tomorrow
- PostGres
- Data entry --> fire and forget, like barometer
- Only eID
- Identical functionality, 1 landing page
- Look --> Same as barometer I think (Johan)
- I am PM

**Comment by GertGuHD** [comment]
@neuronick > eID integratie à 29/4/2020 09:00 meeting with eHealth

**Comment by neuronick** [comment]
We got the eID working as "ACC". After the meeting 13u00, they can activate "PRD".

**Comment by GertGuHD** [comment]
http://covid19lab.healthdata.be/ is nu beschikbaar op HTTPS met redirect op HTTP.

**Comment by neuronick** [comment]
Basic drupal is installed. There will be still some changes needed here and there, but we will tackle them in separate issues.
