### ISSUE TITLE
Create "Status form for Midwifes" 

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#26]

**Comment by maerckaert** [comment]
Johan,
For the field in the screenshot could we use something like Like: 0 = Ik voel mij mentaal zeer zwaak; 10 = Ik voel mij mentaal zeer sterk instead of prefix and suffix?
![scale](https://user-images.githubusercontent.com/59559118/77256057-1c94c100-6c6c-11ea-877b-8f6dd6bfd1bb.JPG)

**Comment by JohanvanBussel** [comment]
Hello Jonathan,
You can ask Eline,
But midwives is not urgen, is for Wednesday evening!!
Greetz,
Johan

----------------------------------------------------------------------------------------------------
Johan van Bussel
Head of service
Healthdata.be
M + 32 485 85 16 97
Skype johan.vanbussel@sciensano.be
[cid:image001.jpg@01D54DCF.B4D16B10]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

**Comment by neuronick** [comment]
draft of the form is deployed:
https://covid19.healthdata.be/nl/midwives/status

**Comment by maerckaert** [comment]
From Eline:

Dear Jonathan,

 

Definitely, what works best in the system that you have. The content is the same so that is perfectly fine with me!

 

Kind regards,

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/496cae8f-6854-4136-9bcc-41f61093ca42)

Title NL: "CRA" must be changed into "Vroedvrouwen"
Title FR: "CRA" must be changed into "Sages-femmes"

Intro NL: "17" must be changed into "enkele"
Intro NL: "17" must be changed into "quelques"

Intro NL: "CRA" must be changed into "Vroedvrouwen"
Intro FR: "CRA" must be changed into "Sages-femmes"
