### ISSUE TITLE
Implementation of COVID-19 messages in software of Hospitals, Laboratories, GP's and Triage Posts

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#266]
Create detailed inventory of all software providers of Hospitals, Laboratories, GP's and Triage Postsall 

In order to address issues and to follow up requests/changes, we need to know which Data Provider is using which Vendor's software. Aim of this task is to have a list of all data providers, with which vendor's software they are using, including the contact details:

- [x]  Create a List with all Data Providers
- [x]  Add Software Vendor per Data Provider
- [x] Add Contact details

https://www.dropbox.com/scl/fi/8dxzs5br92bk5ae2eqych/HD4COVID19LAB_Monitor_DataProviders_01.xlsx?dl=0&rlkey=ma9aj6jb2l3pphq95lftqqne9

**Comment by VrankenKris** [comment]
@hamzasciensano The goal is to create a document containing the different software vendors involved (careconnect, mips, chipsoft, etc), the data providers they have installed their software and then folllow up the success of sending test records that are usable by us and then per dataprovider whether we have received data.

**Comment by JohanvanBussel** [comment]
@hamzasciensano @VrankenKris @evelynedewitte see also main overview of data providers: https://www.dropbox.com/scl/fi/8dxzs5br92bk5ae2eqych/HD4COVID19LAB_Monitor_DataProviders_01.xlsx?dl=0&rlkey=ma9aj6jb2l3pphq95lftqqne9

**Comment by hamzasciensano** [comment]
Task assigned to Gaetan.

**Comment by gmuyldermans** [comment]
document seems up to data
