### ISSUE TITLE
CRA: check whether pre-filling works

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#267]
We received a mail in the evening of April 29, indicating that for CRA, the prefilling does not work.

**Comment by evelynedewitte** [comment]
@maerckaert 
For me, the prefilling on ACC is working.
On PROD it is not working. Is the pre-filling only active once you have submitted your answers? Because in that case, I cannot test on PROD.

**Comment by maerckaert** [comment]
@evelynedewitte I don't know how to test in PROD without sending dummy data.
I investigated and you need to submit the form in order to have the prefill values registered.
I tested on ACC and it's working fine

**Comment by evelynedewitte** [comment]
@maerckaert 
We received another complaint about the fact that the prefilling is not working for CRA (and only for CRA).

I seems to me it might be a good idea to test this on production by submitting to the survey and then remove the submitted lines right after?
