### ISSUE TITLE
MIDWIVES FORM: adding 2 questions

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#269]
Request received:
In de barometer voor vroedvrouwen willen we graag ook volgende vragen (naar analogie van de  andere beroepsgroepen) toevoegen:

**nr_num_clients_covid19_pos**
**nr_num_clients_covid19_pot**

**Comment by evelynedewitte** [comment]
@helene-ameels 

This is a new request from the Consortium. We have to put it in production for 11/05 so we have plenty of time.

I would like to perform all the necessary steps with you to execute this task. I will organise a meeting for this.

**Comment by evelynedewitte** [comment]
Steps to take:
- [ ] Update the covid19_fields document on Dropbox: add the new fields
- [ ] Ask Nikita to adapt the form 
- [ ] Ask Caroline Verlinde (Vivel) who may have access to the resulting data
- [ ] Update the Barometer Access file accordingly --> communicate to Kris
- [ ] Validate the form & ask end-users to perform UAT

**Comment by evelynedewitte** [comment]
To place after:

Hoeveel cliënten begeleidt u of de praktijk op een doorsnee dag? (dus niet in corona periode)
Hoeveel cliënten informeert u of de praktijk op een doorsnee dag telefonisch? (dus niet in corona periode)
Hoeveel cliënten begeleidde u of de praktijk vandaag (enkel face-to-face)?
Hoeveel cliënten informeerde u of de praktijk vandaag telefonisch?

**Comment by helene-ameels** [comment]
Addition of 2 questions as requested : ok

**Comment by evelynedewitte** [comment]
UAT feedback received on 8/05: OK!

@neuronick Can be moved to PRD but we await the GO from @VrankenKris

**Comment by helene-ameels** [comment]
ok in PROD

**Comment by evelynedewitte** [comment]
@VrankenKris 

The questions have been added to the form in ACC & PRD.

We received the answer from Caroline Verlinde concerning access to these answers. See the forwarded mail from Hélène.
