### ISSUE TITLE
Home Nurses: capacity

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#270]
As for Family Care, the question **cd_capacity_region** needs to be added before the field **fl_capacity_next_days** for the following form:
- [x] Home Nurses IND

Out of scope: Home Nurses EMP

**cd_capacity_region**
NL: Zijn er regio’s waar jullie geen prioritaire zorgvragen meer kunnen beantwoorden?
FR: Y a-t-il des régions où vous ne pouvez plus répondre aux questions de soins prioritaires?

Value list is the one for Family care.

**Comment by helene-ameels** [comment]
@evelynedewitte - I've added the corresponding FR translation in the Zenhub board (see above)

**Comment by helene-ameels** [comment]
Steps to take:
- [x] Update the covid19_fields document on Dropbox: add the new fields
- [ ] Ask Jonathan to adapt the form 
- [ ] Ask Caroline Verlinde (Vivel) who may have access to the resulting data
- [ ] Update the Barometer Access file accordingly (Roel, Caroline) --> communicate to Kris
- [ ] Validate the form & ask end-users to perform UAT

**Comment by evelynedewitte** [comment]
@maerckaert @helene-ameels 

I have updated the Excel file to contain the columns "Province" and "Code_Drupal".

This allows us to filter the value list shown to the user, to be filtered upon the Province they already indicated.

**Comment by evelynedewitte** [comment]
cd_capacity_region: to put LoV of "gezinszorg" (family care) instead home nurses (sorry!)

**Comment by helene-ameels** [comment]
@maerckaert : NL : ok - FR : the list should not be in FR. Evelyne suugested that because we do not have (for the moment) the list of region for Wallonia, that we instead put a free text.
She will however check with Kris as it is a federal project, to see if someone can provide the walloon region. @evelynedewitte 
@maerckaert - could you modify the FR version (2 questionnaires: IND/EMP) accordingly?

**Comment by maerckaert** [comment]
@helene-ameels : Do I have to create a new field? In this case we need to update the covid19_fields document.

**Comment by helene-ameels** [comment]
@evelynedewitte - Provide a mapping to Jonathan so the region list is filtered based on the province

**Comment by evelynedewitte** [comment]
@helene-ameels @maerckaert 

I added a column "province (iso)" to the excel file "Diensten voor gezinszorg".

Jonathan, can you make sure the filtering on Province is the same for the form "Gezinszorg"?

Thx

**Comment by maerckaert** [comment]
@helene-ameels : Waiting for deployment in Acc by Nikita.

**Comment by neuronick** [comment]
deployed to ACC

**Comment by helene-ameels** [comment]
FORM SALARIE: ok for both FR and NL

FORM INDEPENDANT: not ok - problem is because field 'province is not present' whereas it is on the SALARIE form. Instead we've the field 'postal code' - @evelynedewitte

**Comment by maerckaert** [comment]
@helene-ameels : deployed on acc.

**Comment by evelynedewitte** [comment]
@maerckaert @helene-ameels 

NL: looking good

FR: not good --> we cannot show the values from the LOV from NL. We can only show "autre".

**Comment by helene-ameels** [comment]
For IND (FR/NL), because Kristel informed it is out of scope:  
- [ ] remove 'cd_capacity_region' 
- [ ] put back 'postal_code'

EMP: waiting feed-back client UAT

**Comment by helene-ameels** [comment]
IND: ok
EMP: waiting feed-back client UAT

**Comment by evelynedewitte** [comment]
@helene-ameels 
As you said: we have to update:
- [ ] covid19_fields document
- [ ] data_access
