### ISSUE TITLE
Healthdata to Contact Center: create example messages

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#276]
Create example messages to test the interaction between HD and SmalS:
- [ ] Script 1A
- [ ] Script 1B
- [ ] Script 2A
- [ ] Script 2B
- [ ] Script 3A
- [ ] Script 3B

![image.png](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/f73347da-496e-4e51-969d-d5b821ddec62)

**Comment by evelynedewitte** [comment]
Data for Script 1A: see Excel[https://app.zenhub.com/files/248791371/6e59bc4b-942a-4230-9d53-06caf7912f77/download](https://app.zenhub.com/files/248791371/6e59bc4b-942a-4230-9d53-06caf7912f77/download)

Input: HD to SmalS
Output: SmalS to HD

**Comment by marijkepauwels** [comment]
@evelynedewitte : enkele vragen

1. Formaat datetime zoals beschreven: **30apr20:12:30:00,10**?
2. Gender: **m** of **f** in kleine letters of hoofdletters of beide erin zetten? 
3. date_of_birth_index_patient: Maakt het formaat iets uit? **05/03/1980** bijvoorbeeld?
4. Snowmed_label_person1: wat moet hierin komen te staan? Is een mandatory field

**Comment by evelynedewitte** [comment]
@marijkepauwels 
1. Yes
2. Gender: doe maar es beide
3. dob: ik zou het voorbeeld volgen. Steek er wel wat "foute" formaten in
4. Het SNOMED label van de "RelationshipCodelist". Zie de Word in bijlage (net ontvangen).
5. Zelf gecreëerde data, wees maar vindingrijk :)

.[https://app.zenhub.com/files/248791371/677b6869-ab3d-46db-9e7d-4eeada413deb/download](https://app.zenhub.com/files/248791371/677b6869-ab3d-46db-9e7d-4eeada413deb/download)
