### ISSUE TITLE
 COVID19Lab Drupal: Create LaboratoryTestPrescription form [message 1]

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#280]
When patients visit a physician, being a general practitioner, or working at a triage post or hospital, and the patient meets criteria for a test, the physician needs to complete a specific COVID-19 LaboratoryTestPrescription form.

The COVID-19 LaboratoryTestPrescription is a specific form because it includes detailed contact information of the patient, the contact person(s) in case of emergency (ICU), language and the type of collectivities the patient is part of. This information is important in the context of contact tracing by the COVID-19 Call Center. 

Points of attention:
- In case the patient has a NISS or a NISS Bis number, the regular address information, date of birth and gender should not be provided. This information is available at the COVID-19 central database, through ConsultRN.
- In case the patient has no NISS or a NISS Bis number, a NISS should be created using the ConsultRN integration in EMD or HIS:
  - https://www.ehealth.fgov.be/ehealthplatform/nl/service-webservices-consultrr
  - https://www.ehealth.fgov.be/ehealthplatform/fr/service-webservices-consultrn
- This is also the case for foreign tourists.
- In that case, the address information of his / her stay in BELGIUM should be recorded in the LaboratoryTestPrescription.
- As for the field “Country”, the country of permanent residence should be recorded in the LaboratoryTestPrescription
- In case the patient is a minor (child), one of the parents, guardian or legal representative, should be provided as first contact person to (“FirstNamesContp1”; “LastNameContp1”; “TelephoneNumberMobileContp1”).

### Message1: LaboratoryTestPrescription (JSON)
```
[
  {
    "PatientIdentificationNumber": "2000013112356",
    "FirstNamesPat": "Lydia",
    "LastNamePat": "Malfait",
    "Street": "Albertplein",
    "HouseNumber": "1",
    "HouseNumberLetter": "a",
    "Postcode": "1050",
    "Municipality": "Elsene",
    "Country": "BE",
    "DateOfBirth": "2000-01-30",
    "Sex": "248152002",
    "TelephoneNumberMobilePat": "0478564512",
    "TelephoneNumberLLPat": "035698795",
    "HealthcareOrElderlyCareWorker": "true",
    "PartOfCollectivity": "yes",
    "Collectivity/LongTermCareFacility": "42665001",
    "Collectivity/School": "257698009",
    "Collectivity/ChildDayCareCenter ": "413817003",
    "Collectivity/PenalInstitution": "257656006",
    "Collectivity/CenterForAsylumSeekers": "CC0001",
    "Collectivity/InstitutionForPeopleWithDisabilities": "CC0002",
    "Collectivity/RehabilitationHospital": "80522000",
    "Collectivity/Psychiatric hospital": "62480006",
    "Collectivity/CenterForHomelessOrUndocumentedMigrants": "CC0003",
    "CollectivityOther": "sportclub",
    "FirstNamesContp1": "Jan",
    "LastNameContp1": "Peeters",
    "TelephoneNumberMobileContp1": "0478562314",
    "TelephoneNumberLLContp1": "092651245",
    "RelationshipContp1": "262043009",
    "FirstNamesContp2": "Martine",
    "LastNameContp2": "Dhont",
    "TelephoneNumberMobileContp2": "0457021548",
    "TelephoneNumberLLContp2": "06458978",
    "RelationshipContp2": "RS0007",
    "EncounterContactType": "CT0002",
    "EncounterStartDateTime": "2020-04-13 10:00:00",
    "ProblemStartDate": "2020-04-12 22:00:00",
    "HealthProfessionalIdentificationNumberPrescr": "1000456012",
    "HealthcareProviderIdentificationNumberHosp": "75689012",
    "HealthcareProviderLocation": 1040,
    "DepartmentSpecialty": 309998007,
    "CTThoraxResult": 10828004,
    "HealthProfessionalIdentificationNumberDmg": "14584569001",
    "TestPrescribed": "yes",
    "HealthcareProviderIdentificationNumberLab": "85694587"
  }
]
```

**Comment by neuronick** [comment]
The basic form can be found here:
https://covid19lab.healthdata.be/forms/ltp

**Comment by neuronick** [comment]
- [ ] Provide international format placeholder for mobile phone (+ description text)
- [ ] Remove the CommunicationLanguage fields
- [ ] Add fieldsets to group visually contact 1, contact 2 fields etc.
- [ ] Date / time => time should be optional

**Comment by evelynedewitte** [comment]
I have created some test records.

Some remarks:
- [ ] "letter following the house number" is a mandatory field --> not logic, what if I don't have one ;-)
- [ ] Indicate that all phone numbers must be in international format
- [ ] The organization’s NIHDI identification number: only mandatory if hospital
- [ ] Campus number of the location where the patient is admitted: only mandatory if patient is admitted on campus of hospital
- [ ] Department specialty: optional (only for Hospital)
- [ ] CTThoraxResult: optional (only for Hospital)
- [ ] The date and optionally, the time at which the contact took place --> I am still forced to fill in the time

**Comment by neuronick** [comment]
@evelynedewitte 
For me 'only for Hospital' criterion is still unclear. Based on what value(s) / field(s) do we check this?

**Comment by neuronick** [comment]
@evelynedewitte 
Just discussed this with @VrankenKris. For drupal forms all the fields with this criterion should be made '**optional**' (we cannot know if it is been filled-in by the hospital or not, without complicating the process).

**Comment by neuronick** [comment]
@JohanvanBussel @evelynedewitte @VrankenKris 

Questions regarding this form:
- Should **NISS** be validated? Should we force a certain format? (or do we allow any input)
- Should any other fields be grouped (visually) into a fieldset(s)? If yes, provide per fieldset:
  - The **name** of the fieldset itself (**EN / NL / FR**);
  - whether it should be **collapsible**;
  - **open** or **closed** by default.
  - List the **fields** to include into the fieldset

Missing info:
- '**The health professional NIHDI identification number of the prescriber**' (**HealthProfessionalIdentificationNumberPrescr**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The organization’s NIHDI identification number**' (**HealthcareProviderIdentificationNumberHosp**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**Campus number of the location where the patient is admitted**' (**HealthcareProviderLocation**) still only contains one dummy option.
 Where do I find **HealthcareProviderLocationCodelist**? Or should this field become a textfield instead of select?
- '**The health professional NIHDI identification number of the DMG owner**' (**HealthProfessionalIdentificationNumberDmg**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The lab’s NIHDI identification number **' (**HealthcareProviderIdentificationNumberLab**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?

**Comment by VrankenKris** [comment]
@neuronick you can find here the list of possible values and their labels. We would like to have autocomplete with the possibility to add another text (like inthe barometer)https://www.dropbox.com/home/HD_Projects/HD_9999_COVID19_Platform/InputDataForDB2

**Comment by evelynedewitte** [comment]
Remarks after review:
- [ ] Adjust the title "Laboratory Test Prescription" (header)
- [ ] I am lacking the "HealthcareProviderLocation" (where a postal code can be entered

**Comment by neuronick** [comment]
the changes are implemented and deployed to PROD
