### ISSUE TITLE
COVID19Lab Drupal: Create ResultFlagsSuspicionFalseNegativeTest form [message 3]

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#281]

**Comment by neuronick** [comment]
The basic version can be found here:
https://covid19lab.healthdata.be/forms/rfsfnt

**Comment by evelynedewitte** [comment]
Patient NISS identification number --> filled in a NISS, still have to specify Official Last Name + Street Name of Address...  --> need to adapt this

**Comment by neuronick** [comment]
- [ ] Make PatientIdentificationNumber optional
- [ ] "letter following the house number" is a mandatory field --> make optional (see mail Johan)
- [ ] Change dateofbirth to a text field with validation for date format (allowing incomplete dates)
- [ ] collectiondatetime1: Date / time => time should be optional
- [ ] testdatetime1: Date / time => time should be optional
- [ ] collectiondatetime2: Date / time => time should be optional
- [ ] testdatetime2: Date / time => time should be optional
- [ ] collectiondatetime3: Date / time => time should be optional
- [ ] testdatetime3: Date / time => time should be optional
- [ ] Switch off default browser autocompletion for all form elements
- [ ] healthcareprovideridentificationnumberhosp: make optional
- [ ] healthcareproviderlocation: make optional
- [ ] departmentspecialty: make optional
- [ ] ctthoraxresult: make optional
- [ ] HealthProfessionalIdentificationNumberDmg: make optional
- [ ] Switch off default browser autocompletion for all form elements

**Comment by neuronick** [comment]
@JohanvanBussel @evelynedewitte @VrankenKris 

Questions regarding this form:
- Should **NISS** be validated? Should we force a certain format? (or do we allow any input)
- Should any other fields be grouped (visually) into a fieldset(s)? If yes, provide per fieldset:
  - The **name** of the fieldset itself (**EN / NL / FR**);
  - whether it should be **collapsible**;
  - **open** or **closed** by default.
  - List the **fields** to include into the fieldset

Missing info:
- '**The health professional NIHDI identification number of the prescriber**' (**HealthProfessionalIdentificationNumberPrescr**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The organization’s NIHDI identification number**' (**HealthcareProviderIdentificationNumberHosp**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**Campus number of the location where the patient is admitted**' (**HealthcareProviderLocation**) still only contains one dummy option.
 Where do I find **HealthcareProviderLocationCodelist**? Or should this field become a textfield instead of select?
- '**The health professional NIHDI identification number of the DMG owner**' (**HealthProfessionalIdentificationNumberDmg**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The lab’s NIHDI identification number**' (**HealthcareProviderIdentificationNumberLab**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?

**Comment by evelynedewitte** [comment]
**Remarks after review:**
- [ ] Can we visually group the questions per Specimen? I was confused when testing...

"SpecimenId1":"SpecimenId1",
"CollectionDateTime1":"2020-04-13 09:53:00",
"TestCode1":"94558-4",
"TestDateTime1":"2020-04-13 16:04:00",
"TestResult1":"260415000",

"SpecimenId2":"SpecimenId2",
"CollectionDateTime2":"2020-04-14 08:00:00",
"TestCode2":"94500-6",
"TestDateTime2":"2020-04-14 21:00:00",
"TestResult2":"419984006",

"SpecimenId3":"SpecimenId3",
"CollectionDateTime3":"2020-04-15 10:00:00",
"TestCode3":"94507-1",
"TestDateTime3":"2020-04-15 10:00:00",
"TestResult3":"260415000",

**Comment by evelynedewitte** [comment]
@neuronick Can you check why there is an error message when I try to give on a datetime?

![Screenshot_error_message_datetimeformat.PNG](https://images.zenhubusercontent.com/5e7dd5bf3f01e29e633b0815/e4a82425-5984-487e-8593-d8a737942c12)

**Comment by neuronick** [comment]
I have improved validation / validation messages. Should work ok now.

Other changes are implemented as well.

Everything is deployed to PROD.
