### ISSUE TITLE
COVID19Lab Drupal: Create AlertSuspectedCaseNoTestPerformed form [message 4]

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#282]

**Comment by neuronick** [comment]
The basic version can be found here:
https://covid19lab.healthdata.be/forms/ascntp

**Comment by neuronick** [comment]
- [ ] Provide international format placeholder for mobile phone (+ description text)
- [x] Remove the CommunicationLanguage fields
- [ ] Add fieldsets to group visually contact 1, contact 2 fields etc.
- [x] Change dateofbirth to a text field with validation for date format (allowing incomplete dates)
- [ ] Date / time => time should be optional

**Comment by neuronick** [comment]
- [ ] Make PatientIdentificationNumber optional
- [ ] "letter following the house number" is a mandatory field --> make optional (see mail Johan)
- [ ] Change dateofbirth to a text field with validation for date format (allowing incomplete dates)
- [ ] encounterstartdatetime: Date / time => time should be optional
- [ ] problemastartdate: change to text field / add validation
- [ ] collectivity: make optional
- [ ] firstnamescontp1: make optional
- [ ] lastnamecontp1: make optional
- [ ] telephonenumbermobilecontp1: make optional
- [ ] telephonenumberllcontp1: make optional
- [ ] relationshipcontp1: make optional
- [ ] firstnamescontp2: make optional
- [ ] lastnamecontp2: make optional
- [ ] telephonenumbermobilecontp2: make optional
- [ ] telephonenumberllcontp2: make optional
- [ ] relationshipcontp2: make optional
- [ ] encountercontacttype: make optional
- [ ] HealthProfessionalIdentificationNumberDmg: make optional
- [ ] Switch off default browser autocompletion for all form elements

**Comment by neuronick** [comment]
@JohanvanBussel @evelynedewitte @VrankenKris 

Questions regarding this form:
- Should **NISS** be validated? Should we force a certain format? (or do we allow any input)
- Should any other fields be grouped (visually) into a fieldset(s)? If yes, provide per fieldset:
  - The **name** of the fieldset itself (**EN / NL / FR**);
  - whether it should be **collapsible**;
  - **open** or **closed** by default.
  - List the **fields** to include into the fieldset

Missing info:
- '**The health professional NIHDI identification number of the prescriber**' (**HealthProfessionalIdentificationNumberPrescr**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The organization’s NIHDI identification number**' (**HealthcareProviderIdentificationNumberHosp**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**Campus number of the location where the patient is admitted**' (**HealthcareProviderLocation**) still only contains one dummy option.
 Where do I find **HealthcareProviderLocationCodelist**? Or should this field become a textfield instead of select?
- '**The health professional NIHDI identification number of the DMG owner**' (**HealthProfessionalIdentificationNumberDmg**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The lab’s NIHDI identification number**' (**HealthcareProviderIdentificationNumberLab**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?

**Comment by VrankenKris** [comment]
you can find here the list of possible values and their labels. We would like to have autocomplete with the possibility to add another text (like inthe barometer)https://www.dropbox.com/home/HD_Projects/HD_9999_COVID19_Platform/InputDataForDB2

**Comment by evelynedewitte** [comment]
Remarks after review:
- [ ] The collectivity of which the patient is part of --> remove "Workplace" and "Boarding School" from LoV

**Comment by neuronick** [comment]
The list with healthcare professionals is very long. Autocomplete begins working starting from 2 characters minimum.

**Comment by neuronick** [comment]
The changes regarding collectivity are in PROD.
