### ISSUE TITLE
COVID19Lab Drupal: Create LaboratoryTestResult form [message 2]

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#283]

**Comment by neuronick** [comment]
The basic form can be found here:
https://covid19lab.healthdata.be/forms/ltr

**Comment by evelynedewitte** [comment]
In contrast with message1, where I did not fill in a NISS but filled in the other fields (name and so on), in this form I am obliged to fill in the NISS even if I fill in the other fields...

@VrankenKris 
Nog iets om mee te nemen in de business logica... wat als het testresultaat "inconclusive" is en niet duidelijk "pos" of "neg"...

**Comment by neuronick** [comment]
- [ ] Make PatientIdentificationNumber optional
- [ ] "letter following the house number" is a mandatory field --> make optional (see mail Johan)
- [ ] Change dateofbirth to a text field with validation for date format (allowing incomplete dates)
- [ ] collectiondatetime1: Date / time => time should be optional
- [ ] testdatetime1: Date / time => time should be optional
- [ ] collectiondatetime2: Date / time => time should be optional
- [ ] testdatetime2: Date / time => time should be optional
- [ ] collectiondatetime3: Date / time => time should be optional
- [ ] testdatetime3: Date / time => time should be optional
- [ ] Switch off default browser autocompletion for all form elements

**Comment by neuronick** [comment]
@JohanvanBussel @evelynedewitte @VrankenKris 

Questions regarding this form:
- Should **NISS** be validated? Should we force a certain format? (or do we allow any input)
- Should any other fields be grouped (visually) into a fieldset(s)? If yes, provide per fieldset:
  - The **name** of the fieldset itself (**EN / NL / FR**);
  - whether it should be **collapsible**;
  - **open** or **closed** by default.
  - List the **fields** to include into the fieldset

Missing info:
- '**The health professional NIHDI identification number of the prescriber**' (**HealthProfessionalIdentificationNumberPrescr**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The organization’s NIHDI identification number**' (**HealthcareProviderIdentificationNumberHosp**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**Campus number of the location where the patient is admitted**' (**HealthcareProviderLocation**) still only contains one dummy option.
 Where do I find **HealthcareProviderLocationCodelist**? Or should this field become a textfield instead of select?
- '**The health professional NIHDI identification number of the DMG owner**' (**HealthProfessionalIdentificationNumberDmg**) still only contains one dummy option.
 Where do I find **HealthProfessionalIdentificationNumberCodelist**? Or should this field become a textfield instead of select?
- '**The lab’s NIHDI identification number**' (**HealthcareProviderIdentificationNumberLab**) still only contains one dummy option.
 Where do I find **HealthcareProviderIdentificationNumberCodelist**? Or should this field become a textfield instead of select?

**Comment by VrankenKris** [comment]
you can find here the list of possible values and their labels. We would like to have autocomplete with the possibility to add another text (like inthe barometer)https://www.dropbox.com/home/HD_Projects/HD_9999_COVID19_Platform/InputDataForDB2

**Comment by evelynedewitte** [comment]
**Remarks after review:**
- [ ] Missing mentioning of "SpecimenId1" (TestResult1), "SpecimenId2" (TestResult2) and "SpecimenId3" (TestResult3).

**See example:**
"SpecimenId1":"SpecimenId1",
"CollectionDateTime1":"2020-04-13 09:53:00",
"TestCode1":"94558-4",
"TestDateTime1":"2020-04-13 16:04:00",
"TestResult1": "260415000",
"SpecimenId2":"SpecimenId2",
"CollectionDateTime2":"2020-04-14 08:00:00",
"TestCode2":"94500-6",
"TestDateTime2":"2020-04-14 21:00:00",
"TestResult2": "419984006",
"SpecimenId3":"SpecimenId3",
"CollectionDateTime3":"2020-04-15 10:00:00",
"TestCode3":"94507-1",
"TestDateTime3":"2020-04-15 10:00:00",
"TestResult3": "260415000",
