### ISSUE TITLE
COVID19Lab Drupal: Setup Cookie policy / privacy notice

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#293]
- [x] Create Cookie policy EN
- [x] Create Cookie policy NL
- [x] Create Cookie policy FR
- [x] Setup Cookie banner / consent
- [x] Provide NL translation for Cookie banner / consent
- [x] Provide FR translation for Cookie banner / consent
- [x] Deploy the changes
- [x] Remove Analytical cookies section (EN / NL / FR) as no Google Analytics will be used.
- [x] Update the texts based on the corrections agreed with Roel (EN / NL / FR)
- [x] Provide cookie policy link in the header or footer.

**Comment by neuronick** [comment]
Cookie policy page added:
EN: https://covid19lab.healthdata.be/cookie-policy
NL: https://covid19lab.healthdata.be/nl/cookiebeleid
FR: https://covid19lab.healthdata.be/fr/politique-en-matiere-de-cookies

**Comment by neuronick** [comment]
Cookie banner / consent added.

**Comment by neuronick** [comment]
Texts changed / link added to the header (EN / NL / FR).

**Comment by helene-ameels** [comment]
Modification implemented correctly
Roel to check the whole policy

**Comment by evelynedewitte** [comment]
@helene-ameels Thanks, Hélène!

@roelheijlen Can you validate the policy? If you agree with what was made, you can close the ticket. If not, please put your remarks in comment + reassign to Nikita.
