### ISSUE TITLE
Triage: Submission for Brussel

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#294]
I've submit a record with postal code 1000 in ACC, form triage - could you check whether you receive it?

**Comment by maerckaert** [comment]
@helene-ameels : I've tested in ACC in French and Dutch with the postal code of Brussels and I don't get any error.

**Comment by helene-ameels** [comment]
@maerckaert - ok merci. I'll follow-up with Kris

**Comment by helene-ameels** [comment]
No technical problem --> closed (no result in Brussel most probably linked to the drop out
