### ISSUE TITLE
Calculations on data from Labs

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#295]
FormLaboratoryTestResult:
•       IDSender
•       NameSender
•       DateMessageReceived
•       TestDateTime(1;2;3)
•       CollectionDateTime(1;2;3)
•       TestCode(1;2;3)
•       MeanTimeCollectionTest (gemiddelde in uren tussen variabele “CollectionDateTime” en “TestDateTime”)
•       MedianTimeCollectionTest (mediaan in uren tussen variabele “CollectionDateTime” en “TestDateTime”)
•       LowTimeCollectionTest (snelste/laagste tijd in uren tussen variabele “CollectionDateTime” en “TestDateTime”)
•       HighTimeCollectionTest (traagste/hoogste tijd in uren tussen variabele “CollectionDateTime” en “TestDateTime”)
•       MeanTimeTestMessageReceived (gemiddelde in uren tussen variabele “TestDateTime” en “DateTimeMessageReceived”)
•       MedianTimeTestMessageReceived (mediaan in uren tussen variabele “TestDateTime” en “DateTimeMessageReceived”)
•       LowTimeTestMessageReceived (snelste/laagste tijd in uren tussen variabele “TestDateTime” en “DateTimeMessageReceived”)
•       HighTimeTestMessageReceived (traagste/hoogste tijd in uren tussen variabele “TestDateTime” en “DateTimeMessageReceived”)
•       MeanTimeCollectionMessageReceived  (gemiddelde in uren tussen variabele “CollectionDateTime” en “DateTimeMessageReceived”)
•       MedianTimeCollectionMessageReceived (mediaan in uren tussen variabele “CollectionDateTime” en “DateTimeMessageReceived”)
•       LowTimeCollectionMessageReceived (snelste/laagste tijd in uren tussen variabele “CollectionDateTime” en “DateTimeMessageReceived”)
•       HighTimeCollectionMessageReceived (traagste/hoogste tijd in uren tussen variabele “CollectionDateTime” en “DateTimeMessageReceived”)
•       CountTests (aantal testen gerapporteerd)

**Comment by JohanvanBussel** [comment]
hallo @marijkepauwels : is deze actie "in progress"?

**Comment by marijkepauwels** [comment]
@JohanvanBussel: ik ben er mee bezig

**Comment by marijkepauwels** [comment]
Hoe maak ik de summary?

Eén summary met cd_test, cd_riziv, name_hosp, cd_riziv_lab, name_lab, cd_riziv_phys, name_prescr, cd_riziv_dmg, name_dmg, cd_riziv_dmg_2, name_dmg_2 als categorische variabelen?

Of op een andere manier?
