### ISSUE TITLE
GP + CRA + TRIAGE: adjust text on landing page

### ISSUE THREAD

**Issue by evelynedewitte** [Sciensano-Healthdata/HD-Corona#308]
Please update the landing page text according to the information in the comments

**Comment by evelynedewitte** [comment]
@maerckaert I've made some corrections to the Dutch version. Could you update the Dutch text on the 3 landing pages as follows:

[https://app.zenhub.com/files/248791371/95357954-5c59-439f-8e4c-1cde2e5d0c60/download](https://app.zenhub.com/files/248791371/95357954-5c59-439f-8e4c-1cde2e5d0c60/download)

**Comment by evelynedewitte** [comment]
@maerckaert I'm still working on the French version.

**Comment by maerckaert** [comment]
@evelynedewitte I think it's not the good link. It's the questions not the landing page.

**Comment by evelynedewitte** [comment]
@maerckaert I see the text for the landing page when I open the doc?

**Comment by evelynedewitte** [comment]
Status on 16/06:
- Dutch version in production --> all OK
- French version NOK: translation received from our translation service is not adequate. To escalate to coordination (by Evelyne).

**Comment by VrankenKris** [comment]
@evelynedewitte Is this done?
