### ISSUE TITLE
GP: corrections requested by Bert Vaes 22.03.2020

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#31]
[https://app.zenhub.com/files/248791371/f9bdf6e3-115e-4004-b514-46fcf7c9cef6/download](https://app.zenhub.com/files/248791371/f9bdf6e3-115e-4004-b514-46fcf7c9cef6/download)

**Comment by neuronick** [comment]
The requested changes are done.
