### ISSUE TITLE
ADMISSION Lime Survvey

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#319]
Documents provided by client (PDF, excel, .lss) --> Admission is survey 523543 
https://www.dropbox.com/sh/g7xir4mm971tbmp/AABj1prHqd5oVHqoKzpB-oBya?dl=0

+ Addition of NISS
+ add the following possible answers for the question ‘Expo_collective_housing’ :

- EN: Yes, other elderly housing /FR: Oui, Autre collectivité résidentielle pour personnes âgées (Résidence-services, seigneurie, …) / NL: Ja, Andere woongemeenschap voor ouderen (assistentiewoning, seniorie, service flat) 
- EN: Yes, disability institution /FR: Oui, Institution pour personnes handicapées /NL: Ja, Instelling voor personen met een handicap

**Comment by helene-ameels** [comment]
Name of the LS:
FR: Surveillance des patients Covid-19 confirmés hospitalisés – **données   d’admission** 
NL:  (not yet received) - Opname

**Comment by helene-ameels** [comment]
@neuronick For the question ‘Expo_collective_housing, have the two additional possible answered moved  up

**Comment by neuronick** [comment]
@helene-ameels Answers have been moved up.

**Comment by helene-ameels** [comment]
Name of LS (to be updated)  @neuronick 
FR: Surveillance des patients Covid-19 confirmés hospitalisés – volet admission
Nl: Formulier voor bevestigde gehospitaliseerde patiënten met het coronavirus COVID-19 – Deel Opname

**Comment by neuronick** [comment]
All requested changes are implemented.

**Comment by neuronick** [comment]
@helene-ameels The link at the and is fixed.

**Comment by helene-ameels** [comment]
Link (in ACC) provided to client on 14/07/2020 for UAT
