### ISSUE TITLE
DISCHARGE Lime Survey

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#320]
Documents provided by client (PDF, excel, .lss) --> Admission is survey 523543 
https://www.dropbox.com/sh/g7xir4mm971tbmp/AABj1prHqd5oVHqoKzpB-oBya?dl=0

+ Addition of NISS

+ when question « admission ICU »=’Yes’, have a direct link which send to LS ICU  - request still to be clarified with client

**Comment by helene-ameels** [comment]
Name of LS:
FR: Surveillance des patients Covid-19 confirmés hospitalisés – données de   sortie
NL: (not yet received) - Ontslag

**Comment by neuronick** [comment]
All currently requested changes are implemented.

Available to test on ACC:
https://acc-covid19hosp.healthdata.be/

**Comment by helene-ameels** [comment]
Name of LS (to be updated) @neuronick 
FR: Surveillance des patients Covid-19 confirmés hospitalisés – volet sortie
NL: Formulier voor bevestigde gehospitaliseerde patiënten met het coronavirus COVID-19 – Deel Ontslag

**Comment by helene-ameels** [comment]
+ Modification asked in email sent on 08/07/2020 @neuronick  - anything unclear, contact me.

**Comment by neuronick** [comment]
All requested changes are implemented.

**Comment by helene-ameels** [comment]
Link (in ACC) provided to client on 14/07/2020 for UAT
