### ISSUE TITLE
INTENSIVE CARE UNIT Lime Survey

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#321]
Develop the lime Survey based on information provided  by client:
https://www.dropbox.com/scl/fi/w4z7g5i45d0noymx8zgjf/ICU_supplement_20_06.22_for_HD.xlsx?dl=0&rlkey=j082x0sc61nlwhwd6sq3u2ntm

+ Add NISS variables

**Comment by helene-ameels** [comment]
@neuronick - some answers to your questions re. ICU:

- All variables need to be put as required except Fi_O2, PEEP, Value_lactate_USI, Value_PaO2_USI, Value_CRP_USI

- All questions of the LS 'ICU' can be put on only one page (no section/group)

- Last page: Keep same approach as for 'admission' and 'discharge', with variables 'Name, phone, email) ad indicating similarly that Name and phone only need to be filled-in the first time

**Comment by helene-ameels** [comment]
Introduction Text (green part) @neuronick 
FR: «  Ce formulaire doit être rempli pour tout patient COVID-19 confirmé par laboratoire ou par imagerie médicale (scanner thoracique) hospitalisé ayant séjourné en unité de soins intensifs. »
**NL:  not yet received**

**Comment by helene-ameels** [comment]
Name of LS:
FR: Surveillance des patients COVID-19 confirmés hospitalisés – données   des soins intensifs 
NL: **(not yet received)** - intensieve zorg

**Comment by neuronick** [comment]
All currently requested changes are implemented.

Available to test on ACC:
https://acc-covid19hosp.healthdata.be/

**Comment by helene-ameels** [comment]
Question ICU_dead_cause should appear only when ICU_outcome=dead (@neuronick ) - add this conditionality

**Comment by neuronick** [comment]
@helene-ameels Condition added.

**Comment by helene-ameels** [comment]
Name of survey (to be udpated)
FR: Surveillance des patients COVID-19 confirmés hospitalisés – volet soins intensifs
NL:  Formulier voor bevestigde gehospitaliseerde patiënten met het coronavirus COVID-19 – Deel intensieve zorg

**Comment by neuronick** [comment]
All requested modifications are implemented.

**Comment by helene-ameels** [comment]
FR/NL Translation received from client (for ICU): https://www.dropbox.com/scl/fi/v1fwdnj3jtwjim100s9jx/ICU_supplement_Translation_FR_NL_20200710.xlsx?dl=0&rlkey=sbgxksipzlr0254pjjn0jvda6

**Comment by neuronick** [comment]
@helene-ameels FR / NL translations has been added. Ready for testing.

**Comment by helene-ameels** [comment]
Following text is missing in the end message (@neuronick)
FR: Important: Si vous désirez enregistrer un patient suivant immédiatement, cliquez ici.
NL: Belangrijk: Indien u onmiddellijk een volgende patiënt wenst te registreren, klik dan hier.

**Comment by neuronick** [comment]
The text is added.

**Comment by helene-ameels** [comment]
Link (in ACC) provided to client on 14/07/2020 for UAT
