### ISSUE TITLE
Access Right - Lime Survey

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#322]
Access right that need to be implemented for the access to the Lime Survey.

**Comment by helene-ameels** [comment]
Hélène to first check with client how it is done for the moment in order we do it the same way.
Email sent to Dominique on 24/06/2020 - waiting feed-back

Feed-back client 25/06/2020: there is only one token for all responders. Nobody from outside has access to the limesurvey server (neither the structure nor the answers)

Question to client (25/06/2020) - is it possible to provide us with this token so we implement it.
(Other possibilities is that we generate one but in that case, it will required that they communicate this new token to hospitals (which is something they probably want to avoid))

To be continued...

**Comment by helene-ameels** [comment]
@neuronick  - Here are the information re. the Access right for the 3 lime surveys:
 Only one token for all responders --> Token: CfMJdjpV

**Comment by neuronick** [comment]
Token authorization is setup.
