### ISSUE TITLE
Non-contact complaint for a positive patient

### ISSUE THREAD

**Issue by nathanmartinsolidaris** [Sciensano-Healthdata/HD-Corona#324]
A doctor complains that his patient (with a postive test) was not contacted by the call center. We want to check (on the basis of the NISS) if the patient has been on the call list or not (script 1A).

Can you carry out this research over the period from June 15 to June 25? 

The request is for Wallonia 
NISS : 45 12 162 8570

Thank you in advance

**Comment by VrankenKris** [comment]
In the data we see the following as a testresult
![image.png](https://images.zenhubusercontent.com/5bfe323082265008a04d6831/0d86f0cf-d399-4cf8-b688-e5302812aaa9)

So no positive test
