### ISSUE TITLE
Feed-back UAT Client - Admission (1) - Introduction page

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#330]
###  1. Update the following text:

FR: Version 5 du questionnaire, 08/06/2020. Modifications par rapport à la version précédente:
- Ajout d'une question sur ethnie, logement collectif, raison du test, causes d'immunosuppression et type de cancer.
- Ajout de questions spécifiques pour les patients de moins de 18 ans à la demande du groupe de surveillance pédiatrique COVID-19. Ces questions n'apparaissent que pour les patients pédiatriques.

NL: Versie 5 van de vragenlijst, 08/06/2020. Wijzigingen ten opzichte van de vorige versie:
- Toevoeging van vragen over etniciteit, residentiêle collectiviteit, reden van de test, oorzaken van immunodepressie en type kanker.
- Op vraag van de pediatrische COVID-19 surveillancegroep, toevoeging van specifieke vragen voor patiënten jonger dans 18 jaar. Deze vragen verschijnen alleen voor pediatrische patiënten.

With:

FR: Version 6 du questionnaire, **dd/mm/yyyy** _(to be completed with PROD date, once put in PROD)_. Modifications par rapport à la version précédente:
- Ajout du rapportage du NISS – numéro d’identification à la sécurité sociale belge
- Ajout de possibilités de réponses pour la variable hébèrgement collectif : « autre collectivité résidentielle » et « institution pour personnes handicapées »

NL: version not provided by client  --> Suggestion (by Hélène):

Versie 6 van de vragenlijst, dd/mm/yyyy [date to be completed with PROD date, once put in PROD]. Wijzigingen ten opzichte van de vorige versie:

- **Toevoeging van het INSZ- Belgisch identificatienummer van de sociale zekerheid**
- Toevoeging van reactiemogelijkheden voor de collectieve woonvariabele: 'andere woongemeenschap voor ouderen (assistentiewoning, seniorie, service flat)' en 'instelling voor personen met een handicap'.

###  2. Update the following text (FYI deliberation number not yet available) --> not possible yet (on hold)

FR: Ce traitement de données est autorisée par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (délibération 17-065-f130-COVID-19). Ce traitement de données a également été approuvé par le Comité d'éthique de l'UZ Gent (dossier BC-07507).

NL: Voor de gegevensverwerking werd een machtiging verkregen van de Kamer Social Zekerheid en Gezondheid van het Informatieveiligheidscomité (beraadslaging 17-065-n130-COVID-19). Deze gegevenswerwerking werd eveneens goedgekeurd door het Ethisch Comité van UZ Gent (dossier BC-07507).

with:
FR: Ce traitement de données est autorisée par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (délibération xxxx[**to be provided once known**]). Ce traitement de données a également été approuvé par le Comité d'éthique de l'UZ Gent (dossier BC-07507).

NL: Voor de gegevensverwerking werd een machtiging verkregen van de Kamer Social Zekerheid en Gezondheid van het Informatieveiligheidscomité (beraadslaging xxxx [**to be provided once known**]). Deze gegevenswerwerking werd eveneens goedgekeurd door het Ethisch Comité van UZ Gent (dossier BC-07507).

**Comment by neuronick** [comment]
The first part is updated.

**Comment by neuronick** [comment]
The NL text fix is done.

**Comment by helene-ameels** [comment]
**Part 1:**
FR/NL - still to update with date of PROD (once known)

**Part 2**
FR/NL: ok - still to update with the reference number of the ISC-SSH deliberation once known

**Comment by neuronick** [comment]
Updated. If the date changes after 01/09/2020 we will need to update it once more.
