### ISSUE TITLE
Feed-back UAT Client - Discharge (1): Intro page

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#331]
### 
- [x] 1. Update the following text:

FR: Version 2. 08/06/2020
- Ajout d’une question sur : oxygénothérapie et support ventilatoire non invasif, les complications,
les causes de décès (COVID-19 comme cause initiale ou non), résultat de sérologie, date de sortie USI et statut vital à la sortie de l’USI
- Suppression des questions sur : pays de résidence, certaines valeurs de laboratoire
- Restructuration des questions sur les traitements spécifiques COVID-19
- Ajout de questions spécifiques pour les patients de moins de 18 ans à la demande du groupe de surveillance pédiatrique COVID-19

NL: Versie 2. 08/06/2020
- Toegevoegde vragen: zuurstoftherapie en niet-invasieve beademingsondersteuning, complicaties, doodsoorzaken (COVID-19 als eerste oorzaak of niet)), serologisch resultaat, datum ontslag uit IC en vitale status bij het verlaten IC
- Weggelaten vragen: land van woonplaats, bepaalde labo waarden
- Herstructurering van vragen betreffende specifieke COVID-19 behandelingen
- Op vraag van de pediatrische COVID-19 surveillancegroep, toevoeging van specifieke vragen voor patiënten jonger dan 18 jaar

With:

FR: Version 3 du questionnaire, **dd/mm/yyyy** _(to be completed with PROD date, once put in PROD)_. Modifications par rapport à la version précédente:
- Ajout du rapportage du NISS – numéro d’identification à la sécurité sociale belge
- Création d’un questionnaire USI distinct dans lequel les questions USI ont été transférées

NL: version not provided by client  (suggestion by Hélène):

Versie 3 van de vragenlijst, **dd/mm/yyyy** [_date to be completed with PROD date, once put in PROD]_. Wijzigingen ten opzichte van de vorige versie:
**- Toevoeging van het INSZ - Belgisch identificatienummer van de sociale zekerheid**
- Creëren van een afzonderlijke USI-vragenlijst waarin de USI-vragen zijn overgebracht

### - [ ] 2. Update the following text: - not possible yet (on hold) as number of deliberation not available yet

FR: Ce traitement de données est autorisée par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (délibération 17-065-f130-COVID-19 ; ). Ce traitement de données a également été approuvé par le Comité d'éthique de l'UZ Gent (dossier BC-07507).

NL: Voor de gegevensverwerking werd een machtiging verkregen van de Kamer Sociale Zekerheid en Gezondheid van het Informatieveiligheidscomité. Deze gegevensverwerking werd eveneens goedgekeurd door het Ethisch Comité van UZ Gent (dossier BC-07507). 

with:
FR: Ce traitement de données est autorisée par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (délibération **[to be provided once known]** ). Ce traitement de données a également été approuvé par le Comité d'éthique de l'UZ Gent (dossier BC-07507).

NL: Voor de gegevensverwerking werd een machtiging verkregen van de Kamer Social Zekerheid en Gezondheid van het Informatieveiligheidscomité (beraadslaging [**to be provided once known**]). Deze gegevenswerwerking werd eveneens goedgekeurd door het Ethisch Comité van UZ Gent (dossier BC-07507).

**Comment by neuronick** [comment]
Texts updated. Waiting for the delibiration date.

**Comment by helene-ameels** [comment]
Part 1:
FR: OK
NL: Small update required (see sentence in bold above) - @neuronick
FR/NL - still to update with date of PROD (once known)

Part 2
FR/NL: ok - still to update with the reference number of the ISC-SSH deliberation once known

**Comment by neuronick** [comment]
The NL text fix is done.

**Comment by helene-ameels** [comment]
**Part 1:**
FR/NL - still to update with date of PROD (once known)
**Part 2:**
FR/NL: still to update with the reference number of the ISC-SSH deliberation once known

**Comment by neuronick** [comment]
Updated. If the date changes after 01/09/2020 we will need to update it once more.
