### ISSUE TITLE
Feed-back UAT Client - ICU (1) : Intro page

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#332]
### - Update the following text
FR: Ce traitement de données est autorisée par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (délibération 17-065-f130-COVID-19 ; ). Ce traitement de données a également été approuvé par le Comité d'éthique de l'UZ Gent (dossier BC-07507).

NL: Voor de gegevensverwerking werd een machtiging verkregen van de Kamer Sociale Zekerheid en Gezondheid van het Informatieveiligheidscomité. Deze gegevensverwerking werd eveneens goedgekeurd door het Ethisch Comité van UZ Gent (dossier BC-07507).

### With
FR: Ce traitement de données est autorisée par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (délibération [**to be updated once known]** ). Ce traitement de données a également été approuvé par le Comité d'éthique de l'UZ Gent (dossier BC-07507).

NL: Voor de gegevensverwerking werd een machtiging verkregen van de Kamer Sociale Zekerheid en Gezondheid van het Informatieveiligheidscomité (beraadslaging **[to be updated once known]**. Deze gegevensverwerking werd eveneens goedgekeurd door het Ethisch Comité van UZ Gent (dossier BC-07507).

**Comment by helene-ameels** [comment]
@neuronick  - there is also this change for ICU - I've assigned it to you in case you already want to prepare like you did for the 2 other LS (while waiting for the reference number from ISC-SSH)

**Comment by neuronick** [comment]
Done. Waiting fo the deliberation number.

**Comment by neuronick** [comment]
Updated. If the date changes after 01/09/2020 we will need to update it once more.
