### ISSUE TITLE
Feed-back UAT Client - Admission (2) - section 1

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#333]
### 1. For question 'NISS/INSZ',

- [x] update label of the question into 
FR: 'NISS – numéro d’identification à la sécurité sociale belge (NISS)'
NL: 'INSZ - Identificatienummer van de sociale zekerheid in België (INSZ)'

- [x] Add in the help text 
FR: 'N’encodez que les chiffres et non les points, espaces ou tirets'
NL: 'Codeer alleen de cijfers en niet de punten, spaties of streepjes'

- Questions from researchers:

- [x] Is it possible to have a check with inclusion of 11 digits?
- Is it possible to put this field as mandatory with an option 'not available'?
- [x] Another option is to put the field mandatory with an help text: 'If NISS not available, indicate - '00000000000'
(FR: Si NISS non disponible, indiquez 0 / NL: (not received)

- Is it possible to have the date of birth pre-filled based on NISS?
Dominique colleague (Kim)  has expertise in this, can be contacted if needed.

### 2. Modification requires:

- [x] When Indiquez s’il s’agit d’une réadmission  d’un patient précédemment hospitalisé pour COVID-19 = 'OUI', question 'Le patient était-il hospitalisé dans le même hôpital ?' should appear below (and not above)

- [x] When 'le patient était-il hospitalisé dans le même hôpital ?' = NO, the order of the question has to be modified: 'De quel hôpital le patient était-il sorti ?' » has to be before 'A quelle date le patient était-il sorti de cet hôpital ? '

- [x] For question 'le patient réside-t-il dans un logement collectif ?:

- use 'hébergement' instead of 'logement' --> le patient réside-t-il dans un hébergement collectif?
- remove capital letter after 'Oui,... for 
- Oui, Autre collectivité résidentielle pour personnes âgées (Résidence-services, seigneurie, …) 
- Oui, Institution pour personnes handicapées'  
--> Oui, autre collectivité résidentielle pour personnes âgées (Résidence-services, seigneurie, …) 
--> Oui, institution pour personnes handicapées

- Move answer 'Oui, autre hébergement collectif' just before 'Inconnu'

- [x] For question 'Motif du test': change in order only one answer possible 

- [x] **TO CHECK WITH NIKITA:** client is asking to have the question 'nombre de personnes vivant dans le même ménage' placed before 'cas index....' --> I cannot find the question the client is speaking about, is it appearing only in specific condition??

**Comment by neuronick** [comment]
The changes are implemented on ACC (Except for birthdate prefill based on NISS, which is split into a separate issue: #340)

**Comment by neuronick** [comment]
The NL correction is preformed.

Regarding ('nombre de personnes vivant dans le même ménage'), in order to test:
1) Fill in the '**date de naissance**', so the age is less than 18 years old (e.g. 01-01-2015). 
2) Select '**Non**' in '**Indiquez s’il s’agit d’une réadmission  d’un patient précédemment hospitalisé pour COVID-19**'
3) Then '**Nombre de personnes vivant dans le même ménage que le patient ?**' should appear.

**Comment by helene-ameels** [comment]
ok - everything in order --> Done
