### ISSUE TITLE
Feed-back UAT Client - Admission (3) - section 2

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#334]
Client informed that a question on the pregnancy trimester should appear when 'Grossesse' is ticked for question 'Conditions médicales sous-jacentes, comorbidités et facteurs de risque' - can you please check?

**Comment by neuronick** [comment]
Should be working

**Comment by neuronick** [comment]
It is automatic in Limesurvey. Because the questions is not set as 'mandatory'

**Comment by helene-ameels** [comment]
ok - so we leave it like that --> Done
