### ISSUE TITLE
Feed-back UAT client - ICU (2)

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#335]
- [x] the question NISS has to be moved after question 'Numéro de dossier hospitalier du patient' (in order to be consistant with the order in the 2 other lime surveys)

### '+ Implement for NISS same changes asked for admission (cfr. # 333): 

- [x] update label of the question into 
FR: 'NISS – numéro d’identification à la sécurité sociale belge (NISS)'
NL: 'INSZ - Identificatienummer van de sociale zekerheid in België (INSZ)'

- [x] Add in the help text 
FR: 'N’encodez que les chiffres et non les points, espaces ou tirets'
NL: 'Codeer alleen de cijfers en niet de punten, spaties of streepjes'

- Questions from researchers:

- [x] Is it possible to have a check with inclusion of 11 digits?

- Is it possible to put this field as mandatory with an option 'not available'?
- [x] Another option is to put the field mandatory with an help text: 'If NISS not available, indicate '00000000000'
(FR: Si NISS non disponible, indiquez 0 / NL: (not received)

- Is it possible to have the date of birth pre-filled based on NISS?
Dominique colleague (Kim)  has expertise in this, can be contacted if needed.

**Comment by neuronick** [comment]
Changes are implemented. The prefill is split into a separate ticket: #340.
