### ISSUE TITLE
Feed-back UAT Client - Discharge (2)

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#337]
Implement for NISS same changes asked for admission (cfr. # 333)

- [x] update label of the question into 
FR: 'NISS – numéro d’identification à la sécurité sociale belge (NISS)'
NL: 'INSZ - Identificatienummer van de sociale zekerheid in België (INSZ)'

- [x] Add in the help text 
FR: 'N’encodez que les chiffres et non les points, espaces ou tirets'
NL: 'Codeer alleen de cijfers en niet de punten, spaties of streepjes'

- Questions from researchers:

- [x] Is it possible to have a check with inclusion of 11 digits?

Is it possible to put this field as mandatory with an option 'not available'?
- [x] Another option is to put the field mandatory with an help text: 'If NISS not available, indicate '00000000000'
(FR: Si NISS non disponible, indiquez 0 / NL: (not received)

- Is it possible to have the date of birth pre-filled based on NISS?
Dominique colleague (Kim)  has expertise in this, can be contacted if needed.

**Comment by neuronick** [comment]
Changes implemented. Prefill is split into separate ticket # #340
