### ISSUE TITLE
TRIAL FR: TYPO: change "d'infirmièresv" into "d'infirmières" (no v at the end)

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#34]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/163354ee-56df-4d1f-a76b-4bfb87771b20)

TYPO: change "d'infirmièresv" into "d'infirmières" (no v at the end)

**Comment by neuronick** [comment]
done
