### ISSUE TITLE
CRA FR: Translate to french landingpage COVID19 Barometer CRA

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#36]
Please translate following text  **BEFORE 12h00, MONDAY 23.03.2020**
===========================================
"Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerend en raadgevend artsen, triageposten en apothekers) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden. De monitoring bij de coördinerend en raadgevend artsen gebeurt elke dag, ongeveer om 18u00.

Voor de coördinerend en raadgevend artsen werd deze barometer opgemaakt door het Academisch Centrum voor Huisartsgeneeskunde (Prof. Jan De Lepeleir) van de KULeuven.
Deze barometer wordt gesteund door de volgende organisaties: **, ** en ****.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, de COVID19 Risk Management Groep, en de Nationale Crisiscel.
Op basis van de gegevens die u registreert, ontvangt u gepersonaliseerde feedback verzorgd door Doclr.

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Uw e-mailadres wordt enkel gebruikt om de samenvatting van de resultaten naar u op te sturen en om de follow-up monitoring aan te kondigen. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig, kan steeds kan onderbroken worden, en alle gegevens zullen anoniem verwerkt worden.

Voor inhoudelijke vragen bij deze gegevensverzameling: emailadres
Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

Start met de barometer registratie.
===========================================

if translated, please inform Jonathan and Nikita

**Comment by helene-ameels** [comment]
Durant cette pandémie de COVID-19, le projet national de surveillance" Baromètre COVID-19 "a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et conseils, les postes de triage et les pharmaciens) et, si nécessaire, apporter une aide via feed-back Le suivi par les médecins coordinateurs et conseils a lieu tous les jours, vers 18h.

Ce baromètre a été établi pour les médecins coordinateurs et conseils par le Centre Académique de Médecine Générale (Prof. Jan De Lepeleir) de la KULeuven. Ce baromètre est soutenu par les organisations suivantes: **, ** et ****.

Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’.
Sur la base des données que vous enregistrez, vous recevrez un feed-back personnalisé de Doclr.

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).

Votre adresse e-mail ne sera utilisée que pour vous envoyer le résumé des résultats et pour annoncer le suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire, peut être interrompu à tout moment et toutes les données seront traitées de manière anonyme.

Pour des questions de fond sur cette collecte de données: adresse e-mail
Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be 

Commencez avec l'enregistrement du baromètre.
