### ISSUE TITLE
Simplification of the forms Admission and Discharge acc. to client feed-back

### ISSUE THREAD

**Issue by helene-ameels** [Sciensano-Healthdata/HD-Corona#360]
Files specs:
https://www.dropbox.com/scl/fi/skbc6nj6s53qmqp37ydyz/LIME_file_specifications.xlsx?dl=0&rlkey=b3y2r3utkaoh6bgpybmv9ag38

**Comment by neuronick** [comment]
Changes for Admission / Discharge are implemented as requested.

**Comment by helene-ameels** [comment]
Retested on 21/08: admission + discharge OK --> ready for review by client

**Comment by helene-ameels** [comment]
Feed-back on discharge: https://www.dropbox.com/s/8lojhk0u24q4xhu/Comments_LS_Discharge_HD_20200824.msg?dl=0
