### ISSUE TITLE
Feedback client Admission

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#363]
https://www.dropbox.com/scl/fi/iyg0vbvjjfcmggg9dvwpf/Comments_LS_admission_HD_24_august.docx?dl=0&rlkey=ryr1s1h231vzah4e509f9znja

**Comment by neuronick** [comment]
All changes described are implemented on ACC.

**Comment by helene-ameels** [comment]
Cover in ticket #360  --> Done/Closed
