### ISSUE TITLE
Create "Daily status form for general practitioners"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#4]

**Comment by JohanvanBussel** [comment]
Form that will be completed on daily basis

Dutch and french have own version of form:
- "Dagelijkse status formulier voor huisartsen" (NL)
- "Formulaire de statut quotidien pour les médecins généralistes" (FR)

Doc:
- covid19-pdf-nl (is dictionary of iform for GP’s, NL, as implemented in GP software)[https://app.zenhub.com/files/248791371/7af44810-2f44-4302-b109-ae12d6c3a2fe/download](https://app.zenhub.com/files/248791371/7af44810-2f44-4302-b109-ae12d6c3a2fe/download)

- covid19-pdf-fr (is dictionary van iform for GP’s, FR, as implemented in GP software)[https://app.zenhub.com/files/248791371/9b6de461-3124-4ac2-95d8-2462665866e9/download](https://app.zenhub.com/files/248791371/9b6de461-3124-4ac2-95d8-2462665866e9/download)

- covid19-nl ( is screenshot of iform for GP’s, NL, as implemented in GP software)[https://app.zenhub.com/files/248791371/88c31ece-e9a4-4a7c-a0dd-dbbf12abffb9/download](https://app.zenhub.com/files/248791371/88c31ece-e9a4-4a7c-a0dd-dbbf12abffb9/download)

- covid19-fr ( is screenshot of iform for GP’s, FR, as implemented in GP software)[https://app.zenhub.com/files/248791371/9db01192-5f8a-422d-9ce2-668f59a90fb3/download](https://app.zenhub.com/files/248791371/9db01192-5f8a-422d-9ce2-668f59a90fb3/download)

**Comment by neuronick** [comment]
Here is the  first draft of the form:
https://hd4patient-acc.healthdata.be/nl/covid19/general_practitioners/status

**Comment by JohanvanBussel** [comment]
Thnx Nikita,

Graag aanpassen van schaal naar hoe het in google form gevraagd wordt.

[cid:image003.png@01D5FF66.1A489890]

----------------------------------------------------------------------------------------------------
Johan van Bussel
Head of service
Healthdata.be
M + 32 485 85 16 97
Skype johan.vanbussel@sciensano.be
[cid:image001.jpg@01D54DCF.B4D16B10]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

**Comment by neuronick** [comment]
The following technical names were used:

- tx_gp_name
- tx_email
- tx_gp_postal_code
- nr_num_gp_providers
- nr_num_gp_providers_absent
- fl_critical_tasks_completed
- tx_critical_tasks_comments
- fl_quality_standard
- tx_quality_comments
- fl_help_needed
- tx_help_needed_comments
- fl_capacity_next_day
- tx_capacity_next_day_comments
- fl_capacity_next_week
- tx_capacity_next_week_comments
- nr_num_consultations_phone
- nr_num_consultations_phys
- nr_num_patients_triage
- nr_num_patients_emergency
- nr_num_respiratory_conusltations
- cd_extra_load
- cd_alc_hand_disinfectant
- cd_surgical_masks
- cd_infection_masks
- cd_infection_gloves
- cd_infection_aprons
- cd_infection_screen

**Comment by JohanvanBussel** [comment]
Thnx Nikita ! Can you include the technical names also in the excel sheet data dictionary? Thnx in advance, Johan

----------------------------------------------------------------------------------------------------
Johan van Bussel
Head of service
Healthdata.be
M + 32 485 85 16 97
Skype johan.vanbussel@sciensano.be
[cid:image001.jpg@01D54DCF.B4D16B10]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

**Comment by neuronick** [comment]
Multistep functionality is added. Scale widget changed.

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/b69b1355-2867-4386-b86f-6f4f43cc61ef)

The **correct sequence is always**:
- Groot tekort
- Klein tekort
- Klein overschot
- Groot overschot

**This should be corrected everywere in the form!**

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/89ff6b25-6d62-4308-a5d1-0dde101c6ff9)

**1 radio button is missing and the correct sequence is always:**
- Abaissé
- Normal
- Augmenté
- Fortement augmenté
- Intensément élevé

in dutch version:
- Verlaagd
- Normaal
- Verhoogd
- Sterk verhoogd
- Onhoudbaar hoog

**Comment by JohanvanBussel** [comment]
Bij de **sectie « besmettingen »** , the **intro**
-  « Met deze vragen proberen we de stijging van besmettingen te monitoren” … 
- change into: 
--“Met deze vragen proberen we de evolutie van besmettingen te monitoren”
-- french: Avec ces questions, nous essayons de surveiller l'evolution des infections.

**Comment by maerckaert** [comment]
Done!
