### ISSUE TITLE
CRA FR + NL: delete "Rusthuis" / "Maison de repos" and rename "Centres de soins résidentiels"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#40]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/47cea881-bb24-4046-a498-2e90161c5463)

![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/dc63de42-7007-4fe0-961a-d88b771e55ea)

In NL: delete radiobutton "Rusthuis" / 
In FR: delete radiobutton "Maison de repos" 
In FR: rename radiobutton "Centres de soins résidentiels" into "'Maison de repos et de soins"

**Comment by neuronick** [comment]
change is done
