### ISSUE TITLE
Setup SFTP account for doclr

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#42]

**Comment by QuesadaJuan** [comment]
Send request for sFTP account to DC team. 
Content was: 
We need very urgent an sFTP account on the non-NGS SFTP server for COVID19 project. 

-	One account with name “doclr” and folder “doclr”
o	Only “read” and “delete” rights (no write and update rights)
-	Our “wiv” account needs full access to this folder (but I think that this is automatically the case?)

**Comment by QuesadaJuan** [comment]
We have a small change: 
-	The “doclr” account needs also “write” right

And we need an extra sFTP account: 

-	One account with name “kris.doggen” needs access to the folder “doclr”, so the folder of the user “doclr”.  
o	Only “read” rights for this user

**Comment by QuesadaJuan** [comment]
And another change…
Kris.doggen will have to get his own folder…

**Comment by QuesadaJuan** [comment]
To be clear: Kris Doggen needs only access to his own folder, not anymore to the “doclr” folder.

**Comment by QuesadaJuan** [comment]
Within the folder “doclr” the folder “upload” should be removed and replaced by 2 new folders:
-	“raw”
-	“clean”

**Comment by QuesadaJuan** [comment]
The sFTP accounts have been created.

**Comment by QuesadaJuan** [comment]
User “wiv” should be able to write file in the “doclr” and “krisdoggen” folder. 
Can you adjust this?
