### ISSUE TITLE
Create DB2 table key-values

### ISSUE THREAD

**Issue by VrankenKris** [Sciensano-Healthdata/HD-Corona#46]

**Comment by QuesadaJuan** [comment]
Created the following tables in ACC and PROD: 

OPER.T_DOCUMENT_COVID19
OPER.T_DOC_KEY_VALUE_COVID19

The tables are a copy of the OPER.T_DOCUMENT and OPER.T_DOC_KEY_VALUE tables, so same columns etc. 
Tables can be accessed with the same users that access the original tables.
