### ISSUE TITLE
MAIN page COVID19 barometer: small layout adjustments

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#51]
- position the buttons to the different sub projects lower. centralize in screen. 

- the higth of the  buttons should be the same … providing some margin for the text

- for the button “coordinerend en raadgevende artsen” I suggest:
-- NL:  to have on 1st line “coördinerend en” and on the second line “raadgevende artsen” 
-- FR: to have on 1st line “médecins coordinateurs"  and on the second line "et consultatifs"

**Comment by maerckaert** [comment]
I don't have easy solution for the text on second line.
But the rest is implemented.
