### ISSUE TITLE
Add DWH REST handlers to all the forms

### ISSUE THREAD

**Issue by neuronick** [Sciensano-Healthdata/HD-Corona#52]
URL pattern: http://10.72.128.65:9090/generic/<webform_id>

- [x] hd_covid_cra_status: http://10.72.128.65:9090/generic/hd_covid_cra_status
- [x] hd_covid_pharmacist_status: http://10.72.128.65:9090/generic/hd_covid_pharmacist_status
- [x] hd_covid_gp_status: http://10.72.128.65:9090/generic/hd_covid_gp_status
- [x] hd_covid_triage_status: http://10.72.128.65:9090/generic/hd_covid_triage_status
- [x] hd_covid_midwives_status: http://10.72.128.65:9090/generic/hd_covid_midwives_status

**Comment by neuronick** [comment]
Handlers added / configure and deployed

**Comment by neuronick** [comment]
Now all aforementioned forms can be tested for transfer to DWH

**Comment by VrankenKris** [comment]
Data that has been created is not arriving in the REST logs...

**Comment by VrankenKris** [comment]
Midwives is not yet done in production...
So back to in progress

**Comment by neuronick** [comment]
@VrankenKris @tommichiels 

**PROD:**
- [ ] Testing of data transfer still needs to be done on PROD for: hd_covid_midwives_status

**ACC:**
- [ ] Testing of data transfer hd_covid_cra_status
- [ ] Testing of data transfer hd_covid_pharmacist_status:
- [ ] Testing of data transfer hd_covid_pharmacist_status
- [ ] Testing of data transfer hd_covid_gp_status: 
- [ ] Testing of data transfer hd_covid_triage_status
- [ ] Testing of data transfer hd_covid_midwives_status

**Comment by VrankenKris** [comment]
@neuronick I cannot find the midwives data entry page in acc or prod

**Comment by VrankenKris** [comment]
@neuronick Apothekers in frans:Unable to process this submission. Please contact the site administrator. in acceptatie

**Comment by VrankenKris** [comment]
I am still unable to save data in acceptance...

**Comment by neuronick** [comment]
@tommichiels 
I am getting the following errors in log on ACC:

- http://10.72.128.65:9090/generic/hd_covid_gp_status failed. cURL error 28: Connection timed out after 30001 milliseconds
- http://10.72.128.65:9090/generic/hd_covid_pharmacist_status failed. cURL error 28: Connection timed out after 30001 milliseconds
- http://10.72.128.65:9090/generic/hd_covid_midwives_status failed. cURL error 28: Connection timed out after 30001 milliseconds

**Comment by tommichiels** [comment]
@neuronick  The url is not correct it is 129 instead of 128.

**Comment by maerckaert** [comment]
I've just modified the url's.

**Comment by VrankenKris** [comment]
@neuronick THis is working now in acceptance, because I was able to save records. Why is this not moved to another pipeline?
