### ISSUE TITLE
Create "Daily status form for CRA"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#6]

**Comment by JohanvanBussel** [comment]
Form that will be completed on daily basis
Geen user acces nodig

Dutch and french have own version of form:
- "Dagelijkse status formulier voor Coordinerende en Raadgevende Artsen" (NL)
- "Formulaire de statut quotidien pour les Médecin coordinateur et conseiller" (FR)

Doc:
- https://docs.google.com/forms/d/e/1FAIpQLSeUPqfycPM218FRMrx7eqYhktGq_jp-_AUQwzAnyfc1CCSoZg/viewform

**Comment by neuronick** [comment]
Form draft can be found here:
https://hd4patient-acc.healthdata.be/covid19/coordinating_physicians/status

Registration form is integrated into the first step.

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/b69b1355-2867-4386-b86f-6f4f43cc61ef)

The **correct sequence is always**:
- Groot tekort
- Klein tekort
- Klein overschot
- Groot overschot

**This should be corrected everywere in the form!**
see:
- Alcoholische handontsmetting
- Gewone chirurgische maskers
- Maskers geschikt te gebruiken bij infecties (FFP2 en co)
- Handschoenen geschikt te gebruiken bij infecties
- Schorten geschikt te gebruiken bij infecties
- Bril/scherm geschikt te gebruiken bij infecties

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/2563e87c-9ff5-4d1c-948d-9daad617767f)

"Submit" vervangen door "**verzenden**"

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/3ff57c63-72da-4302-b6e3-1107665cddd7)

to do: vertalen naar **nederlands**: 
- "New submission added to"
- "Back to form"

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/f2647d79-0b9e-4dda-8f60-d528f554ebc4)

vertalen naar nederlands:
- Voor CRA: aantal artsen, verpleegkundigen & zorgkundigen

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/32155a98-724b-426b-9a39-2226e8c1c3ad)

Vertaling naar frans nodig*:
- Zijn er reeds bewoners met corona in uw rust- en verzorgingstehuis (RVT)? 
- Hoeveel bewezen en klinisch verdachte bewoners samen?

vertaling aangevraagd bij Bert Vaes (22.03.2020, 7u23)

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/97f04987-f5ca-4978-a892-0ee2cc7ee34e)

vertaling naar frans nodig voor:
- New submission added to 
- Dagelijkse status formulier voor Coordinerende en Raadgevende Artsen

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/76096024-0d50-4ef5-ad85-d0f8f67da521)

I think that **size of letter** of "E-mailadres" and "Welke leeftijd heeft u?" is **smaller** than "Geslacht" ...

**Comment by JohanvanBussel** [comment]
Bij de **sectie « besmettingen »** , the **intro**
-  « Met deze vragen proberen we de stijging van besmettingen te monitoren” … 
- change into: 
--“Met deze vragen proberen we de evolutie van besmettingen te monitoren”
-- french: Avec ces questions, nous essayons de surveiller l'evolution des infections.

**Comment by JohanvanBussel** [comment]
Bij de **sectie « besmettingen »** , the **intro**
-  « Met deze vragen proberen we de stijging van besmettingen te monitoren” … 
- change into: 
--“Met deze vragen proberen we de evolutie van besmettingen te monitoren”
-- french: Avec ces questions, nous essayons de surveiller l'evolution des infections.

**Comment by maerckaert** [comment]
For this comment: https://github.com/Sciensano-Healthdata/HD-Corona/issues/6#issuecomment-602154711

I checked and the font size and font family are the same. I don't see differences.

The rest is done!
