### ISSUE TITLE
Midwives FR + NL : Create landing page 

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#64]

**Comment by neuronick** [comment]
Could you provide the necessary text? (NL /  FR)

**Comment by JohanvanBussel** [comment]
NL: 

Tijdens deze COVID-19 pandemie werd een landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerend en raadgevend artsen, triageposten, apothekers, en vroedvrouwen) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden. De monitoring van het vroedvrouwenkorps gebeurt twee maal per week, op woensdag en zaterdagavond. Indien u in een groepspraktijk werk, dient de vragenlijst enkel beantwoord te worden door de verantwoordelijke. Indien u zelfstandig werkt, dient u de vragenlijst zelf in te vullen

Voor de vroedvrouwenwerd deze barometer opgemaakt door de Dienst toegepaste farmacologie & farmacotherapie, farmaceutische zorg (Prof. Eline Tommelein) van de Vrije Universiteit Brussel.

Deze barometer wordt gesteund door de volgende organisaties: Vlaamse Beroepsorganisatie van Vroedvrouwen.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en Nationale Crisiscel.

Op basis van de gegevens die u registreert, ontvangt u gepersonaliseerde feedback verzorgd door Doclr.

De nieuwe Europese Algemene Verordening omtrent Gegevensbescherming (AVG), die sinds 25 mei 2018 van kracht is, legt bijkomende vereisten op over hoe bedrijven of organisaties uw persoonsgegevens mogen gebruiken. Een van die vereisten is dat de verantwoordelijke voor de verwerking u onderstaande informatie bezorgt.

Zoals reeds aangegeven worden in het kader van het onderzoek waar u aan deelneemt, persoonsgegevens van u verzameld. Wij, Sciensano en de Vrije Universiteit Brussel, zijn verantwoordelijk voor de correcte verwerking en de informatieplicht die daarmee gepaard gaat.

U heeft het recht om een klacht in te dienen over hoe uw informatie wordt behandeld. Dit kan u doen bij de Belgische toezichthoudende instantie die verantwoordelijk is voor het handhaven van de wetgeving rond gegevensbescherming:
Gegevensbeschermingsautoriteit (GBA)
Drukpersstraat 35,
1000 Brussel
Tel. +32 2 274 48 00
e-mail: contact@apd-gba.be
Website: www.gegevensbeschermingsautoriteit.be

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Uw e-mailadres wordt enkel gebruikt om de samenvatting van de resultaten naar u op te sturen en om de follow-up monitoring aan te kondigen. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig, kan steeds kan onderbroken worden, en alle gegevens zullen anoniem verwerkt worden.

Voor inhoudelijke vragen bij deze gegevensverzameling: Eline.Tommelein@vub.be

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

**Comment by JohanvanBussel** [comment]
FR: 
Chère sage-femme,

Durant cette pandémie de COVID-19, un projet national de surveillance "Baromètre COVID-19" a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et consultatifs, les postes de triage, les pharmaciens, et les sages-femmes) et, si nécessaire, apporter une aide via feed-back. Le suivi par le corps des sages-femmes se fait deux fois par semaine, le mercredi et le samedi soir. Si vous travaillez en groupe, le questionnaire ne doit être répondu que par le responsable. Si vous travaillez de manière indépendante, vous devez remplir le questionnaire vous-même.

Ce baromètre a été établi, pour les sages-femmes, par le Département de Pharmacologie Appliquée et Pharmacothérapie, Soins Pharmaceutiques (Prof. Eline Tommelein) de la ‘Vrije Universiteit Brussel’ (VUB).

Ce baromètre est soutenu par les organisations suivantes: Vlaamse Beroepsorganisatie van Vroedvrouwen.

Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’.

Sur la base des données que vous enregistrez, vous recevrez un feed-back personnalisé de Doclr.

Comme déjà indiqué, des données personnelles sont collectées auprès de vous dans le cadre des recherches auxquelles vous participez. Nous, Sciensano et la Vrije Universiteit Brussel, sommes responsables du traitement correct et de l'obligation de fournir des informations.

Vous avez le droit de vous plaindre du traitement de vos informations. Vous pouvez le faire avec l'autorité de surveillance belge chargée de faire respecter la législation sur la protection des données:
Autorité de protection des données (ADP)
Drukpersstraat 35,
1000 Bruxelles
Tél. +32 2 274 48 00
email: contact@apd-gba.be
Site Web: www.dataprotectionauthority.be

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).

Votre adresse e-mail ne sera utilisée que pour vous envoyer le résumé des résultats et pour annoncer un suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire, peut être interrompu à tout moment et toutes les données seront traitées de manière anonyme.

Pour des questions de fond sur cette collecte de données: Eline.Tommelein@vub.be

Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be

**Comment by JohanvanBussel** [comment]
NL: start landing page with:

Beste vroedkundige,
.............

**Comment by neuronick** [comment]
Changes made and deployed to ACC
