### ISSUE TITLE
Home nurses NL + FR: create landing page

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#65]

**Comment by JohanvanBussel** [comment]
Text NL

Beste thuisverpleegkundige,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerend en raadgevend artsen, triageposten, apothekers, vroedkundigen en thuisverpleegkundigen) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden. De monitoring van bij de thuisverpleegkundigen gebeurt tweemaal per week, op ***** en op ****, steeds rond 18u00.

Voor de thuisverpleegkundigen werd deze barometer opgemaakt door het ********** (****** ******) van *******.

Deze barometer wordt gesteund door de volgende organisaties:*******, *******, ******* en *******.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en Nationale Crisiscel.

Op basis van de gegevens die u registreert, ontvangt u gepersonaliseerde feedback verzorgd door Doclr.

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Uw e-mailadres wordt enkel gebruikt om de samenvatting van de resultaten naar u op te sturen en om de follow-up monitoring aan te kondigen. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig, kan steeds kan onderbroken worden, en alle gegevens zullen anoniem verwerkt worden.

Voor inhoudelijke vragen bij deze gegevensverzameling: *******.*******@*******.be

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

**Comment by JohanvanBussel** [comment]
text FR:

Cher / Chère infirmière à domicile,

Durant de cette pandémie de COVID-19, le projet national de surveillance" Baromètre COVID-19" a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et consultatifs, les postes de triage, les pharmaciens, les sages-femmes, et les infirmières à domicile) et, si nécessaire, apporter une aide via feed-back. Le suivi du corps des infirmières à domicile a lieu deux fois par semaine, ******* et *******, vers 18h00.

Ce baromètre a été établi, pour les infirmières à domicile, par le ******* (*******) de la *******.

Ce baromètre est soutenu par les organisations suivantes: *******, *******, ******* et *******.

Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’. Sur la base des données que vous enregistrez, vous recevrez un feed-back personnalisé de Doclr.

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).

Votre adresse e-mail ne sera utilisée que pour vous envoyer le résumé des résultats et pour annoncer le suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire, peut être interrompu à tout moment et toutes les données seront traitées de manière anonyme.

Pour des questions de fond sur cette collecte de données: *******.*******@*******.be

Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be

**Comment by neuronick** [comment]
Created and deployed to ACC:
https://covid19-acc.healthdata.be/nl/hn
https://covid19-acc.healthdata.be/fr/hn

**Comment by evelynedewitte** [comment]
Tekst NL:

@neuronick: please correct the very first phrase of the Dutch text as follows:

- coördinerend**e** en raadgevend**e** artsen
- en om zo nodig via feedback hulp aan te bieden (in plaats van: "en kan er zo nodig via de feedback hulp aangeboden worden")

@JohanvanBussel: wie kan ons helpen de ontbrekende tekst in te vullen?

**Comment by JohanvanBussel** [comment]
Tim weltens: Tim.Weltens@vlaanderen.wgk.be

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/14dd595f-ca4f-482d-8f63-9d264591853f)

- "Start met de barometer registratie" => "Start met de barometer registratie: Diensten voor thuisverpleging (loontrekkenden)"
- "Start met de barometer registratie" => "Start met de barometer registratie: Zelfstandige thuisverpleegkundigen"

**Comment by evelynedewitte** [comment]
Tekst NL:

Beste thuisverpleegkundige,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerend en raadgevend artsen, triageposten, apothekers, vroedkundigen en thuisverpleegkundigen) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden. De monitoring van bij de thuisverpleegkundigen gebeurt tweemaal per week, op maandag en op woensdag, tussen 15u en 22u.

Voor de thuisverpleegkundigen werd deze barometer opgemaakt door het Nederlandstalig Platform voor Thuisverpleegkundigen.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en Nationale Crisiscel.

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Uw e-mailadres wordt gebruikt om de samenvatting van de resultaten naar u op te sturen en om de follow-up monitoring aan te kondigen. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig, kan steeds kan onderbroken worden. Uw gegeven worden op dit moment gebruikt om het beleid te sturen en alle gegevens zullen in verder wetenschappelijke onderzoek anoniem verwerkt worden.

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

**Comment by evelynedewitte** [comment]
text FR:

Cher / Chère infirmière à domicile,

Durant de cette pandémie de COVID-19, le projet national de surveillance" Baromètre COVID-19" a été lancé pour suivre de près l'état des soins de première ligne (entre autres les médecins généralistes, les médecins coordinateurs et consultatifs, les postes de triage, les pharmaciens, les sages-femmes, et les infirmières à domicile) et, si nécessaire, apporter une aide via feed-back. Le suivi du corps des infirmières à domicile a lieu deux fois par semaine, le lundi et le mercredi, entre 15h et 22h.

Ce baromètre a été établi, pour les infirmières à domicile, par Inficonsor: Consortium Infirmier.

Ces données seront utilisées pour soutenir le ‘COVID19 Risk Assessment Group’, le ‘COVID19 Risk Management Group’ et la ‘National Crisis Cell’.

Cet enregistrement a été notifié, évalué et autorisé par la Chambre sécurité sociale et santé du Comité de sécurité de l'information (référence IVC / KSZG / 20/134).

Votre adresse e-mail ne sera utilisée que pour vous envoyer le résumé des résultats et pour annoncer le suivi. La saisie de l'adresse e-mail est considérée comme une acceptation de participation à ce questionnaire. Ce questionnaire est entièrement volontaire et peut être interrompu à tout moment. Vos données sont actuellement utilisées pour guider la politique et toutes les données seront traitées de manière anonyme dans les recherches scientifiques futures.

Pour des questions techniques sur cette collecte de données: support.healthdata@sciensano.be

**Comment by maerckaert** [comment]
I did the changes but I think it would be better: Chère infirmière, cher infirmier,

And for the buttons also

**Comment by evelynedewitte** [comment]
@maerckaert Yes, I agree with your last comment.

**Comment by evelynedewitte** [comment]
@maerckaert 

Let me know when I can review

**Comment by neuronick** [comment]
First line is changed on ACC:
https://covid19-acc.healthdata.be/fr/hn

As agreed on skype with @evelynedewitte, for the button's text we will wait for feedback from the researches.

**Comment by evelynedewitte** [comment]
@neuronick 

Change requested on landing page:

Zin nu:

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen en thuisverpleegkundigen) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden.

REPLACE WITH

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen en thuisverpleegkundigen) van nabij te volgen en knelpunten in de eerste lijn vroeger te detecteren en om gerichte oplossingen te kunnen bieden.

**Comment by evelynedewitte** [comment]
Op het eind zou het leuk zijn als er een ‘Bedankt!’ wordt getoond + herhaling van wanneer de vragenlijsten moeten ingevuld worden: De monitoring van bij de thuisverpleegkundigen gebeurt tweemaal per week, op maandag en op woensdag, tussen 15u en 22u.

**Comment by neuronick** [comment]
Could you provide me with the FR version of the "De monitoring van bij de thuisverpleegkundigen gebeurt tweemaal per week, op maandag en op woensdag, tussen 15u en 22u."?

**Comment by evelynedewitte** [comment]
@neuronick 

I just put it in Google Translate and it actually came out quite well: 

Les infirmières à domicile sont suivies deux fois par semaine, les lundis et mercredis, de 15h à 22h.

**Comment by evelynedewitte** [comment]
Assigned back to me as I am waiting for confirmation from Kristel & Tim.

**Comment by evelynedewitte** [comment]
@neuronick 

Just received the final (I hope) text for the **NL landing page**:

Beste thuisverpleegkundige,
 
Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (o.a. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen en thuisverpleegkundigen) van nabij te volgen en zo knelpunten in de eerste lijn vroeger te detecteren en sneller gericht oplossingen te kunnen aanbieden. 

Deze monitoring werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134). Concreet worden de gegevens gebruikt ter ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en de Nationale Crisiscel in de sturing van het beleid.
 
Voor de thuisverpleegkundigen werd deze barometer opgemaakt door het Nederlandstalig Platform voor Thuisverpleegkundigen (NPTV) en zal de monitoring tweemaal per week gebeuren, op maandag en op woensdag, tussen 15u en 22u.

Er zijn 2 verschillende vragenlijsten: 1 voor diensten voor thuisverpleging (loontrekkenden) en 1 voor zelfstandige thuisverpleegkundigen. Gelieve de juiste vragenlijst in te vullen.
 
Uw e-mailadres wordt gebruikt om de follow-up monitoring aan te kondigen en om de samenvatting van de resultaten naar u op te sturen. Alle gegevens zullen in verder wetenschappelijk onderzoek anoniem verwerkt worden. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst, die geheel vrijwillig is en op elk moment kan worden onderbroken.
 
Mogen wij u vragen deze korte vragenlijst op maandag & woensdag in te vullen tussen 15h en 22h?
 
Alvast hartelijk bedankt voor uw medewerking,
NPTV

**Comment by evelynedewitte** [comment]
And yet another (small) update to the text:

Beste thuisverpleegkundige,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (o.a. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen en thuisverpleegkundigen) van nabij te volgen en zo knelpunten in de eerste lijn vroeger te detecteren en sneller gericht oplossingen te kunnen aanbieden.

Deze monitoring werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134). Concreet worden de gegevens gebruikt ter ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en de Nationale Crisiscel in de sturing van het beleid.

Voor de thuisverpleegkundigen werd deze barometer opgemaakt door het Nederlandstalig Platform voor Thuisverpleegkundigen (NPTV) en zal de monitoring tweemaal per week gebeuren, op maandag en op woensdag, tussen 15u en 22u.

Er zijn 2 verschillende vragenlijsten: 1 voor diensten voor thuisverpleging (loontrekkenden) en 1 voor zelfstandige thuisverpleegkundigen. Gelieve de juiste vragenlijst in te vullen.

**Pas op: per dienst hoeft er slechts één vragenlijst ingevuld te worden.**

Uw e-mailadres wordt gebruikt om de follow-up monitoring aan te kondigen. Alle gegevens zullen in verder wetenschappelijk onderzoek anoniem verwerkt worden. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst, die geheel vrijwillig is en op elk moment kan worden onderbroken.

Mogen wij u vragen deze korte vragenlijst op maandag & woensdag in te vullen tussen 15h en 22h?

Alvast hartelijk bedankt voor uw medewerking,
NPTV

**Comment by evelynedewitte** [comment]
@maerckaert 

Please put this phrase in bold:
**Pas op: per dienst hoeft er slechts één vragenlijst ingevuld te worden.**

The rest is fine!

**Comment by evelynedewitte** [comment]
@neuronick 
Update on the FR landing page:

Please **remove** the phrase: Ce baromètre a été établi, pour les infirmières à domicile, par Inficonsor: Consortium Infirmier.

**Comment by neuronick** [comment]
deployed to PROD
