### ISSUE TITLE
Home nurses NL + FR: create survey "Home nurses"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#66]
There are 2 "different" types of data providers: 
- indipendent home nurses
- home nurses working for a "home nursing service"

The client created 2 different forms:
- indipendent home nurses
- home nurses working for a "home nursing service"

the difference are (at first glance):
- Question 1. "Naam van de Dienst voor Thuisverpleging" vs "Naam van de praktijk"
- troughout the following questions , reference is made to "de Dienst voor Thuisverpleging" vs "de praktijk"

Decision:
- 1 form vs 2 forms

ALSO:
- the questions on availability of materials are different from GP, CRA, .... I asked to align with GP, CRA, ... no feedback yet. My suggestion: start already and copy paste the version "availability of materials" of GP, CRA, ... 

[https://app.zenhub.com/files/248791371/6fddc379-cf04-4a0d-b6ab-1c8f6282aab0/download](https://app.zenhub.com/files/248791371/6fddc379-cf04-4a0d-b6ab-1c8f6282aab0/download)

**Comment by JohanvanBussel** [comment]
No FR translation yet

**Comment by neuronick** [comment]
Technically we can use 1 parameterised form.

Then we can use two buttons on the landing page instead of one linking to:
https://covid19.healthdata.be/nl/nurses?type=1 (independent)
https://covid19.healthdata.be/nl/nurses?type=2 (nursing service)

We questions labels can be switched based on the provided type. Type will be a hidden field, also sent to DWH.

Please let us know if this approach is fine. Otherwise we will create 2 forms.

**Comment by VrankenKris** [comment]
This has to be done in a generic way (like the others) because all of our logic after getting the data (and even in getting the data) is based on standards. So, please 2 different forms with different names (like gp, midwives, pharmacist, cra and triage)

**Comment by neuronick** [comment]
The form are created and deployed to ACC:
https://covid19-acc.healthdata.be/nl/hn_emp/status
https://covid19-acc.healthdata.be/nl/hn_ind/status

DWH REST handler is also added for the following end-points on ACC:
http://10.72.128.65:9090/generic/hd_covid_hn_emp_status
http://10.72.128.65:9090/generic/hd_covid_hn_ind_status

**Comment by evelynedewitte** [comment]
Form - home nurses employed:
- LOONTREKENDEN --> replace by: LOONTRE**KK**ENDEN
- BESCHIKBAARHEID MEDISCH MATERIAAL: 
-- Met deze vragen polsen we naar **DE** beschikbaarheid van medisch materiaal om u voldoende te kunnen beschermen
-- Algemeen --> er mist een antwoordoptie: "geen tekort, geen overschot" @JohanvanBussel, akkoord?

**Comment by JohanvanBussel** [comment]
Neen, er is geen antwoordoptie tekort. Consortium zegt dat ze er lang over gediscussieerd hebben...

**Comment by evelynedewitte** [comment]
Form - home nurses independent:

-- Met deze vragen polsen we naar **DE** beschikbaarheid van medisch materiaal om u voldoende te kunnen beschermen (same as for the previous form)

- Shouldn't "Aantal zorgmedewerkers dat ziek is en niet kan werken (incl. zorgkundigen) op het moment van de bevraging) always be >= than "Aantal zorgmedewerkers (incl. zorgkundigen) dat positief heeft getest op COVOID-19 en thuis is op het moment van de bevraging"? There is no such check. @JohanvanBussel @neuronick

**Comment by JohanvanBussel** [comment]
het gaat denk ik over beschikbaar zijn van medewerkers, en zo indicatie werklast, niet over afwezigheid omwille van covid...

**Comment by VrankenKris** [comment]
In de documenten moeten er geen checks ingebouwd worden dacht ik. --> Johan
Enkele de postcode wordt nu ‘autocompleted’

Want in de andere documenten zijn zo ook geen checks ingebouwd (terwijl het wle zou kunnen)



Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

**Comment by VrankenKris** [comment]
Ik heb net in GP ingevuld dat er 4 werkzaam zijn en 100 ziek…

Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

From: Kris Vranken
Sent: Saturday, March 28, 2020 4:20 PM
To: 'Sciensano-Healthdata/HD-Corona' <reply@reply.github.com>; Sciensano-Healthdata/HD-Corona <HD-Corona@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Sciensano-Healthdata/HD-Corona] Home nurses NL + FR: create survey "Home nurses" (#66)

In de documenten moeten er geen checks ingebouwd worden dacht ik. --> Johan
Enkele de postcode wordt nu ‘autocompleted’

Want in de andere documenten zijn zo ook geen checks ingebouwd (terwijl het wle zou kunnen)



Kris Vranken
Technical Lead
Healthdata.be
M + 32 491 08 02 05
Skype kriswiv
[cid:image002.jpg@01D5962C.5D529BC0]
Rue Juliette Wytsmanstraat 14 • 1050 Brussels
www.sciensano.be<http://www.sciensano.be/>

P  Please consider the environment before printing this e-mail

**Comment by evelynedewitte** [comment]
@neuronick 

If I click on the links:
https://covid19-acc.healthdata.be/nl/hn_emp/status
https://covid19-acc.healthdata.be/nl/hn_ind/status

I do not see any changes. What do I need to check?

**Comment by evelynedewitte** [comment]
Changes verified on ACC.

**Comment by JohanvanBussel** [comment]
TRANSLATIONS: 
- Naam van de Dienst voor Thuisverpleging = Nom du service de soins infirmiers à domicile
- Provincie = Province
- Aantal zorgmedewerkers, actief aan het werk in de Dienst (incl. zorgkundigen) op het moment van de bevraging = Nombre de professionnels de la santé travaillant activement au service (y compris aides-soignants) au moment de l'enquête
- Aantal zorgmedewerkers dat ziek is en niet kan werken (incl. zorgkundigen) op het moment van de bevraging = Nombre de professionnels de la santé qui est malade et ne peut pas travailler (y compris aides-soignants) au moment de l'enquête
- Aantal zorgmedewerkers (incl. zorgkundigen) dat positief heeft getest op COVOID-19 en thuis is op het moment van de bevraging = Nombre de professionnels de la santé (y compris. aides-soignants) qui ont été testés positifs pour COVOID-19 et à la maison au moment de l'enquête
- Hoeveel patiënten zijn er vandaag in zorg die positief hebben getest op COVID-19? = Combien de patients qui ont été testés positifs pour Covid-19 sont pris en charge aujourd'hui?
- Hoeveel patiënten zijn vandaag potentieel besmet met COVID-19 (patiënten met symptomen)? = Combien de patients sont potentiellement infectés par COVID-19 (patients présentant des symptômes) aujourd'hui?
- Hoeveel patiënten hebt u vandaag in cohortzorg? = Combien de patients avez-vous en soins de cohorte aujourd'hui?

**Comment by JohanvanBussel** [comment]
**TRANSLATION FORM ZELFSTANDIGE THUISVERPLEEGKUNDIGEN:**

- Naam van de praktijk = Nom de la pratique
- E-mailadres contactpersoon = Adresse e-mail de contact
- Aantal zorgmedewerkers, actief aan het werk in de Dienst (incl. zorgkundigen) op het moment van de bevraging = Nombre de professionnels de la santé travaillant activement au pratique (y compris aides-soignants) au moment de l'enquête
- Aantal zorgmedewerkers dat ziek is en niet kan werken (incl. zorgkundigen) op het moment van de bevraging = Nombre de professionnels de la santé qui est malade et ne peut pas travailler (y compris aides-soignants) au moment de l'enquête
- Aantal zorgmedewerkers (incl. zorgkundigen) dat positief heeft getest op COVOID-19 en thuis is op het moment van de bevraging = Nombre de professionnels de la santé (y compris. aides-soignants) qui ont été testés positifs pour COVOID-19 et à la maison au moment de l'enquête
- Hoeveel patiënten zijn er vandaag in zorg die positief hebben getest op COVID-19? = Combien de patients qui ont été testés positifs pour Covid-19 sont pris en charge aujourd'hui?
- Hoeveel patiënten zijn vandaag potentieel besmet met COVID-19 (patiënten met symptomen)? = Combien de patients sont potentiellement infectés par COVID-19 (patients présentant des symptômes) aujourd'hui?
- Hoeveel patiënten hebt u vandaag in cohortzorg? = Combien de patients avez-vous en soins de cohorte aujourd'hui?

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/41f897ad-b07b-41c5-bc1b-c9362c68a583)

CHANGE TITLE: "COVID19 - DAGELIJKSE STATUS ZELFSTANDIGE THUISVERPLEEGKUNDIGEN" => IN TO **"COVID19 - STATUS ZELFSTANDIGE THUISVERPLEEGKUNDIGEN"** (so delete word "DAGELIJKSE")

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/751bedd6-1fd2-4036-98da-718c3609ea6b)

CHANGE TITLE: "COVID19 - DAGELIJKSE STATUS VOOR DIENSTEN VOOR THUISVERPLEGING (LOONTREKKENDEN)" => IN TO **"COVID19 - STATUS VOOR DIENSTEN VOOR THUISVERPLEGING (LOONTREKKENDEN)"** (so delete word "DAGELIJKSE")

**Comment by neuronick** [comment]
Translations and changes are added to ACC:
https://covid19-acc.healthdata.be/fr/hn_ind/status
https://covid19-acc.healthdata.be/fr/hn_emp/status

**Comment by evelynedewitte** [comment]
Update:

Add an additional numerical field when someone indicates a shortage (tekort/penurie) / protective gear.

See COVID19_fields file on Dropbox for home nurses:

- nr_num_surgical_masks
- nr_num_alc_hand_disinfectant
- nr_num_infection_masks
- nr_num_infection_gloves
- nr_num_infection_aprons
- nr_num_infection_screen

**Comment by evelynedewitte** [comment]
### NL version

**Page 1: add the following 2 questions**

‘Hoeveel zorgmedewerkers zijn er ingeschakeld in cohortzorg binnen de organisatie’
‘Hoeveel zorgmedewerkers zijn er ingeschakeld in cohortzorg buiten de organisatie’

**Besmettingen**: add as first question:
Hoeveel patiënten heeft u vandaag in zorg?

**Remark**: update the following question:

- as-is: "Hoeveel patiënten zijn er vandaag in cohortzorg?"

- to-be: "Hoeveel patiënten zijn er vandaag in cohortzorg binnen de organisatie?"

**Comment by evelynedewitte** [comment]
@neuronick 
As just agreed, please adapt the fields as I specified them in my previous comment. When you are done with the fields --> send an e-mail to @VrankenKris to let him know.

**Comment by VrankenKris** [comment]
checked in acceptance, data is ok. Can be deployed to production

**Comment by evelynedewitte** [comment]
@neuronick 

Just checked NL version in acceptance: one small remark:

- At the end of the survey for the **independent home nurses**, we also have to show the "Thank you" message as shown for the employed home nurses.

So for employed home nurses --> OK
For independent home nurses --> add the same thank you message as for the employed.

**Comment by evelynedewitte** [comment]
@neuronick 

Just checked the FR version in acceptance:

**Employed home nurses** --> still 3 questions need to be translated to French. I added the French translation in the COVID19_fields file:
- nr_num_cp_cohort_inside
- nr_num_cp_cohort_outside
- nr_num_patients

To add when the form has been submitted:
Merci!
Les infirmières à domicile sont suivies deux fois par semaine, les lundis et mercredis, de 15h à 22h.

**Comment by neuronick** [comment]
Translations added to ACC

**Comment by neuronick** [comment]
deployed to prod
