### ISSUE TITLE
Family care services NL: create landing page

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#67]

**Comment by evelynedewitte** [comment]
Text NL gezinszorg

Beste zorgkundige,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen en thuisverpleegkundigen) van nabij te volgen en kan er zo nodig via de feedback hulp aangeboden worden. De monitoring van bij de gezinszorg gebeurt tweemaal per week, op maandag en op woensdag, tussen 15u en 22u.

Voor de gezinszorg werd deze barometer opgemaakt door het **XXX**.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en Nationale Crisiscel.

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Uw e-mailadres wordt gebruikt om de samenvatting van de resultaten naar u op te sturen en om de follow-up monitoring aan te kondigen. Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig en kan steeds onderbroken worden. Uw gegevens worden op dit moment gebruikt om het beleid te sturen en alle gegevens zullen in verder wetenschappelijke onderzoek anoniem verwerkt worden.

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

**Comment by evelynedewitte** [comment]
Contactperson (for myself):
Ewout@zorggezind.be (Ewout Vanormelingen)

**Comment by evelynedewitte** [comment]
@JohanvanBussel @VrankenKris 

No French version is needed today. VZW zorggezind only concerns the Flemish provinces + Brussels.

**Comment by neuronick** [comment]
Preliminary version is created on ACC:
https://covid19-acc.healthdata.be/nl/fcs

**Comment by evelynedewitte** [comment]
Update on the NL text:

Beste medewerker gezinszorg,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen en thuisverpleegkundigen) van nabij te volgen en zo knelpunten in de eerste lijn vroeger te detecteren en sneller gericht oplossingen te kunnen aanbieden.

De monitoring van bij de gezinszorg gebeurt tweemaal per week, op maandag en op woensdag, tussen 15u en 22u.

Voor de gezinszorg werd deze barometer opgemaakt door vzw Zorggezind.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en Nationale Crisiscel.

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig en kan steeds onderbroken worden. Uw gegevens worden op dit moment gebruikt om het beleid te sturen en alle gegevens zullen in verder wetenschappelijke onderzoek anoniem verwerkt worden.

Voor inhoudelijke vragen bij deze gegevensverzameling: ewout@zorggezind.be

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

Alvast hartelijk bedankt voor uw medewerking,
vzw Zorggezind

**Comment by evelynedewitte** [comment]
Update on the NL text:

Beste,

Tijdens deze COVID-19 pandemie werd het landelijk monitoringsproject "COVID-19 Barometer" opgestart om de status van de eerste lijn (oa. bij huisartsen, coördinerende en raadgevende artsen, triageposten, apothekers, vroedvrouwen, thuisverpleegkundigen en diensten voor gezinszorg) van nabij te volgen en zo knelpunten in de eerste lijn vroeger te detecteren en sneller gericht oplossingen te kunnen aanbieden.

De monitoring van bij de gezinszorg gebeurt tweemaal per week, op maandag en op woensdag, tussen 15u en 22u.

Voor de gezinszorg werd deze barometer in samenwerking met vzw Zorggezind en Vivel opgemaakt. Bepaalde vragen werden bewust uniform gehouden binnen het geheel van de barometer. Diensten die in meerdere provincies actief zijn, vullen dit formulier per provincie in.

Deze gegevens zullen gebruikt worden voor de ondersteuning van de COVID19 Risk Assessment Group, COVID19 Risk Management Group, en Nationale Crisiscel.

Deze registratie werd aangemeld bij, en beoordeeld en toegestaan door de kamer sociale zekerheid en gezondheid van het InformatieVeiligheidsComité (referentie IVC/KSZG/20/134).

Het invullen van het mailadres geldt als aanvaarding van deelname aan deze vragenlijst. Deze vragenlijst is volledig vrijwillig en kan steeds onderbroken worden. Uw gegevens worden op dit moment gebruikt om het beleid te sturen en alle gegevens zullen in verder wetenschappelijke onderzoek anoniem verwerkt worden.

Voor inhoudelijke vragen bij deze gegevensverzameling: info@zorggezind.be

Voor technische vragen bij deze gegevensverzameling: support.healthdata@sciensano.be

Alvast hartelijk bedankt voor uw medewerking!

**Comment by neuronick** [comment]
Text updated:
https://covid19-acc.healthdata.be/nl/fcs

**Comment by evelynedewitte** [comment]
Yes!

**Comment by neuronick** [comment]
Deployed to PROD:
https://covid19.healthdata.be/nl/fcs
https://covid19.healthdata.be/fr/fcs

**Comment by evelynedewitte** [comment]
Reviewed in prod and validated
