### ISSUE TITLE
Family care services NL: create survey

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#68]

**Comment by evelynedewitte** [comment]
Take the survey as for Home Nurses but:

Zou het mogelijk zijn om meerdere provincies te kunnen selecteren en/of een knop Vlaams gewest toe te voegen? De grote diensten zitten namelijk vaak over meerdere provincies verspreid of over het hele gewest.
 
Wat de vragen over besmettingen van cliënten betreft zouden we de eerste twee willen vervangen door één vraag:
Hoeveel cliënten zijn er vandaag (potentieel) besmet met COVID-19 (cliënten met symptomen)?
 
Capaciteit:
Is het mogelijk om hier bijkomend een vraag naar % uitval van medewerkers toe te voegen?
 
Terminologie:
Binnen gezinszorg spreken we over cliënten en niet over patiënten alsook medewerkers ipv (wanneer er verpleegkundige staat).

**Comment by evelynedewitte** [comment]
I updated the COVID19_fields file by adding the following sheet for Family Care:

- hd_covid_fc_status

**Comment by evelynedewitte** [comment]
1e pagina:
 
Toch reeds de mogelijkheid geven om meerdere provincies en Vlaams Gewest aan te duiden.
 
Graag een opsplitsing bij de vraag naar de situatie van de medewerkers:
 
-       Aantal gezinszorg medewerkers actief aan het werk in de dienst op het moment van de bevraging?
-       Aantal aanvullende thuiszorg medewerkers actief aan het werk in de dienst op het moment van de bevraging?
-       Aantal gezinszorg medewerkers dat wegens ziekte/ preventieve maatregelen thuis zit op het moment van de bevraging?
-       Aantal aanvullende thuiszorg medewerkers dat wegens ziekte/ preventieve maatregelen thuis zit op het moment van de bevraging?
 
De vraag over de positieve testen van medewerkers zouden wij schrappen
 
Besmettingen:
Hier graag nog volgende vraag toevoegen:
 
Aantal cliënten waarbij de zorg tijdelijk is stopgezet omwille van de huidige crisis (zelf afbellen, prioritering, …).
(dit heeft niet rechtstreeks met besmettingen te maken maar lijkt ons de beste plaats om dit te bevragen).

**Comment by neuronick** [comment]
Form created and deployed to ACC:
https://covid19-acc.healthdata.be/nl/fcs/status

**Comment by evelynedewitte** [comment]
Please perform the following changes on ACC:

**Start page**
- [ ] Province (cd_province): no longer a multiple-choice needed. Revert back to the drop-down list with the provinces.

- [ ] Add the question: "Aantal aanvullende thuiszorg medewerkers actief aan het werk in de dienst op het moment van de bevraging?" (nr_num_employees_tz) --> already mentioned in the metadata --> no new field for Kris, this question was just not mentioned on the form

Move the following questions to this page:
- [ ] Aantal gezinszorg medewerkers dat wegens ziekte/ preventieve maatregelen thuis zit op het moment van de bevraging? (nr_num_employees_sick)
- [ ] Aantal aanvullende thuiszorg medewerkers dat wegens ziekte/ preventieve maatregelen thuis zit op het moment van de bevraging? (nr_num_employees_sick_tz)

**Besmettingen**
- [ ] Remove the question: "Aantal zorgmedewerkers dat positief heeft getest op COVOID-19 en thuis is op het moment van de bevraging" (nr_num_employees_covid19_pos)

**Capacity**
- [ ] Extra question: "Zijn er regio’s waar jullie geen prioritaire zorgvragen meer kunnen beantwoorden?" 
- [ ] Remove the question: "Heb je nog capaciteit (mensen en middelen) om de komende dagen bijkomende cliënten te verzorgen?" (fl_capacity_next_days) and (tx_capacity_next_days_comments)
- [ ] Add the question: "Heb je nog capaciteit in mensen om de komende dagen bijkomende cliënten te verzorgen?" (fl_capacity_next_days_p) and (tx_capacity_next_days_p_comments)
- [ ] Add the question: ""Heb je nog capaciteit in middelen om de komende dagen bijkomende cliënten te verzorgen?"
(fl_capacity_next_days_m) and (tx_capacity_next_days_m_comments)

**Comment by evelynedewitte** [comment]
Requested but still to be checked by @evelynedewitte 

- [ ] Remove the question: "Heb je nog capaciteit (mensen en middelen) om de komende dagen bijkomende cliënten te verzorgen?" (**fl_capacity_next_days**) and (**tx_capacity_next_days_comments**)

- [ ] Add the question: "Heb je nog capaciteit in mensen om de komende dagen bijkomende cliënten te verzorgen?" (**fl_capacity_next_days_p**) and (**tx_capacity_next_days_p_comments**)

- [ ] Add the question: ""Heb je nog capaciteit in middelen om de komende dagen bijkomende cliënten te verzorgen?"
(**fl_capacity_next_days_m**) and (**tx_capacity_next_days_m_comments**)

**Comment by neuronick** [comment]
Most of the tasks are implemented, except for the capacity (still need the answer about values / codes).

@evelynedewitte I have an additional question regarding 'Naam dienst' (based on the provided list). For the moment instead of changing **tx_name** I have added a new field **cd_fcs**, which is used by the select (it shows Dienst name, but saves cd_fcs code). The tx_name is currently hidden, but can be automatically populated the the name on the background. 
The question is: do we need to send cd_fcs AND tx_name to the DWH or would just cd_fcs suffice? Or may be we don't need the **cd_fcs** at all?

**Comment by evelynedewitte** [comment]
@neuronick Let's discuss this together with @VrankenKris

**Comment by evelynedewitte** [comment]
@neuronick 

Most of the tasks are implemented, except for the capacity (still need the answer about values / codes). We will have to create the codes ourselves.

**Comment by evelynedewitte** [comment]
See update in the covid19_fields file for the NL version

**Comment by neuronick** [comment]
cd_capacity_region is implemented

**Comment by evelynedewitte** [comment]
Verified & validated

**Comment by neuronick** [comment]
Deployed to PROD:
https://covid19.healthdata.be/nl/fcs/status
https://covid19.healthdata.be/fr/fcs/status
