### ISSUE TITLE
Create "Daily status form for Triage posts"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#7]

**Comment by JohanvanBussel** [comment]
Form that will be completed on daily basis
no user acces needed

Dutch and french have own version of form:
- "Dagelijkse status formulier voor triage posten" (NL)
- "Formulaire de statut quotidien pour les postes de triage" (FR)

Doc:
- https://docs.google.com/forms/d/e/1FAIpQLSfmv5JoRil-0gDGugyPDzHkZZRYJ4B5qP9KAxa74G9-FDjo7w/viewform

**Comment by neuronick** [comment]
Form drafts can be found here:
https://hd4patient-acc.healthdata.be/nl/covid19/triage_centers/status
https://hd4patient-acc.healthdata.be/fr/covid19/triage_centers/status

Triage registration is added as the first step.

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/f0599a10-8764-4da7-8d08-03e07c2feb7a)

vertaling naar frans nodig:
- Beschikbaarheid medisch materiaal

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/b69b1355-2867-4386-b86f-6f4f43cc61ef)
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/f1c5435b-7ae7-480e-bc60-56f72a694c36)

The **correct sequence is always**:
- Grande pénurie
- Petite pénurie
- Petit surplus
- Grand surplus

- Groot tekort
- Klein tekort
- Klein overschot
- Groot overschot

**This should be corrected everywere in the form!**
see:
- Alcoholische handontsmetting
- Gewone chirurgische maskers
- Maskers geschikt te gebruiken bij infecties (FFP2 en co)
- Handschoenen geschikt te gebruiken bij infecties
- Schorten geschikt te gebruiken bij infecties
- Bril/scherm geschikt te gebruiken bij infecties

**Comment by JohanvanBussel** [comment]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/8fac90f2-d19d-4805-8335-ca8fdd03199e)

vertaling naar frans nodig voor:
- New submission added to

**Comment by JohanvanBussel** [comment]
Bij de **sectie « besmettingen »** , the **intro**
-  « Met deze vragen proberen we de stijging van besmettingen te monitoren” … 
- change into: 
--“Met deze vragen proberen we de evolutie van besmettingen te monitoren”
-- french: Avec ces questions, nous essayons de surveiller l'evolution des infections.

**Comment by maerckaert** [comment]
Done!
