### ISSUE TITLE
GP NL + FR: status survey : add "Postcode autocomplete"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#78]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/687ffe2a-aca6-4351-b137-7ea732b1e7ac)

add "Postcode autocomplete" with postcode list of HD DWH

**Comment by neuronick** [comment]
Changes deployed to ACC:
https://covid19-acc.healthdata.be/nl/gp/status
https://covid19-acc.healthdata.be/fr/gp/status
