### ISSUE TITLE
CRA NL + FR: status survey : add "Postcode autocomplete"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#79]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/97bb817b-0c8d-48e8-b9b9-2371868b78c0)

add "Postcode autocomplete" based on postcode list of HD DWH

**Comment by neuronick** [comment]
Changes deployed to ACC:
https://covid19-acc.healthdata.be/nl/cra/status
https://covid19-acc.healthdata.be/fr/mcc/status
