### ISSUE TITLE
Create "Registration form for Triage posts"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#8]

**Comment by JohanvanBussel** [comment]
Seperate version for Dutch and French:
- "Registratie formulier voor triage posten" (NL)
- "Formulaire d'inscription pour les postes de triage" (FR)

Will only be complete once!

Final version, but Dutch and French in same form => 
- https://docs.google.com/forms/d/e/1FAIpQLSdf9SI8Xz8bQ9GjW_yc9CJvIpDDoTLYimitqF8BI2TybRNeWA/viewform

**Comment by neuronick** [comment]
Form drafts can be found here:
http://hd4patient-acc.healthdata.be/nl/covid19/triage_centers/register
http://hd4patient-acc.healthdata.be/fr/covid19/triage_centers/register

**Comment by JohanvanBussel** [comment]
IMPORTANT: "Registration form for triage posts" should be merged into => Create "Daily status form for triage posts" ,

=> Thus, an independent form "Registration form for triage posts" becomes obsolete, should be removed/deleted.
