### ISSUE TITLE
TRIAGE NL + FR: status survey : add "Postcode autocomplete"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#80]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/dbcdbf7f-388d-4611-88e0-2f53b7a04165)

add "Postcode autocomplete" based on postcode list of HD DWH

**Comment by neuronick** [comment]
Changes deployed to ACC:
https://covid19-acc.healthdata.be/nl/triage/status
https://covid19-acc.healthdata.be/fr/triage/status
