### ISSUE TITLE
Pharmacist NL + FR: status survey : add "Postcode autocomplete"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#81]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/5524caca-d5ea-42fc-8315-98aff30de7d5)

add "Postcode autocomplete" based on postcode list of HD DWH

**Comment by neuronick** [comment]
Changes deployed to ACC:
https://covid19-acc.healthdata.be/nl/pharmacists/status
https://covid19-acc.healthdata.be/fr/pharmacists/status
