### ISSUE TITLE
MAIN LANDINGPAGE: NL + FR: replace button midwives after pharmacists (2nd line)  

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#85]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/fdc96f23-7d25-4c0b-954b-fb01745ea2ba)

replace button midwives after pharmacists (2nd line)

**Comment by neuronick** [comment]
Changes made and deployed to ACC. Is it ok now?
