### ISSUE TITLE
Pharmacists NL + FR : status form: create autocomplete of "APB nummer van de apotheek"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#86]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/4b20be7c-2626-4f7d-a082-4192b1f2d28f)

create autocomplete of "APB nummer van de apotheek" with list available in excel
discuss approach with HD DWH 

[https://app.zenhub.com/files/248791371/c253c674-b122-45b0-8e9d-04a184ab1cae/download](https://app.zenhub.com/files/248791371/c253c674-b122-45b0-8e9d-04a184ab1cae/download)

**Comment by evelynedewitte** [comment]
@neuronick 
Tested & validated in ACC.
