### ISSUE TITLE
Pharmacists NL + FR: status form: prefill "Naam van de apotheek waar u titularis van bent" based on "APB nummer van de apotheek"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#87]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/a59b6d77-fd29-4dd4-93bb-eb4290d460b6)

prefill "Naam van de apotheek waar u titularis van bent" based on "APB nummer van de apotheek"

**Comment by evelynedewitte** [comment]
@neuronick 

On ACC this works fine.

As  you mentioned, when I correct the APB number _after_ the pre-fill took place, the pre-filled fields do not change with my correction.
How much effort does it take to improve this functionality in order for the pre-filled fields to be updated too?

**Comment by neuronick** [comment]
@evelynedewitte It's a small and easy change but there are repercussions: in this case each time apb nummer changes the autofilled fields will be overwritten (even if you filled or corrected something in there by hand).
If this is a desired behaviour - please let me know and I will deploy the change.

**Comment by evelynedewitte** [comment]
@neuronick 
You mean the other autofilled fields that have nothing to do with APB number?

**Comment by neuronick** [comment]
@evelynedewitte They do (they are prefilled based on the APB number), but you can always change them afterwards.
Example: 
1) You select APB Number
2) Name and Postal code are prefilled by the info we have connected to the APB number in question
3) You notice that the Name contains a typo or is not fully correct and you go to the Name field and change something.
4) With the new fix if you now change the APB number, your corrections will be overwritten by the prefill. With the old behaviour, if the system notices that there is already a value provided in the field - it will not change it.

**Comment by neuronick** [comment]
I have applied the fix and deployed to ACC / PROD. If needed we can always revert to the original behaviour (its one line change).
