### ISSUE TITLE
Pharmacist NL + FR Landing page: ADD text

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#89]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/6d9a203b-673b-4e1a-88de-ac289ab7a1dd)

NL: **BETWEEN** the lines "Op basis van de gegevens die u registreert ...." **AND** "Deze registratie werd aangemeld bij, en beoordeeld ..." : **ADD** following text:
"De nieuwe Europese Algemene Verordening omtrent Gegevensbescherming (AVG), die sinds 25 mei 2018 van kracht is, legt bijkomende vereisten op over hoe bedrijven of organisaties uw persoonsgegevens mogen gebruiken. Een van die vereisten is dat de verantwoordelijke voor de verwerking u onderstaande informatie bezorgt. 

Zoals reeds aangegeven worden in het kader van het onderzoek waar u aan deelneemt, persoonsgegevens van u verzameld. Wij, Sciensano en de Vrije Universiteit Brussel, zijn verantwoordelijk voor de correcte verwerking en de informatieplicht die daarmee gepaard gaat. 

U heeft het recht om een klacht in te dienen over hoe uw informatie wordt behandeld. Dit kan u doen bij de Belgische toezichthoudende instantie die verantwoordelijk is voor het handhaven van de wetgeving rond gegevensbescherming:
Gegevensbeschermingsautoriteit (GBA)
Drukpersstraat 35,
1000 Brussel
Tel. +32 2 274 48 00
e-mail: contact@apd-gba.be
Website: www.gegevensbeschermingsautoriteit.be”

=============================
FR: **BETWEEN** the lines "Sur la base des données que vous enregistrez ...." **AND** "Cet enregistrement a été notifié, évalué ..." : **ADD** following text:

still in translation

**Comment by maerckaert** [comment]
Done in Dutch. Waiting for French translation.

**Comment by JohanvanBussel** [comment]
FR: BETWEEN the lines "Sur la base des données que vous enregistrez ...." AND "Cet enregistrement a été notifié, évalué ..." : ADD following text:

Comme déjà indiqué, des données personnelles sont collectées auprès de vous dans le cadre des recherches auxquelles vous participez. Nous, Sciensano et la Vrije Universiteit Brussel, sommes responsables du traitement correct et de l'obligation de fournir des informations.

Vous avez le droit de vous plaindre du traitement de vos informations. Vous pouvez le faire avec l'autorité de surveillance belge chargée de faire respecter la législation sur la protection des données:
Autorité de protection des données (ADP)
Drukpersstraat 35,
1000 Bruxelles
Tél. +32 2 274 48 00
email: contact@apd-gba.be
Site Web: www.dataprotectionauthority.be
