### ISSUE TITLE
Create "Registration form for Pharmacists"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#9]

**Comment by JohanvanBussel** [comment]
Seperate version for Dutch and French:
- "Registratie formulier voor apothekers" (NL)
- "Formulaire d'inscription pour les pharmaciens" (FR)

Will only be complete once!
- No examples available yet: should be aligned with GP etc

**Comment by neuronick** [comment]
As discussed via Skype, this one is included into daily status.
