### ISSUE TITLE
Midwives Barometer: complete form in metadata.healthdata.be and push to fair.healthdata.be

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#94]

**Comment by neuronick** [comment]
@evelynedewitte The metadata form container more than a 100 fields / questions which are highly subject matter / content oriented. This information is usually filled-in by the researcher(s).

I can help with the populating the data, but this is mostly about content...

**Comment by JohanvanBussel** [comment]
completion metadata form is currently no priority. 
description of dataset is priority. Is already done
Therefore this card in Icebox
