### ISSUE TITLE
Pharmacists FR + NL: landing page: REPLACE "bert.vaes@kuleuven.be" by "Eline.Tommelein@vub.be"

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#96]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/cfc92604-2a8c-4a5b-9dab-ab1c8e9d9e29)

REPLACE "bert.vaes@kuleuven.be" by "Eline.Tommelein@vub.be"

**Comment by neuronick** [comment]
Change is implemented on ACC and PROD
