### ISSUE TITLE
CRA/MCC FR + NL: Status form, section "Besmettingen": CHANGE question

### ISSUE THREAD

**Issue by JohanvanBussel** [Sciensano-Healthdata/HD-Corona#98]
![image.png](https://images.zenhubusercontent.com/5c0f5944b1e8912f0823876f/b227471b-8313-43d9-8143-5aa209d4ab45)

NL: CHANGE "Zijn er reeds bewoners met corona in uw rust- en verzorgingstehuis (RVT)? " INTO "Zijn er reeds bewoners klinisch verdacht of bewezen met corona in uw rust- en verzorgingstehuis (RVT)?"

FR: CHANGE "Y a-t-il déjà des résidents avec une infection COVID-19 dans votre maison de repos et de soins?" INTO "Y a-t-il déjà des résidents avec une infection COVID-19 éprouvés ou suspecté cliniquement dans votre maison de repos et de soins?"

**Comment by neuronick** [comment]
Changes made and deployed to ACC
